import {test} from 'node:test';
import assert from 'node:assert/strict';
import {blankState,normalizeState} from '../src/state.js';
import {normalizeLife} from '../src/life-state.js';
import {lifeState,awardDiscovery,dailyActivity,recordScene,startOuting,chooseOuting,finishOuting,displayCurio,selectFrame,visitorActivity,solveVisitorActivity,welcomeBack} from '../src/engine/life.js';
import {OUTINGS,GEAR,RELICS,visitorActFor} from '../src/content/life.js';
import {VISITORS} from '../src/content/stories.js';
import {newCourt,accuseCourt} from '../src/engine/court.js';
import {advanceStories,advanceCase,caseGate,startNextCase,storyState} from '../src/engine/stories.js';
import {newChase,updateChase,jumpChase,recordChase,chaseRecordKey} from '../src/engine/chase.js';
import {newHandshake,tapHandshake,rewardHandshake,playWait} from '../src/engine/play.js';
const now=new Date(2026,8,5,12).getTime();
function fixture(stats=3){const s=blankState();s.lastTick=now;s.life.introDone=true;s.pets=[{id:'a',name:'Pip',traits:[],stats:{cute:stats,menace:stats,damp:stats,mystique:stats},needs:{food:60,fuss:60,clean:60},bond:0,cared:0,art:{}}];s.slots[0]='a';return s;}
function complete(s,at=now){const g=newHandshake(s.pets[0],()=>.1);for(let i=0;i<3;i++)for(const x of g.sequence.slice(0,i+2))tapHandshake(g,x);return rewardHandshake(s,g,at);}
test('legacy shelves skip onboarding while new shelves have a progressive introduction',()=>{assert.equal(normalizeLife(undefined,true).introDone,true);assert.equal(normalizeLife(undefined,false).introDone,false);const s=fixture();s.life.introDone=false;s.life.introStarted=true;advanceStories(s,now);assert.equal(s.stories.case,undefined);complete(s);advanceStories(s,now);assert.ok(s.stories.case);});
test('life normalization bounds malformed backup data without losing realistic timestamps',()=>{const l=normalizeLife({xp:-4,frame:'bad',displayed:['a','a','b','c','d'],lastSeen:now,outing:{cast:['a'],step:9},visitorEpisodes:{moth:99},scenes:Array.from({length:50},(_,id)=>({id,title:'T',text:'X',cast:['a','b','c'],at:now}))});assert.equal(l.xp,0);assert.equal(l.frame,'wood');assert.equal(l.displayed.length,3);assert.equal(l.lastSeen,now);assert.equal(l.outing,null);assert.equal(l.scenes.length,18);assert.equal(l.visitorEpisodes.moth,3);});
test('discoveries have bounded daily activities and permanent unlocks without a streak penalty',()=>{const s=fixture();assert.ok(dailyActivity(s,'care',now));assert.equal(dailyActivity(s,'care',now),false);awardDiscovery(s,'game:memory',3);assert.equal(awardDiscovery(s,'game:memory',3),false);assert.equal(s.life.xp,4);assert.equal(selectFrame(s,'brass'),false);dailyActivity(s,'care',now+86400000);dailyActivity(s,'play',now+86400000);assert.equal(selectFrame(s,'brass'),true);assert.equal(s.life.xp,6);});
test('practice remembers completed games and rewards are independent across game types',()=>{const s=fixture(),p=s.pets[0];assert.equal(complete(s).practice,false);const bond=p.bond;assert.equal(complete(s).practice,true);assert.equal(p.handshakes,2);assert.equal(p.bond,bond);assert.equal(playWait(p,now,'chase'),0);assert.ok(playWait(p,now,'memory'));const loaded=normalizeState(s);assert.ok(playWait(loaded.pets[0],now,'memory'));assert.equal(loaded.pets[0].handshakes,2);});
for(const route of OUTINGS)test(route.name+' preserves three legacy prizes and reloadable, single-claim results',()=>{
 const found=new Set();
 for(const stat of [3,8])for(const gear of GEAR)for(let mask=0;mask<8;mask++){
  let s=fixture(stat);assert.equal(startOuting(s,route.id,gear.id,['a','a']),true);delete s.life.outing.version; // Simulate a saved trip begun before trail planning existed.
 assert.equal(startOuting(s,route.id,gear.id,['a']),false);assert.equal(chooseOuting(s,8,now),null);
  chooseOuting(s,mask&1,now);s=normalizeState(s);chooseOuting(s,(mask>>1)&1,now);const end=chooseOuting(s,(mask>>2)&1,now);found.add(end.relic.id);const xp=s.life.xp;assert.equal(chooseOuting(s,0,now),null);assert.equal(s.life.xp,xp);assert.equal(s.pets[0].expeditions,1);assert.equal(finishOuting(s),true);assert.equal(finishOuting(s),false);
 }
 assert.deepEqual([...found].sort(),RELICS.filter(r=>r.id.startsWith(route.id+':')).map(r=>r.id).sort());
});
test('a rehomed expedition crew cannot receive or duplicate rewards',()=>{const s=fixture();startOuting(s,'drawer','thread',['a']);s.pets=[];assert.equal(chooseOuting(s,0,now),null);assert.equal(s.life.outing,null);assert.equal(s.life.relics.length,0);});
test('curiosities require ownership and displaying a fourth replaces the oldest',()=>{const s=fixture();s.life.relics=RELICS.slice(0,4).map(r=>r.id);assert.equal(displayCurio(s,'invented'),false);s.life.relics.forEach(id=>displayCurio(s,id));assert.deepEqual(s.life.displayed,s.life.relics.slice(1));displayCurio(s,s.life.relics[1]);assert.equal(s.life.displayed.length,2);});
for(const guest of VISITORS)test(guest.name+' has three distinct chapters with persistent once-per-visit awards',()=>{const s=fixture();storyState(s);const titles=[];for(let chapter=0;chapter<3;chapter++){s.stories.visitor={kind:guest.id,at:now,welcomed:true,hostId:'a'};const act=visitorActivity(s);assert.equal(act.chapter,chapter);titles.push(act.title);assert.equal(act.choices.length,2);assert.ok(act.clue.length>20);const xp=s.life.xp;assert.equal(solveVisitorActivity(s,act.right,now),true);assert.ok(s.life.xp>=xp+2);assert.equal(solveVisitorActivity(s,1-act.right,now),false);s.life=normalizeLife(s.life);assert.equal(s.life.visitorEpisodes[guest.id],chapter+1);}assert.equal(new Set(titles).size,3);s.stories.visitor={kind:guest.id,at:now,welcomed:true};assert.equal(solveVisitorActivity(s,0,now),false);});
test('visitor activities reject missing welcomes, invalid answers and expired visits',()=>{const s=fixture();storyState(s);s.stories.visitor={kind:'moth',at:now,welcomed:false};assert.equal(solveVisitorActivity(s,0,now),false);s.stories.visitor.welcomed=true;assert.equal(solveVisitorActivity(s,9,now),false);assert.equal(solveVisitorActivity(s,0,now+6*3600000),false);});
test('court scenario rotation explains mistakes and cannot pay twice',()=>{const s=fixture();const titles=[];for(let i=0;i<12;i++){const g=newCourt(s,()=>i/12);titles.push(g.title);const correct=i%2===0,choice=correct?g.answer:(g.answer+1)%3;const r=accuseCourt(s,g,choice,now);assert.equal(r.correct,correct);assert.ok(r.text.includes(g.suspects[g.answer].name));assert.equal(accuseCourt(s,g,choice,now),null);}assert.equal(new Set(titles).size,12);assert.equal(s.life.courtWins,6);assert.equal(s.pets[0].bond,1);});
test('a pending court case cannot charge or credit a rehomed resident',()=>{const s=fixture(),g=newCourt(s);s.pets[0].id='replacement';assert.equal(accuseCourt(s,g,g.answer,now),null);assert.equal(s.life.courtPlays,0);});
test('another household case starts immediately and needs new evidence at the second gate',()=>{const s=fixture();advanceStories(s,now);s.stories.case.beat=6;const kind=s.stories.case.kind;assert.equal(startNextCase(s,now),true);assert.notEqual(s.stories.case.kind,kind);assert.equal(startNextCase(s,now),false);advanceCase(s,'listen',now);complete(s);advanceCase(s,'listen',now);s.slots[0]=null;s.slots[6]='a';advanceCase(s,'listen',now);advanceCase(s,'listen',now);assert.equal(caseGate(s).ready,false);complete(s);assert.equal(caseGate(s).ready,true);});
test('return recap uses actual recorded scenes, stays bounded and survives save restoration',()=>{const s=fixture();lifeState(s).lastSeen=now-3600000;welcomeBack(s,now);assert.equal(s.life.recap.length,1);assert.match(s.life.scenes[0].text,/comfortable/);for(let i=0;i<30;i++)recordScene(s,'care','Title','Text',['a'],now);assert.equal(s.life.scenes.length,18);const loaded=normalizeState(s);assert.equal(loaded.life.scenes.length,18);assert.equal(loaded.life.lastSeen,now);});
test('chase grounds change mechanics and keep fair separate personal bests',()=>{const p=fixture().pets[0],a=newChase(p,{venue:'shelf'}),b=newChase(p,{venue:'moon'});jumpChase(a);jumpChase(b);for(let i=0;i<10;i++){updateChase(a,{},1/60);updateChase(b,{},1/60);}assert.ok(b.player.z>a.player.z);assert.equal(newChase(p,{venue:'bogus'}).venue,'shelf');for(const venue of ['shelf','pantry','moon']){const g=newChase(p,{venue});g.finished=true;g.score=100;recordChase(p,g,now);assert.equal(p.chaseRecords[chaseRecordKey(g)].score,100);}const s=fixture();s.pets=[p];assert.equal(Object.keys(normalizeState(s).pets[0].chaseRecords).length,3);});
