import { marketErrandMarkup } from './market-errands.js';
import { MARKET_TAGS, MARKET_STALLS, RELICS } from '../content/life.js';
import { bestMarketScore, scoreMarket } from '../engine/life.js';
import { curioSVG } from '../art/curios.js';

const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,extra='')=>'<button class="btn" data-life="'+action+'" '+extra+'>'+label+'</button>';
const tags=item=>item.tags.map(t=>'<span class="market-tag tag-'+t+'">'+MARKET_TAGS[t]+'</span>').join('');

function vendorFace(step){
 const hat=step===1?'<path d="M22 30 48 4 74 30Z" fill="#372b44"/><path d="m42 4 5 24" stroke="#e3be89" stroke-width="3"/>':step===3?'<path d="M64 8a25 25 0 1 0 13 43A28 28 0 0 1 64 8" fill="#e7cc89"/>':'<path d="M24 32V18q24-14 48 0v14Z" fill="#322332"/><path d="M18 32h60" stroke="#d6b47a" stroke-width="5"/>';
 return '<svg viewBox="0 0 96 100" role="presentation"><path d="M21 91V51q0-29 27-29t27 29v40l-13-7-14 8-14-8Z" fill="'+(['#ac90aa','#b9a5c9','#9dad78','#6c749f','#c3c7cb','#a89483'][step])+'"/><g class="market-vendor-head">'+hat+'<ellipse cx="36" cy="51" rx="4" ry="5" fill="#211d2a"/><ellipse cx="60" cy="51" rx="4" ry="5" fill="#211d2a"/><path d="M35 68q13 9 26-1" fill="none" stroke="#211d2a" stroke-width="3"/><path d="M45 70v7m9-7v5" stroke="#eee1be" stroke-width="4"/></g><path class="market-vendor-hand" d="m70 75 16-12" stroke="#d8bd9a" stroke-width="9" stroke-linecap="round"/></svg>';
}

function marketStage(step,stock=[],action){
 const actor=Math.min(5,step),reaction=action?MARKET_STALLS[action.step]?.[action.kind==='buy'?'bought':action.kind==='secret'?'secret':'passed']:'';
 return '<div class="market-theatre" aria-hidden="true"><div class="market-awning"></div><span class="market-lantern lantern-a"></span><span class="market-lantern lantern-b"></span><div class="market-vendor">'+vendorFace(actor)+'</div><div class="market-counter-stock">'+stock.map(i=>curioSVG(i.shape,{literal:true})).join('')+'</div><div class="market-counter"></div><div class="market-stage-bag"><span></span></div>'+(action?.item?'<div class="market-purchase-flight">'+curioSVG(action.item.shape,{literal:true})+'</div>':'')+(action?.kind==='secret'?'<div class="market-secret-flight">'+curioSVG('receipt')+'</div>':'')+'</div>'+(reaction?'<p class="market-reaction" role="status">'+esc(reaction)+'</p>':'');
}

function requestCards(m){return '<div class="market-requests">'+m.requests.map((r,i)=>'<article class="market-request '+(m.score.fulfilled[i]?'fulfilled':'')+'"><span class="eyebrow">'+(m.score.fulfilled[i]?'Fulfilled · +4':'Shopping request · 4 points')+'</span><b>'+esc(r.name)+'</b><div class="market-tags">'+tags(r)+'</div><small>'+esc(r.line)+'</small></article>').join('')+'</div>';}

function marketWorkspace(body,actions,phase='playing'){
 return '<section class="adventure-workspace market-workspace phase-'+phase+'"><div class="adventure-scroll">'+body+'</div><footer class="adventure-actions market-action-dock">'+actions+'</footer></section>';
}
export function marketSelectedOffer(m,selection='',trade=''){
 const stock=m?.stalls?.[m.step]||[],buttons=(m?.buttons||0)+(!m?.traded&&m?.bag.some(i=>i.id===trade)?1:0);
 return stock.find(i=>i.id===selection)||stock.find(i=>i.cost<=buttons)||stock[0]||null;
}
export function marketMarkup(state,m,trade='',lastAction=null,selection='',panel=''){
 if(!m||m.version===3)return marketErrandMarkup(state,m,trade,selection,panel,{workspace:marketWorkspace,stage:marketStage,select:marketSelectedOffer});
 const l=state.life;
 if(!m)return marketWorkspace('<div class="market-welcome"><span class="eyebrow">Six stalls · Ten buttons · No timer</span><h3>Leave before the digging starts.</h3>'+marketStage(0)+'<p>The household needs three pairs of things. You have room for three objects and ten buttons to spend.</p></div><ol class="market-rules"><li><b>Build a basket.</b> Buy one object at a stall or pass. Each request needs two separate objects, and one object can help with several requests.</li><li><b>Plan ahead.</b> The route book shows every object and price. Two stalls carry expensive rare keepsakes.</li><li><b>Change your mind once.</b> Trade one packed object for one button while buying its replacement.</li><li><b>Sell a secret, once.</b> Give up a stall’s stock for three buttons. The scandal costs three final points.</li></ol><div class="market-score-rule"><b>Your score</b><span>Charm + 4 per request + spare buttons − 3 if you sell a secret</span></div><p class="hint">Your choices are saved. No timer, real money or resident penalties.</p>',button('Enter the night market','market-start'),'planning');
 if(m.complete){
  const best=bestMarketScore(m.seed,{version:m.version}),tier=m.score.total===best?2:m.score.total>=17?1:0,relic=RELICS.find(r=>r.id==='market:'+tier);
  const body='<div class="market-welcome market-results">'+curioSVG(relic.shape,{literal:true})+'<span class="eyebrow">Nobody followed you home. Yet.</span><h3 tabindex="-1">'+m.score.total+' points. '+(m.score.total===best?'A perfect market.':m.score.total>=23?'You robbed them politely.':m.score.total>=17?'A respectable collection of evidence.':'At least the bag is innocent.')+'</h3><p>'+esc(relic.name)+'<br>'+esc(relic.line)+'</p></div><div class="market-tally '+(m.secret?'has-scandal':'')+'"><div><b>'+m.score.charm+'</b><span>Charm</span></div><div><b>'+m.score.requestPoints+'</b><span>Requests</span></div><div><b>'+m.buttons+'</b><span>Spare buttons</span></div>'+(m.secret?'<div><b>−3</b><span>Scandal</span></div>':'')+'</div><div class="market-record"><b>'+best+' points were possible on this route.</b><span>Your best: '+l.marketBest+' · Markets completed: '+l.marketRuns+'</span></div><details class="market-map"><summary>Your requests and final basket</summary>'+requestCards(m)+m.bag.map(item=>'<p><b>'+esc(item.name)+'</b> · '+item.charm+' charm<br>'+esc(item.line)+'</p>').join('')+(!m.bag.length?'<p>The bag contains nothing. The vendor called it minimalism and charged for the label.</p>':'')+'<p>Retry keeps these stalls, requests and '+(m.version===2?'secret-selling rules':'original shopping rules')+'. Existing keepsakes give no repeat discoveries.</p></details>';
  return marketWorkspace(body,'<div class="market-result-actions">'+button('Try again','market-retry')+button('New market','market-start')+button('Display your keepsake','display')+'</div>','result');
 }
 const traded=!m.traded?m.bag.find(item=>item.id===trade):null,available=m.buttons+(traded?1:0),bag=traded?m.bag.filter(item=>item!==traded):m.bag,stall=MARKET_STALLS[m.step],selected=marketSelectedOffer(m,selection,trade),full=bag.length>=3,short=selected.cost>available,disabled=full||short,projected=scoreMarket([...bag,selected],available-selected.cost,m.requests,m.secret);
 const heading='<div class="market-heading"><div><span class="eyebrow">Stall '+(m.step+1)+' / 6</span><h3 tabindex="-1">'+esc(stall.name)+'</h3></div><div class="market-purse"><b>'+m.buttons+'</b><span>buttons</span></div></div><div class="market-context-nav" aria-label="Market information">'+button('Requests '+m.score.fulfilled.filter(Boolean).length+'/3','market-panel','data-panel="requests" aria-pressed="'+(panel==='requests')+'"')+button('Bag '+m.bag.length+'/3'+(traded?' · trade':''),'market-panel','data-panel="bag" aria-pressed="'+(panel==='bag')+'"')+button('Route '+(6-m.step)+' stops','market-panel','data-panel="route" aria-pressed="'+(panel==='route')+'"')+'</div>';
 let body=heading;
 if(panel){
  body+='<div class="market-context-panel" tabindex="-1"><div class="market-context-heading"><h4>'+({requests:'Shopping requests',bag:'Your bag & trade-in',route:'The remaining route'})[panel]+'</h4>'+button('Back to stall','market-panel','data-panel=""')+'</div>';
  if(panel==='requests')body+='<p class="hint">Each request needs two distinct objects. The same object can help with other requests. Each completed request adds four points.</p>'+requestCards(m);
  if(panel==='bag')body+='<p class="hint">Current basket: '+m.score.total+' points'+(m.secret?', including the −3 scandal':'')+'. Three spaces; one trade-in per trip.</p><div class="market-bag-items">'+m.bag.map(item=>'<div class="market-packed">'+curioSVG(item.shape,{literal:true})+'<div><b>'+esc(item.name)+'</b><span>'+item.charm+' charm · '+item.tags.map(t=>MARKET_TAGS[t]).join(' / ')+'</span></div></div>').join('')+'</div>'+(!m.bag.length?'<p>Your bag is empty. The vendor is already offering to sell you something to put the emptiness in.</p>':'')+(!m.traded&&m.bag.length?'<label class="market-trade-label">Trade with your next purchase<select id="marketTrade"><option value="">Keep everything in the bag</option>'+m.bag.map(item=>'<option value="'+item.id+'" '+(trade===item.id?'selected':'')+'>Trade '+esc(item.name)+' for 1 button</option>').join('')+'</select></label><p class="hint">Trading happens only when you buy. Passing or selling a secret keeps your bag intact.</p>':m.traded?'<p>Your trade-in has been used.</p>':'');
  if(panel==='route')body+='<p class="hint">All stock is shown, including this stall. You can buy one object from each stall.</p><div class="market-map">'+m.stalls.slice(m.step).map((stock,i)=>'<article><b>'+esc(MARKET_STALLS[m.step+i].name)+(i===0?' · here':'')+'</b><div>'+stock.map(item=>'<p><strong>'+esc(item.name)+'</strong><span>'+item.cost+' buttons · '+item.charm+' charm · '+item.tags.map(t=>MARKET_TAGS[t]).join(' / ')+'</span></p>').join('')+'</div></article>').join('')+'</div>';
  body+='</div>';
 }else{
  const stage=marketStage(m.step,m.stalls[m.step],lastAction),reactionAt=stage.indexOf('<p class="market-reaction"'),theatre=reactionAt<0?stage:stage.slice(0,reactionAt),reaction=reactionAt<0?'':stage.slice(reactionAt);
  body+=theatre+'<p class="market-stall-line">'+esc(stall.line)+'</p><div class="market-offer-selector" aria-label="Choose an object">'+m.stalls[m.step].map(item=>'<button class="market-offer-pick '+(item.id===selected.id?'selected':'')+'" data-life="market-select" data-id="'+item.id+'" aria-pressed="'+(item.id===selected.id)+'"><span class="market-choice-price">'+item.cost+' buttons · '+item.charm+' charm'+(item.cost>=5?' · Rare':'')+'</span><b>'+esc(item.name)+'</b><span class="market-tags">'+tags(item)+'</span></button>').join('')+'</div><div class="market-selection-story"><p class="market-object-line">'+esc(selected.line)+'</p><span>'+(disabled?full?(m.traded?'Your bag is full and the trade-in is used.':'Open your bag to choose a trade-in.'):m.version===2&&!m.secret?'You can sell a secret for more buttons, giving up this stall.':'Choose a cheaper object or pass.':'This basket: '+projected.total+' points · '+projected.fulfilled.filter(Boolean).length+' requests')+'</span></div>'+reaction;
 }
 const primary=full&&!m.traded?button('Choose a trade-in','market-panel','data-panel="bag"'):button(full?'Bag full':short?'Need '+(selected.cost-available)+' more buttons':(traded?'Trade & buy':'Buy')+' · '+selected.cost+' buttons','market-buy','data-id="'+selected.id+'" '+(disabled?'disabled':''));
 const actions='<div class="market-dock-selection"><span>'+(traded?'Trading '+esc(traded.name)+' for ':'Selected: ')+'<b>'+esc(selected.name)+'</b></span></div>'+primary+'<div class="market-next-actions">'+button(m.step===5?'Finish without buying':'Pass this stall','market-pass')+(m.version===2&&!m.secret?button('Sell secret: +3 buttons','market-secret'):'')+'</div>'+(m.version===2&&!m.secret?'<p class="market-secret-rule">Secret: skips this stall, −3 final points. Once.</p>':'');

 return marketWorkspace(body,actions,panel?'context':'playing');
}
