import { masteryUnlockText, mastery, masteryTicket, completeMastery, masteryText } from '../mastery-state.js';
import { MARKET_TAGS, MARKET_STALLS, RELICS } from '../content/life.js';
import { ERRAND_ITEM_LINES, ERRAND_VENDOR_LINES, ERRAND_STALL_NAMES } from '../content/market-errands.js';
import { deliveryOptions, bestErrandScore, errandProgress, errandPurchasePreview, maxRemainingErrands, deliveryBonus } from '../engine/market-errands.js';
import { curioSVG } from '../art/curios.js';

const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,extra='')=>'<button class="btn" data-life="'+action+'" '+extra+'>'+label+'</button>';
const tags=item=>item.tags.map(t=>'<span class="market-tag tag-'+t+'">'+MARKET_TAGS[t]+'</span>').join('');
const owner=(m,i)=>m.patrons[i]||'The household';
const itemLine=item=>ERRAND_ITEM_LINES[item.id]||item.line;
const stallName=(m,step)=>m.version>=4?ERRAND_STALL_NAMES[step]:MARKET_STALLS[step].name;
const special=(item,m)=>deliveryBonus(item,m.version)?' · +'+deliveryBonus(item,m.version)+' points if delivered':'';
function shoppingHint(m,r){
  const progress=errandProgress(m,r);
  if(progress.delivered)return 'Delivered';
  if(progress.pairs.length)return 'A pair is ready to send home.';
  if(!progress.partners.length)return 'Find two objects: '+r.tags.map(t=>MARKET_TAGS[t]).join(' + ')+'.';
  return progress.partners.map(({item,tag})=>'Pair '+item.name+' with a '+MARKET_TAGS[tag].toLowerCase()+' object.').join(' ');
}
function purchaseHint(m,item,trade){
  const preview=errandPurchasePreview(m,item,trade||null);
  if(!preview)return '';
  if(preview.ready.length)return '<div class="market-offer-fit"><b>This purchase makes a delivery ready</b>'+preview.ready.map(({request,pair})=>'<p>'+esc(request.name)+': '+esc(pair.map(i=>i.name).join(' + '))+'.</p>').join('')+'<small>'+(preview.ready.length>1?'These are alternatives: choose one delivery for this object. ':'')+'Send the pair home after buying to receive 4 buttons and free two spaces.</small></div>';
  if(preview.futurePairs.length){
    const next=preview.futurePairs.slice().sort((a,b)=>a.step-b.step||a.partner.cost-b.partner.cost)[0];
    return '<div class="market-offer-fit"><b>A possible partner is still ahead</b><p>'+esc(next.request.name)+': pair this with '+esc(next.partner.name)+' at stall '+(next.step+1)+' ('+next.partner.cost+' buttons).</p><small>Keep enough buttons and bag space. See the route for other choices.</small></div>';
  }
  return '<div class="market-offer-fit"><b>'+(preview.helps.length?'No matching partner remains':'No unfinished errand needs this object')+'</b><p>This purchase cannot join a matching pair in your bag or at a later stall. Leftover purchases earn no points.</p></div>';
}
function errands(m,finished=false){
  const ordered=m.requests.map((r,i)=>({r,i,order:m.delivered.includes(r.id)?2:deliveryOptions(m,r).length?0:1}));
  if(!finished)ordered.sort((a,b)=>a.order-b.order||a.i-b.i);
  return '<div class="market-requests">'+ordered.map(({r,i})=>{
    const done=m.delivered.includes(r.id),pairs=deliveryOptions(m,r),receipt=m.receipts.find(x=>x.request===r.id);
    return '<article class="market-request '+(done?'fulfilled':'')+'"><span class="eyebrow">'+esc(owner(m,i))+' · '+(done?'Delivered':'+4 buttons on delivery')+'</span><b>'+esc(r.name)+'</b><div class="market-tags">'+tags(r)+'</div><p>'+esc(r.brief)+'</p>'+
      (done?'<div class="market-delivery-stage" aria-label="Shopping received by '+esc(owner(m,i))+'"><div class="market-recipient" data-patron="'+esc(m.patronIds?.[i]||'')+'"></div><div class="market-delivery-objects">'+receipt.items.map(item=>curioSVG(item.shape,{literal:true})).join('')+'</div></div><p>'+esc(receipt.items.map(x=>x.name).join(' + '))+'</p><p class="market-delivery-comedy">'+esc(r.delivered)+'</p>':finished?'<p>Not delivered. The household will manage; it has already started discussing your route.</p>':pairs.length?pairs.map(pair=>button('Deliver '+esc(pair.map(x=>x.name).join(' + '))+' · +4 buttons','market-deliver','aria-label="Deliver '+esc(pair.map(x=>x.name).join(' + '))+' for '+esc(owner(m,i))+': '+esc(r.name)+'; receive 4 buttons" data-request="'+r.id+'" data-items="'+pair.map(x=>x.id).join(',')+'"')).join(''):'<small>'+esc(shoppingHint(m,r))+'</small>')+'</article>';
  }).join('')+'</div>';
}
function basket(m,trade){
  return '<h4>Your bag · '+m.bag.length+'/3 spaces</h4><div class="market-bag-items">'+m.bag.map(item=>'<div class="market-packed">'+curioSVG(item.shape,{literal:true})+'<div><b>'+esc(item.name)+'</b><span>'+item.tags.map(t=>MARKET_TAGS[t]).join(' / ')+'</span></div></div>').join('')+'</div>'+(!m.bag.length?'<p>The bag is empty. This is also its preferred working condition.</p>':'')+
    (!m.traded&&m.bag.length&&m.step<m.stalls.length?'<label class="market-trade-label">One return per trip, with a new purchase<select id="marketTrade"><option value="">Keep everything</option>'+m.bag.map(item=>'<option value="'+item.id+'" '+(trade===item.id?'selected':'')+'>Return '+esc(item.name)+' for 1 button</option>').join('')+'</select></label><p class="hint">A return only happens when you buy. Deliveries free two spaces and pay four buttons, so check your errands first. Returning an object leaves fewer objects for deliveries.</p>':m.traded?'<p>Your one return has been used.</p>':'');
}
export function marketErrandMarkup(state,m,trade,selection,panel,{workspace,stage,select}){
  if(!m)return workspace('<p>'+esc(masteryText(state,'market'))+'</p>'+'<div class="market-welcome"><span class="eyebrow">Household shopping · No timer</span><h3>Start with one errand. Learn the household’s prices.</h3>'+stage(0)+'<p>Your first lesson has one errand across two stalls. Finish it to learn the six-stall, three-errand route, then the eight-stall merchant challenge. Every route starts with ten buttons. You have a three-space bag and a porter who knows the way home.</p></div><ol class="market-rules"><li><b>Check the list.</b> Every errand needs two separate objects. Their labels show what they are good for.</li><li><b>Choose your route.</b> Each stall allows one purchase. Two delivered objects finish each errand. Later lessons add alternative stock and premium prices. Check future stock when you need it.</li><li><b>Send a pair home.</b> Choose an errand and deliver two matching objects. They leave your bag. The household pays you four buttons to keep shopping.</li></ol><p>Delivered objects cannot fill another errand. One return is allowed: get one button back while buying a replacement.</p><p class="hint">Aim to finish every errand on your current list. Score: 10 per delivery + special-delivery points + buttons brought home. Objects above 3 buttons earn 2 extra points for each extra button spent, when delivered. Leftover purchases earn no points. These buttons belong to this outing; your residents’ needs and trust are safe.</p>',button('Continue mastery shopping','market-start')+button('One-errand practice','market-practice'),'planning');
  const delivered=m.delivered.length,ready=m.requests.filter(r=>deliveryOptions(m,r).length).length;
  if(m.complete){
    const tier=delivered===m.requests.length?2:delivered===2?1:0,relic=RELICS.find(r=>r.id==='market:'+tier),best=bestErrandScore(m.seed,{version:m.version,tier:m.tier});
    return workspace((m.masteryUnlocked?'<p class="mastery-unlock" role="status">'+esc(masteryUnlockText('market',m.masteryUnlocked))+'</p>':'')+'<div class="market-welcome market-results">'+curioSVG(relic.shape,{literal:true})+'<span class="eyebrow">Home with the shopping</span><h3 tabindex="-1">'+delivered+' of '+m.requests.length+' errands delivered.</h3><p>'+(delivered===m.requests.length?'Everyone got what they asked for. They are meeting to decide what they meant.':delivered?'Some of the list is done. The unfinished part has elected a spokesperson.':'You brought the list back. It was not one of the errands.')+'</p><p>'+esc(relic.name)+'</p></div><div class="market-tally"><div><b>'+m.score.requestPoints+'</b><span>Errand points</span></div><div><b>'+m.buttons+'</b><span>Buttons returned</span></div>'+(m.score.premiumPoints?'<div><b>'+m.score.premiumPoints+'</b><span>Special deliveries</span></div>':'')+'<div><b>'+m.score.total+'</b><span>Total points</span></div></div><p class="market-record">Best possible on this route: '+best+' points. Your best with these rules: '+(state.life[m.version>=4?'marketErrandBestV4':'marketErrandBest']||0)+'.</p>'+errands(m,true)+(m.bag.length?'<p><b>Still in the bag:</b> '+esc(m.bag.map(i=>i.name).join(', '))+'. These were not delivered and earn no points.</p>':'')+'<p class="hint">'+(m.version===3?'This saved trip keeps its original six-stall rules. A new market uses eight stalls and special-delivery points. ':'')+'Retry uses the same stock, prices, and list. A new market gives you a fresh list. Previously earned keepsakes give no repeat discoveries.</p>',button('Retry this shopping list','market-retry')+button('New market','market-start')+button('Display keepsake','display'),'result');
  }
  const returned=!m.traded?m.bag.find(i=>i.id===trade):null,available=m.buttons+(returned?1:0),bag=returned?m.bag.filter(i=>i.id!==returned.id):m.bag;
  const selected=select(m,selection,trade),atEnd=m.step===m.stalls.length,full=bag.length>=3,short=selected&&selected.cost>available,possible=maxRemainingErrands(m),afterPass=maxRemainingErrands(m,true);
  const header='<div class="market-heading"><div><span class="eyebrow">'+(atEnd?'Before you go home':'Stall '+(m.step+1)+' / '+m.stalls.length)+'</span><h3 tabindex="-1">'+(atEnd?'The porter is waiting.':esc(stallName(m,m.step)))+'</h3></div><div class="market-purse"><b>'+m.buttons+'</b><span>buttons</span></div></div>';
  const nav='<div class="market-context-nav" aria-label="Market information">'+button('Errands '+delivered+'/'+m.requests.length+(ready?' · '+ready+(ready===1?' ready':' options'):''),'market-panel','data-panel="requests" aria-pressed="'+(panel==='requests')+'"')+button('Bag '+m.bag.length+'/3','market-panel','data-panel="bag" aria-pressed="'+(panel==='bag')+'"')+(!atEnd?button('See the route','market-panel','data-panel="route" aria-pressed="'+(panel==='route')+'"'):'')+'</div>';
  let body='<p>'+esc(masteryText(state,'market'))+'</p>'+header+nav+(possible<m.requests.length?'<p class="market-route-status">At most '+possible+' of '+m.requests.length+' errands fit within your remaining purchases. Matching stock and your budget may reduce that number. Make the most of those deliveries, then bring your spare buttons home.</p>':'')+(m.lastReceipt?'<p class="market-reaction" role="status">'+esc(m.lastReceipt)+'</p>':'');
  if(panel==='requests'||atEnd&&!panel){
    body+='<div class="market-context-panel" tabindex="-1"><h4>Send your shopping home</h4><p>Each delivery uses the two named objects, frees two bag spaces, and pays four buttons. Choose carefully if a pair could fill more than one errand.</p>'+errands(m)+'</div>';
  }else if(panel==='bag')body+='<div class="market-context-panel" tabindex="-1">'+basket(m,trade)+'</div>';
  else if(panel==='route')body+='<div class="market-context-panel market-map" tabindex="-1"><h4>The remaining route</h4><p>One purchase per stall. Deliveries do not use a stall.</p>'+m.stalls.slice(m.step).map((stock,i)=>'<article><b>'+esc(stallName(m,m.step+i))+(i===0?' · here':'')+'</b><div>'+stock.map(item=>'<p><strong>'+esc(item.name)+'</strong><span>'+item.cost+' buttons'+special(item,m)+' · '+item.tags.map(t=>MARKET_TAGS[t]).join(' / ')+'</span></p>').join('')+'</div></article>').join('')+'</div>';
  else{
    body+='<div class="market-errand-list">'+m.requests.map((r,i)=>'<p><b>'+esc(owner(m,i))+': '+esc(r.name)+'</b><span>'+(m.delivered.includes(r.id)?'✓ Delivered':deliveryOptions(m,r).length?'Pair ready to deliver':r.tags.map(t=>MARKET_TAGS[t]).join(' + '))+'</span></p>').join('')+'</div>'+stage(m.step,m.stalls[m.step])+'<p class="market-stall-line">'+esc(ERRAND_VENDOR_LINES[m.step].opening)+'</p><div class="market-offer-selector" aria-label="Choose an object">'+m.stalls[m.step].map(item=>'<button class="market-offer-pick '+(item.id===selected.id?'selected':'')+'" data-life="market-select" data-id="'+item.id+'" aria-pressed="'+(item.id===selected.id)+'"><span class="market-choice-price">'+item.cost+' buttons'+special(item,m)+'</span><b>'+esc(item.name)+'</b><span class="market-tags">'+tags(item)+'</span></button>').join('')+'</div><p class="market-object-line">'+esc(itemLine(selected))+'</p><details class="market-hint"><summary>Need a pairing hint?</summary>'+purchaseHint(m,selected,returned?.id)+'</details>';
  }
  const blocked=full&&!ready&&m.traded;
  const primary=atEnd?'':ready&&(full||short)?button(full?'Deliver to free two spaces':'Deliver for 4 buttons','market-panel','data-panel="requests"'):
    !m.traded&&(full||short&&!returned&&m.bag.length&&selected.cost<=m.buttons+1)?button('Choose an object to return','market-panel','data-panel="bag"'):
    blocked?button(m.step===m.stalls.length-1?'Pass final stall':'Pass this stall','market-pass'):
    button(full?'Bag full':short?'Need '+(selected.cost-available)+' more button'+(selected.cost-available===1?'':'s'):(returned?'Return & buy':'Buy')+' · '+selected.cost+' buttons','market-buy','data-id="'+selected?.id+'" '+(full||short?'disabled':''));
  let actions;
  if(atEnd)actions='<p>You can still deliver from your bag before leaving.'+(ready?' A pair is ready: send it home for 10 points and 4 buttons.':'')+'</p>'+(ready&&panel!=='requests'&&panel?button('Send the ready pair','market-panel','data-panel="requests"'):'')+button(ready?'Leave with undelivered shopping':'Return home · '+delivered+'/'+m.requests.length+' delivered','market-leave');
  else if(panel)actions=button('Back to stall','market-panel','data-panel=""');
  else actions='<p class="market-dock-selection">'+(returned?'Return '+esc(returned.name)+' for 1 button. ':'')+'Selected: '+esc(selected.name)+'</p>'+primary+'<div class="market-next-actions">'+button('Check errands'+(ready?' · pair ready':''),'market-panel','data-panel="requests"')+(blocked?'':button(m.step===m.stalls.length-1?'Pass final stall':'Pass this stall','market-pass'))+'</div>'+(full?'<p>'+(blocked?'No pair matches and your return is used. Pass the remaining stalls, then bring your spare buttons home.':ready?'Deliver a matching pair to free two spaces.':'Your bag has no matching pair. Choose one object to return with your purchase.')+'</p>':'<p>'+(short?'Choose a cheaper object, deliver a pair, or pass.':'After buying: '+(available-selected.cost)+' button'+(available-selected.cost===1?'':'s')+' left.')+'</p>')+(afterPass<possible?'<p class="market-pass-warning">After passing, there are enough purchase opportunities for at most '+afterPass+' of '+m.requests.length+' errands. Labels and budget still matter.</p>':'');
  return workspace(body,actions,atEnd||panel?'context':'playing');
}
