import { MARKET_TAGS, MARKET_STALLS, RELICS } from '../content/life.js';
import { bestMarketScore, scoreMarket } from '../engine/life.js';
import { curioSVG } from '../art/curios.js';

const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,extra='')=>'<button class="btn" data-life="'+action+'" '+extra+'>'+label+'</button>';
const tags=item=>item.tags.map(t=>'<span class="market-tag tag-'+t+'">'+MARKET_TAGS[t]+'</span>').join('');

function vendorFace(step){
 const hat=step===1?'<path d="M22 30 48 4 74 30Z" fill="#372b44"/><path d="m42 4 5 24" stroke="#e3be89" stroke-width="3"/>':step===3?'<path d="M64 8a25 25 0 1 0 13 43A28 28 0 0 1 64 8" fill="#e7cc89"/>':'<path d="M24 32V18q24-14 48 0v14Z" fill="#322332"/><path d="M18 32h60" stroke="#d6b47a" stroke-width="5"/>';
 return '<svg viewBox="0 0 96 100" role="presentation"><path d="M21 91V51q0-29 27-29t27 29v40l-13-7-14 8-14-8Z" fill="'+(['#ac90aa','#b9a5c9','#9dad78','#6c749f','#c3c7cb','#a89483'][step])+'"/><g class="market-vendor-head">'+hat+'<ellipse cx="36" cy="51" rx="4" ry="5" fill="#211d2a"/><ellipse cx="60" cy="51" rx="4" ry="5" fill="#211d2a"/><path d="M35 68q13 9 26-1" fill="none" stroke="#211d2a" stroke-width="3"/><path d="M45 70v7m9-7v5" stroke="#eee1be" stroke-width="4"/></g><path class="market-vendor-hand" d="m70 75 16-12" stroke="#d8bd9a" stroke-width="9" stroke-linecap="round"/></svg>';
}

function marketStage(step,stock=[],action){
 const actor=Math.min(5,step),reaction=action?MARKET_STALLS[action.step]?.[action.kind==='buy'?'bought':action.kind==='secret'?'secret':'passed']:'';
 return '<div class="market-theatre" aria-hidden="true"><div class="market-awning"></div><span class="market-lantern lantern-a"></span><span class="market-lantern lantern-b"></span><div class="market-vendor">'+vendorFace(actor)+'</div><div class="market-counter-stock">'+stock.map(i=>curioSVG(i.shape,{literal:true})).join('')+'</div><div class="market-counter"></div><div class="market-stage-bag"><span></span></div>'+(action?.item?'<div class="market-purchase-flight">'+curioSVG(action.item.shape,{literal:true})+'</div>':'')+(action?.kind==='secret'?'<div class="market-secret-flight">'+curioSVG('receipt')+'</div>':'')+'</div>'+(reaction?'<p class="market-reaction" role="status">'+esc(reaction)+'</p>':'');
}

function requestCards(m){return '<div class="market-requests">'+m.requests.map((r,i)=>'<article class="market-request '+(m.score.fulfilled[i]?'fulfilled':'')+'"><span class="eyebrow">'+(m.score.fulfilled[i]?'Fulfilled · +4':'Shopping request · 4 points')+'</span><b>'+esc(r.name)+'</b><div class="market-tags">'+tags(r)+'</div><small>'+esc(r.line)+'</small></article>').join('')+'</div>';}

export function marketMarkup(state,m,trade='',lastAction=null){
 const l=state.life;
 if(!m)return '<div class="market-welcome"><span class="eyebrow">The Unlicensed Night Market</span><h3>Come for the bargains. Leave before the digging starts.</h3>'+marketStage(0)+'<p>Six stalls. Ten buttons. A bag for three objects. The household needs three pairs of things, and the vendors need you to stop asking where things came from.</p></div><ol class="market-rules"><li><b>Plan the basket.</b> Every stall and price is visible. Buy one object from each stall, or pass. Each request needs two separate objects; one object can serve several requests.</li><li><b>Watch for rare stock.</b> Two stalls carry expensive keepsakes worth extra charm. Their prices and tags are visible in the route book.</li><li><b>Change your mind once.</b> Trade one packed object for one button while buying its replacement.</li><li><b>Pawn your reputation, once.</b> Skip a stall’s stock to sell the vendor a secret for three buttons. The scandal costs three final points. Useful when the better basket costs more than ten.</li></ol><div class="market-score-rule"><b>Your score</b><span>Object charm + 4 per request + spare buttons − 3 if you sold a secret</span></div><div class="life-links">'+button('Enter the night market','market-start')+'</div><p class="hint">No timer. No real money. Your basket and choices are saved when you leave.</p>';
 if(m.complete){
  const best=bestMarketScore(m.seed,{version:m.version}),tier=m.score.total===best?2:m.score.total>=17?1:0,relic=RELICS.find(r=>r.id==='market:'+tier);
  return '<div class="market-welcome market-results">'+curioSVG(relic.shape,{literal:true})+'<span class="eyebrow">Nobody has followed you home. Yet.</span><h3 tabindex="-1">'+m.score.total+' points. '+(m.score.total===best?'A perfect market.':m.score.total>=23?'You robbed them politely.':m.score.total>=17?'A respectable collection of evidence.':'At least the bag is innocent.')+'</h3><p>'+esc(relic.name)+'<br>'+esc(relic.line)+'</p></div>'+marketStage(5,[],lastAction)+'<div class="market-tally '+(m.secret?'has-scandal':'')+'"><div><b>'+m.score.charm+'</b><span>Object charm</span></div><div><b>'+m.score.requestPoints+'</b><span>Requests</span></div><div><b>'+m.buttons+'</b><span>Spare buttons</span></div>'+(m.secret?'<div><b>−3</b><span>Public scandal</span></div>':'')+'</div>'+requestCards(m)+'<div class="market-record"><b>'+best+' points were possible on this route.</b><span>Your best: '+l.marketBest+' · Markets completed: '+l.marketRuns+'</span></div><div class="life-links">'+button('Try this market again','market-retry')+button('Visit a new market','market-start')+button('Display your keepsake','display')+'</div><details class="market-map"><summary>Your basket and replay rules</summary>'+m.bag.map(item=>'<p><b>'+esc(item.name)+'</b> · '+item.charm+' charm<br>'+esc(item.line)+'</p>').join('')+(!m.bag.length?'<p>The bag contains nothing. The vendor has written “minimalism” on the receipt and charged for the ink.</p>':'')+'<p>Retry keeps these stalls, requests and '+(m.version===2?'secret-selling rules':'original shopping rules')+'. Keepsakes unlock at 17 points and a perfect route. Existing keepsakes do not give repeat discoveries.</p></details>';
 }
 const traded=!m.traded?m.bag.find(item=>item.id===trade):null,available=m.buttons+(traded?1:0),bag=traded?m.bag.filter(item=>item!==traded):m.bag,stall=MARKET_STALLS[m.step];
 const compactRequests='<details class="market-request-book"><summary><b>'+m.score.fulfilled.filter(Boolean).length+' / 3 requests</b><span>'+m.requests.map((r,i)=>'<span class="market-request-pair '+(m.score.fulfilled[i]?'fulfilled':'')+'">'+(m.score.fulfilled[i]?'✓ ':'')+r.tags.map(t=>MARKET_TAGS[t]).join(' + ')+'</span>').join('')+'</span></summary>'+requestCards(m)+'</details>';
 const tradeSelect=!m.traded&&m.bag.length?'<label class="market-trade-label">Optional trade-in with this purchase<select id="marketTrade"><option value="">Keep all '+m.bag.length+' packed object'+(m.bag.length===1?'':'s')+'</option>'+m.bag.map(item=>'<option value="'+item.id+'" '+(trade===item.id?'selected':'')+'>Trade '+esc(item.name)+' for 1 button</option>').join('')+'</select></label>':'';
 return '<div class="market-heading"><div><span class="eyebrow">Stall '+(m.step+1)+' of 6 · No timer</span><h3 tabindex="-1">'+esc(stall.name)+'</h3><p>'+esc(stall.line)+'</p></div><div class="market-purse"><b>'+m.buttons+'</b><span>buttons left</span></div></div>'+marketStage(m.step,m.stalls[m.step],lastAction)+'<div class="market-status-line"><b>Bag '+m.bag.length+' / 3</b><span>'+m.score.total+' current points'+(m.secret?' · scandal included':'')+'</span></div>'+compactRequests+tradeSelect+'<div class="market-offers">'+m.stalls[m.step].map(item=>{
  const full=bag.length>=3,short=item.cost>available,disabled=full||short,projected=scoreMarket([...bag,item],available-item.cost,m.requests,m.secret);
  return '<article class="market-offer">'+(item.cost>=5?'<span class="market-rarity">Rare keepsake</span>':'')+'<div class="market-price">'+item.cost+' buttons <span>· '+item.charm+' charm</span></div><h4>'+esc(item.name)+'</h4><div class="market-tags">'+tags(item)+'</div>'+button(full?'Bag full':short?'Need '+(item.cost-available)+' more':traded?'Trade & buy':'Buy this object','market-buy','data-id="'+item.id+'" '+(disabled?'disabled':''))+'<small>'+(disabled?full?(m.traded?'Trade used. Keep your bag and pass.':'Choose a trade-in above to free a space.'):(m.version===2&&!m.secret?'Pass, or sell a secret for more buttons.':'Choose a cheaper object or pass this stall.'):'Basket: '+projected.total+' points · '+projected.fulfilled.filter(Boolean).length+' requests')+'</small><p class="market-object-line">'+esc(item.line)+'</p></article>';
 }).join('')+'</div><div class="market-next-actions">'+button(m.step===5?'Finish without buying':'Pass this stall','market-pass')+(m.version===2&&!m.secret?button('Sell a secret · +3 buttons','market-secret'):'')+'</div>'+(m.version===2&&!m.secret?'<p class="market-secret-rule">Selling a secret uses this stall instead of buying. Once per trip; −3 final points. No effect on your residents.</p>':'')+'<div class="market-progress" aria-label="Market route, stall '+(m.step+1)+' of 6">'+MARKET_STALLS.map((_,i)=>'<span class="'+(i<m.step?'visited':i===m.step?'current':'')+'" '+(i===m.step?'aria-current="step"':'')+'>'+(i+1)+'</span>').join('')+'</div><details class="market-map"><summary>Plan ahead: '+(5-m.step)+' remaining stalls and prices</summary><p class="hint">One purchase per stall. All future stock is shown.</p>'+m.stalls.slice(m.step+1).map((stock,i)=>'<article><b>'+esc(MARKET_STALLS[m.step+i+1].name)+'</b><div>'+stock.map(item=>'<p><strong>'+esc(item.name)+'</strong><span>'+item.cost+' buttons · '+item.charm+' charm · '+item.tags.map(t=>MARKET_TAGS[t]).join(' / ')+'</span></p>').join('')+'</div></article>').join('')+(m.step===5?'<p>Last stall. Your next choice finishes this trip.</p>':'')+'</details><details class="market-map"><summary>Your packed objects · '+m.bag.length+' / 3</summary><div class="market-bag-items">'+m.bag.map(item=>'<div class="market-packed">'+curioSVG(item.shape,{literal:true})+'<div><b>'+esc(item.name)+'</b><span>'+item.charm+' charm · '+item.tags.map(t=>MARKET_TAGS[t]).join(' / ')+'</span></div></div>').join('')+'</div><p class="hint">'+(m.traded?'Trade-in used.':'One trade-in is available with a purchase. Passing or selling a secret keeps every packed object.')+'</p></details>';
}
