// The observations are reliable facts, not testimony to guess about. Each new
// hearing rotates which facts matter; names and cosmetic art never give a clue.
const axis = (name, values) => ({ name, values });
export const COURT_LEVELS = [
 { name:'Cozy', summary:'3 suspects · 2 direct clues', instructions:'Find the only suspect who fits both exhibits. Read at your own pace; there is no timer.' },
 { name:'Curious', summary:'4 suspects · exclusions and inclusive either/or', instructions:'Some evidence excludes a fact; an inclusive either/or allows one or both. The answer must fit every exhibit.' },
 { name:'Tangled', summary:'4 suspects · linked observations and conditionals', instructions:'Exactly one means one statement is true, never both. An “if” rule only rules somebody out when its first part is true and its second part is false.' }
];
export const COURT_CASES = [
 { title:'The biscuit with a bite missing', intro:'Half a biscuit has been eaten. The surviving half has retained counsel. The heirs are arguing over what is left.', object:'The biscuit',
   axes:[axis('Residue',['had jam on their sleeve','had flour on their sleeve','had cocoa on their sleeve']),axis('Last location',['stood beside the lamp','stood beside the bowl','stood beside the clock']),axis('Pocket contents',['carried a teaspoon','carried a paper bag','carried a brass key'])],
   end:'The defendant will inform the family. They are still in the packet.' },
 { title:'The unauthorised funeral', intro:'A crumb was buried alive during a heavily discounted funeral. It dug itself out and would like its deposit back.', object:'The crumb grave',
   axes:[axis('Tool',['carried a teaspoon','carried a fork','carried a thimble']),axis('Ribbon',['wore a black ribbon','wore a red ribbon','wore a striped ribbon']),axis('Shoes',['had muddy shoes','had floury shoes','had clean shoes'])],
   end:'The grave must be filled in. The victim has declined the loyalty card.' },
 { title:'The lamp that went missing', intro:'The communal lamp vanished. An unlicensed interrogation service opened shortly afterward, with excellent lighting.', object:'The little lamp',
   axes:[axis('Cloth',['carried a blue cloth','carried a green cloth','carried a dotted cloth']),axis('Last location',['stood at the doorway','stood at the window','stood behind the curtain']),axis('Residue',['had wax on their cuffs','had dust on their cuffs','had jam on their cuffs'])],
   end:'The lamp is returned. The business is closed. Confessions already invoiced remain disputed.' },
 { title:'The forged eviction', intro:'A forged eviction notice appeared beside a price list for the tenants’ beds. Someone has monetised the emergency.', object:'The forged eviction notice',
   axes:[axis('Ink',['used violet ink','used black ink','used green ink']),axis('Stamp',['held a round stamp','held a square stamp','held a star stamp']),axis('Paper',['carried lined paper','carried spotted paper','carried plain paper'])],
   end:'The eviction is cancelled. The defendant must live next to the person who snores.' },
 { title:'The last word held for ransom', intro:'A resident staged its death to escape a debt. Someone bottled its last word and sold the family subscriptions. The resident has returned to demand royalties.', object:'The last word',
   axes:[axis('Container',['held a glass jar','held a wooden box','held a paper envelope']),axis('Last location',['stood near the curtain','stood near the stair','stood near the clock']),axis('Sleeve',['had a wool sleeve','had a cotton sleeve','had a silk sleeve'])],
   end:'The word is returned. It was “actually”. The resident resumes being unbearable without a paywall.' },
 { title:'The pea’s suspicious coronation', intro:'A pea has seized the throne, banned elections, and ordered the jury steamed. Someone helped with the crown.', object:'The paper crown',
   axes:[axis('Paper',['held gold paper','held silver paper','held green paper']),axis('Tool',['carried scissors','carried glue','carried a hole punch']),axis('Accessory',['wore a tiny cape','wore a paper hat','wore a ribbon sash'])],
   end:'The monarchy is dissolved into soup. The cabinet has requested separate bowls.' },
 { title:'The emergency that was a raisin', intro:'A raisin was declared a plague victim. During the evacuation, someone offered cash for the supposedly contaminated beds.', object:'The alarm bell',
   axes:[axis('Gloves',['wore wool gloves','wore silk gloves','wore paper gloves']),axis('Tool',['held a pencil','held a spoon','held a paintbrush']),axis('Last location',['stood on the top shelf','stood on the middle shelf','stood on the bottom shelf'])],
   end:'All beds are returned. The raisin remains under observation until the coroner finishes lunch.' },
 { title:'The rent paid in moths', intro:'Six moths were passed off as rent. They had been told the envelope was affordable housing. Neither claim has survived inspection.', object:'The rent envelope',
   axes:[axis('Seal',['used a wax seal','used a glue seal','used a ribbon seal']),axis('Bag',['carried a velvet bag','carried a paper bag','carried a string bag']),axis('Residue',['had glitter on their fingers','had flour on their fingers','had soot on their fingers'])],
   end:'The moths are released. The landlord tries to charge them an exit fee and is added to the docket.' },
 { title:'The inheritance portrait', intro:'A family portrait has been altered to make its owner look dead. A request to open the will arrived before the paint dried.', object:'The altered portrait',
   axes:[axis('Drawing tool',['held a charcoal stick','held a pencil','held a paintbrush']),axis('Headwear',['wore a beret','wore a bonnet','wore a paper crown']),axis('Last location',['stood by the frame','stood by the easel','stood by the sink'])],
   end:'The portrait is restored. The defendant is removed from the will and added to the portrait.' },
 { title:'The teaspoon declared dead', intro:'A teaspoon was declared dead and its pension withdrawn. The spoon turned up alive, tarnished, and understandably difficult.', object:'The travelling teaspoon',
   axes:[axis('String',['carried red thread','carried blue thread','carried white thread']),axis('Footwear',['wore slippers','wore boots','wore socks']),axis('Pocket contents',['carried a magnet','carried a button','carried a pebble'])],
   end:'The pension is restored. The spoon names a fork as its sole beneficiary out of spite.' },
 { title:'The counterfeit moon', intro:'A biscuit taped to the window triggered an eclipse cult. Someone sold evacuation subscriptions before anyone checked the sky.', object:'The fraudulent moon',
   axes:[axis('Adhesive',['held sticky tape','held a glue stick','held sealing wax']),axis('Residue',['had crumbs on their collar','had glitter on their collar','had chalk on their collar']),axis('Last location',['stood on a stool','stood on a box','stood on the floor'])],
   end:'Subscriptions are cancelled. The prophet is ordered to eat the eclipse in front of the congregation.' },
 { title:'The tiny witness protection programme', intro:'Vulnerable crumbs paid for new identities. They received false moustaches and were all hidden in a tin labelled “witnesses”.', object:'The false moustaches',
   axes:[axis('Material',['carried black yarn','carried brown wool','carried grey felt']),axis('Tool',['held small scissors','held a needle','held tweezers']),axis('Container',['carried a matchbox','carried a mint tin','carried a paper cup'])],
   end:'The programme is closed. Its director is given a new identity: the defendant in next Tuesday’s hearing.' }
];
export const COURT_DEFENCES = [
 '“The victim owed me money. Now nobody owes me money. Explain how I benefited.”',
 '“I was grieving privately. If you saw me laughing, you should respect my process.”',
 '“I did threaten them, yes. I threaten everyone. Ask my references.”',
 '“The obituary was a draft. I like to be prepared.”',
 '“My solicitor says I should stop calling it a successful misunderstanding.”',
 '“I have a receipt proving I was buying something much worse.”',
 '“Nobody was using that grave at the time.”',
 '“I reported the smell three days early. Apparently that is suspicious now.”',
 '“We had an understanding. They would leave everything to me. I was helping with the timing.”',
 '“You keep saying ‘victim’. Before this happened, they were widely considered a nuisance.”',
 '“I did not kill it. I declared it no longer cost-effective.”',
 '“Can the jury be replaced? Several of them stand to inherit.”'
];

// These are reasons to conceal a fact, not proof of the charged offence. Every
// witness has something unpleasant to hide, including the innocent ones.
export const COURT_INVESTIGATIONS = [
 { scene:'The plate has been cordoned off with black thread. A relative keeps asking whether the evidence will be returned in time for tea.',
   pressure:['The residue was collected before anyone was allowed to comfort the remains.','The clock photographed everyone in the room. It invoices by the hour, including this one.','The wrapper kept an impression of every pocket that touched it. The dead are being more cooperative than the living.'],
   motives:[
    'I sold the family a closed-packet funeral. There was considerably less inside than the brochure implied.',
    'I had already bought the victim’s half of the bed. I was waiting for the market to become vacant.',
    'The biscuit asked me to witness its will. I was checking whether it had named a beneficiary or a serving size.',
    'I wrote the obituary last Tuesday. Nobody appreciates the amount of unpaid preparation that goes into grief.' ] },
 { scene:'The headstone says “At peace”. Something underneath has scratched out “At”. The undertaker calls this normal customer feedback.',
   pressure:['The grave floor preserved the tool marks. It also preserved the victim, against the wishes of the organiser.','A ribbon was trapped under the headstone. The stone weighs more than the alibi.','Everyone crossed the burial sheet. We have their tracks and an unpaid cleaning bill.'],
   motives:[
    'I sold the same plot to three families. None of the original occupants had complained until today.',
    'The crumb kept asking for air. I thought it was negotiating an upgrade.',
    'I was making a death mask. It kept opening its eyes and spoiling the impression.',
    'I wanted the deposit back. The policy says the customer must appear in person, which I was helping it do.' ] },
 { scene:'A chair faces a bare bulb. The appointment book has a column for arrival and a second column headed “eventually”.',
   pressure:['Fibres under the lamp base identify what each person carried. The cleaning service refused to go near the chair.','The wax trail shows where everyone stood. Nobody stood near the exit for long.','The recovered switch kept the cuff residue. It was the only thing in the room anyone could turn off.'],
   motives:[
    'I rented out the chair for apologies. Most customers needed help understanding how sorry they were.',
    'I was retrieving my confession. They had corrected the spelling and added two offences.',
    'I sold the business a dimmer switch. Compassion should be available at several price points.',
    'I booked a session for my neighbour. The gift receipt did not include a release time.' ] },
 { scene:'The beds have price tags. The eviction notice thanks the tenants for a lifetime of custom and asks them to make it a short one.',
   pressure:['Ink samples were taken before the landlord could classify them as wear and tear.','The seal left a measurable impression. Unlike the appeal process.','Every sheet was examined. The clause about being buried on the premises was not in the original lease.'],
   motives:[
    'I bought the beds in advance. The sales listing described the occupants as a temporary obstruction.',
    'I was copying the signature for a memorial plaque. They are alive, but I like to catch people before their handwriting declines.',
    'I charged the tenants an appeal fee. There is no appeals office. It was a difficult conversation to monetise.',
    'I planned to rent them their own beds back. Displacement is traumatic; I wanted continuity of service.' ] },
 { scene:'A jar whispers “actually” whenever the lid turns. Beside it, a subscription form offers bereavement in three affordable tiers.',
   pressure:['The containers were tested separately. One insists its contents are final even after being told they are wrong.','The bedside dust records everybody’s position. The grieving family kept a respectable distance from the invoice.','Fabric was lifted from the lid. The victim asked us to preserve its final word; then supplied fourteen more.'],
   motives:[
    'I offered the family a free trial of closure. I knew they would struggle to cancel before the funeral.',
    'I wanted the word erased. It was the last thing between me and winning an argument from six years ago.',
    'The fake death was my idea. The subscription was someone else’s. I resent being undercut at my own bereavement.',
    'I recorded a replacement last word. “Sorry” would have been a better investment, but the family said it sounded nothing like them.' ] },
 { scene:'The royal decree orders dissenters simmered until tender. The pea has signed it by rolling through the ink.',
   pressure:['The crown’s paper was matched to everyone’s supplies. The royal archivist has asked us to stop calling it stationery.','Tool marks show how the crown was assembled. The constitution was cut to fit afterward.','The throne pins caught the accessories. One still has a resignation letter attached to it.'],
   motives:[
    'I sold the pea a hereditary title. I did not mention that its heirs were in the freezer.',
    'I accepted a cabinet post because it included immunity. The paperwork said “from washing up”, in very small print.',
    'I wrote the royal anthem. It is mostly names of residents the pea wants removed.',
    'I was organising the rebellion. I needed a crown for whoever survived the planning meeting.' ] },
 { scene:'The evacuation map leads directly to a property-buying desk. The raisin is under a sheet much larger than its medical needs.',
   pressure:['The bell rope preserved every glove fibre. The emergency operator has billed us for the panic.','The striker kept the tool marks. Someone rang it again when property prices began to recover.','Dust beneath the alarm places everyone on a shelf. The fire exit was being valued at the time.'],
   motives:[
    'I sold the residents plague insurance. It covered the plague. It did not cover discovering there was no plague.',
    'I bought two beds during the evacuation. The sellers seemed motivated. One was still screaming.',
    'I made the diagnosis. The raisin had no pulse. Neither did my previous eleven patients, but most were buttons.',
    'I was arranging quarantine accommodation. The rooms became more expensive once people were locked inside.' ] },
 { scene:'Six moths queue beside an opened envelope. The landlord has deducted the cost of opening it from their deposits.',
   pressure:['The rent seal was sampled before the landlord could charge us for breaking it.','Fibres from the transport bag were compared. The moths were told the journey counted as a viewing.','The payment slip kept everybody’s fingerprints. It did not keep any money.'],
   motives:[
    'I took deposits from all six moths. They each wanted a window. I promised to put a stamp on it.',
    'I was evicting the moths from my coat. I called it a relocation package because that sounded less like shaking them over a bin.',
    'I guaranteed the rent. I thought “six occupants” meant somebody would eventually pay.',
    'I sold the landlord moth insurance last week. There is a waiting period. I was checking whether he had noticed.' ] },
 { scene:'The portrait now looks recently deceased. Its owner is posing beside it, demanding that the resemblance be corrected.',
   pressure:['The added marks were sampled. The artist claims the pallor was a technical improvement.','Fibres behind the canvas identify the headwear. The portrait’s black veil is a separate item of evidence.','The studio floor records where everyone stood. The solicitor stood nearest the will.'],
   motives:[
    'I ordered the frame in mourning colours. It would have looked insensitive to wait for a discount.',
    'The will leaves me nothing while they are alive. I was exploring the boundaries of interpretation.',
    'I had been commissioned to make them look younger. Removing all signs of life was the most convincing method.',
    'I wanted the portrait off the wall. It watches me eat and has better prospects in the will than I do.' ] },
 { scene:'A pension form is clipped to a tiny death certificate. The teaspoon is using its bowl to bang on the fraud-office window.',
   pressure:['Thread was recovered from the handle. The spoon describes the retirement journey as involuntary.','Footprints beside the drawer were measured. The undertaker arrived wearing a delivery uniform.','Tests show what each pocket carried. The pension officer has asked whether the spoon can prove it was ever alive.'],
   motives:[
    'I spent the funeral allowance on a replacement spoon. The deceased was proving expensive to keep declaring dead.',
    'I had promised to care for it in old age. I thought the death certificate settled both problems.',
    'I was helping it escape the drawer. It wanted to see the world before being inherited by someone with a dishwasher.',
    'I sold it a resurrection policy. Finding it alive before I had collected the premium was deeply inconvenient.' ] },
 { scene:'The congregation faces a biscuit on the window. Beneath it, a shoebox promises salvation for the first twelve payments.',
   pressure:['The adhesive was tested. It held through three sermons and a failed ascent.','The window recorded collar residue. The prophet says the laboratory has misunderstood the nature of revelation.','Support marks show how the false moon reached the glass. The ladder was sold separately from salvation.'],
   motives:[
    'I sold priority boarding. Nobody asked how a shoebox gets above the weather.',
    'I wrote the prophecy. It originally ended in rain, but rain does not convert well.',
    'I bought the congregation’s possessions. They insisted they would not need them after Tuesday.',
    'I was collecting refunds for the last apocalypse. This one had better branding and the same treasurer.' ] },
 { scene:'A tin labelled “witnesses” contains several crumbs wearing moustaches. A second label gives directions for anyone unable to find them.',
   pressure:['The disguise material was sampled. Several moustaches are more recognisable than their owners.','The offcuts preserve tool marks. The protection service says evidence collection was not in its threat model.','The containers were examined. The tin’s forwarding address points back to the crime scene.'],
   motives:[
    'I sold the witnesses new names. The cheap plan gives everyone the same one.',
    'I printed the hiding-place labels. They said clarity was essential. I am beginning to suspect a failure of management.',
    'I was buying their old identities. Mine has accumulated obligations I would prefer somebody else to experience.',
    'I offered lifelong protection. They are crumbs. I had expected a substantially shorter commitment.' ] }
];

// Each charge is a small, specific story. The factual exhibits remain separate
// from these interested parties and their very selective remorse.
export const COURT_TRANSCRIPTS = [
 { charge:'The deliberate reduction of a neighbour to leftovers.',
   opening:'The victim has been identified by dental records. Specifically, yours.',
   prosecution:'Half a biscuit is missing. The surviving half has already been offered a lower settlement.',
   plea:'It said “eat me” on the packet. I assumed that was legally binding.',
   conviction:'The court finds that hunger explains the offence. It does not explain the pre-written obituary.',
   acquittal:'Enthusiasm is not evidence, counsel. You have accused someone who merely looked pleased.',
   sentence:'The defendant will inform the family. They are still in the packet.',
   objection:'Objection. The prosecution keeps saying “remains” and making me hungry.',
   exhibits:['Residue recovered from the bite','Wax and dust transfer on the plate','Pocket impressions in the discarded wrapper'],
   reconstruction:'The laboratory reconstructed the bite and the transfer marks' },
 { charge:'Burial without a death, a permit, or the occupant’s consent.',
   opening:'The deceased has asked to stand rather than lie in evidence.',
   prosecution:'The defendant booked the burial before checking whether the crumb was dead. There was a discount for weekdays.',
   plea:'It was a very good plot. You cannot expect me to waste the deposit.',
   conviction:'The court rejects “eventually” as an answer to whether the victim was dead.',
   acquittal:'Your suspect attended the funeral. Attendance alone is not murder, whatever the catering suggests.',
   sentence:'The grave must be filled in. The victim has declined the loyalty card.',
   objection:'Objection. My client thought the scratching was settling soil.',
   exhibits:['Marks cut into the grave floor','Fibres trapped beneath the headstone','Soil tracked across the burial sheet'],
   reconstruction:'A reconstruction of the burial marks' },
 { charge:'The theft of communal light for a private interrogation business.',
   opening:'The defendant’s booking form asks whether you intend to confess. The only options are dates.',
   prosecution:'The lamp vanished at ten. By eleven, the defendant was charging residents to admit things.',
   plea:'Nobody had to confess. The chair was available indefinitely.',
   conviction:'Calling it a “listening service” does not improve the straps.',
   acquittal:'Looking sinister in the dark is not a crime. We would have to arrest the entire shelf.',
   sentence:'The lamp is returned. The business is closed. Confessions already invoiced remain disputed.',
   objection:'Objection. Those testimonials were given voluntarily, after a while.',
   exhibits:['Fibres caught under the lamp base','Wax trail at the scene','Residue transferred to the stolen switch'],
   reconstruction:'The recovered lamp and its transfer marks' },
 { charge:'Forgery with intent to make homelessness administratively convenient.',
   opening:'The eviction notice allows thirty days. The defendant crossed out “days”.',
   prosecution:'The forged letter orders everyone out. Beneath it is a price list for their vacant beds.',
   plea:'I prefer “accelerated estate planning”. Nobody has to die first.',
   conviction:'A signature obtained from a sleeping person is still forgery, even if you held the pen very gently.',
   acquittal:'This suspect dislikes the tenants. That establishes membership of the household, not guilt.',
   sentence:'The eviction is cancelled. The defendant must live next to the person who snores.',
   objection:'Objection. The prosecution is making property ownership sound unpleasant.',
   exhibits:['Ink analysis of the forged signature','Seal impression on the notice','Paper fibres recovered from the printing table'],
   reconstruction:'Tests of the forged notice and the tools that made it' },
 { charge:'The theft and attempted resale of someone else’s final words.',
   opening:'The alleged deceased is alive and charging the prosecution an appearance fee.',
   prosecution:'The resident was rehearsing its death to avoid a debt. Someone bottled the last word and billed the family for closure.',
   plea:'They did not have to stay subscribed. I explained that closure would stop working.',
   conviction:'The court rejects the claim that a staged death permits genuine extortion.',
   acquittal:'Cruelty is a motive, counsel. Several people in this room have it in abundance.',
   sentence:'The word is returned. It was “actually”. The resident resumes being unbearable without a paywall.',
   objection:'Objection. The relatives have already consumed part of the product.',
   exhibits:['Sound test of the recovered container','Positions recorded in the bedside dust','Fabric impression on the bedside dust'],
   reconstruction:'The bedside recording and the container examination' },
 { charge:'Conspiracy to install an edible dictator.',
   opening:'His Majesty has ordered the jury steamed. We will proceed promptly.',
   prosecution:'Within minutes of coronation, the pea abolished elections and declared every spoon a political prisoner.',
   plea:'It promised me a place in the cabinet. I did not realise it meant the one beside the stock cubes.',
   conviction:'“Only following recipes” is not a defence to treason.',
   acquittal:'Wearing a stupid accessory does not establish guilt. The judge would have to recuse himself.',
   sentence:'The monarchy is dissolved into soup. The cabinet has requested separate bowls.',
   objection:'Objection. The prosecution is encouraging a serving suggestion.',
   exhibits:['Paper analysis of the royal crown','Tool marks along the crown’s edges','Fabric caught in the throne pins'],
   reconstruction:'A reconstruction of the crown-making and throne assembly' },
 { charge:'Staging a public emergency to purchase the victims’ property cheaply.',
   opening:'The alleged corpse is a raisin. The coroner has declined to revise the invoice.',
   prosecution:'Someone rang the alarm, shouted “plague”, and offered cash for the evacuated beds.',
   plea:'I was providing liquidity during a crisis I understood unusually well.',
   conviction:'The court finds the defendant guilty of panic-selling other people’s belongings.',
   acquittal:'The suspect panicked. That makes them a customer, not the architect of this unpleasant little business.',
   sentence:'All beds are returned. The raisin remains under observation until the coroner finishes lunch.',
   objection:'Objection. It looked considerably more dead before the lighting was improved.',
   exhibits:['Fibres recovered from the bell rope','Impact marks on the alarm striker','Dust transfer beneath the bell mounting'],
   reconstruction:'Tests of the alarm mechanism and evacuation footage' },
 { charge:'Rent fraud and the involuntary subletting of six moths.',
   opening:'The rent envelope is moving. The landlord has called this an encouraging market signal.',
   prosecution:'Six moths were delivered as payment. Each had been promised the envelope was a one-bedroom flat.',
   plea:'I disclosed that the property could be posted elsewhere. Nobody reads the whole agreement.',
   conviction:'The court rejects “air conditioning included” as a description of a hole in an envelope.',
   acquittal:'Your suspect is a tenant. The court recognises the expression of permanent dread.',
   sentence:'The moths are released. The landlord tries to charge them an exit fee and is added to the docket.',
   objection:'Objection. Nobody asked whether the moths had references.',
   exhibits:['Seal residue on the rent envelope','Fibres recovered from the moth transport','Finger marks beneath the false payment slip'],
   reconstruction:'The envelope examination and rental-office reconstruction' },
 { charge:'Premeditated disfigurement of a portrait to accelerate an inheritance.',
   opening:'The portrait now appears gravely ill. The person in it remains irritatingly healthy.',
   prosecution:'Someone added funeral shading to the family portrait and began measuring the curtains.',
   plea:'I was helping everyone visualise a difficult transition.',
   conviction:'The court finds that an artistic interpretation of death does not open probate.',
   acquittal:'Disliking the portrait is not evidence. We have all seen it.',
   sentence:'The portrait is restored. The defendant is removed from the will and added to the portrait.',
   objection:'Objection. The subject already looked like that in certain light.',
   exhibits:['Drawing residue inside the added marks','Headwear fibres caught behind the canvas','Footprints in the disturbed studio dust'],
   reconstruction:'The studio reconstruction and examination of the altered canvas' },
 { charge:'Faking a teaspoon’s death to collect its pension.',
   opening:'The missing teaspoon has been found. It would like to know why its pension is empty.',
   prosecution:'A death notice was filed at nine. At ten, the teaspoon was seen being dragged toward the door.',
   plea:'It had retired from stirring. I thought the rest was a technicality.',
   conviction:'The court observes that the defendant spent the funeral allowance before buying a coffin.',
   acquittal:'The suspect had access to the drawer. So does everyone with a modest amount of ambition.',
   sentence:'The pension is restored. The spoon names a fork as its sole beneficiary out of spite.',
   objection:'Objection. My client paid for a funeral. It is unreasonable for the guest of honour to demand a refund.',
   exhibits:['Thread recovered from the teaspoon handle','Footprints beside the drawer','Magnetic and abrasion tests on the spoon bowl'],
   reconstruction:'The drawer reconstruction and pension-office evidence' },
 { charge:'Operating an apocalypse subscription using a biscuit taped to a window.',
   opening:'The end of the world has been postponed until the next billing cycle.',
   prosecution:'The moon was replaced with a biscuit. Residents were sold priority evacuation places in a shoebox.',
   plea:'Nobody can prove the shoebox would not have worked.',
   conviction:'The court finds that the defendant confused salvation with recurring revenue.',
   acquittal:'Your suspect bought a ticket. Bad judgment is not presently a criminal offence, for reasons of capacity.',
   sentence:'Subscriptions are cancelled. The prophet is ordered to eat the eclipse in front of the congregation.',
   objection:'Objection. Eating the moon is a protected religious practice I have just established.',
   exhibits:['Adhesive recovered from the false moon','Collar residue transferred to the window','Support marks beneath the installation'],
   reconstruction:'The window reconstruction and examination of the false moon' },
 { charge:'Selling witness protection that consists entirely of false moustaches.',
   opening:'The witnesses have been placed in one tin. The defendant labelled it “witnesses”.',
   prosecution:'Every crumb paid for a new identity. Each received a moustache and directions to the same unsafe address.',
   plea:'The moustaches were different sizes. I took their circumstances seriously.',
   conviction:'The court finds the protection programme was primarily protecting its own profit margin.',
   acquittal:'This suspect also paid for protection. You may recognise them despite the moustache.',
   sentence:'The programme is closed. Its director is given a new identity: the defendant in next Tuesday’s hearing.',
   objection:'Objection. The labels were for internal use by anyone who opened the tin.',
   exhibits:['Material analysis of the false moustaches','Tool marks on the discarded disguise offcuts','Container traces from the protected witnesses'],
   reconstruction:'The disguise workshop reconstruction and examination of the witness container' }
];
