// The observations are reliable facts, not testimony to guess about. Each new
// hearing rotates which facts matter; names and cosmetic art never give a clue.
const axis = (name, values) => ({ name, values });
export const COURT_LEVELS = [
 { name:'Cozy', summary:'3 suspects · 2 direct clues', instructions:'Find the only suspect who fits both exhibits. Read at your own pace; there is no timer.' },
 { name:'Curious', summary:'4 suspects · 3 clues, including exclusions', instructions:'Some evidence tells you what the culprit did not have. The answer must fit every exhibit.' },
 { name:'Tangled', summary:'4 suspects · either/or and conditional clues', instructions:'Exactly one means one statement is true, never both. An “if” rule only rules somebody out when its first part is true and its second part is false.' }
];
export const COURT_CASES = [
 { title:'The biscuit with a bite missing', intro:'Half a biscuit has been eaten. The surviving half has retained counsel. The heirs are arguing over what is left.', object:'The biscuit',
   axes:[axis('Residue',['had jam on their sleeve','had flour on their sleeve','had cocoa on their sleeve']),axis('Last location',['stood beside the lamp','stood beside the bowl','stood beside the clock']),axis('Pocket contents',['carried a teaspoon','carried a paper bag','carried a brass key'])],
   end:'The defendant will inform the family. They are still in the packet.' },
 { title:'The unauthorised funeral', intro:'A crumb was buried alive during a heavily discounted funeral. It dug itself out and would like its deposit back.', object:'The crumb grave',
   axes:[axis('Tool',['carried a teaspoon','carried a fork','carried a thimble']),axis('Ribbon',['wore a black ribbon','wore a red ribbon','wore a striped ribbon']),axis('Shoes',['had muddy shoes','had floury shoes','had clean shoes'])],
   end:'The grave must be filled in. The victim has declined the loyalty card.' },
 { title:'The lamp that went missing', intro:'The communal lamp vanished. An unlicensed interrogation service opened shortly afterward, with excellent lighting.', object:'The little lamp',
   axes:[axis('Cloth',['carried a blue cloth','carried a green cloth','carried a dotted cloth']),axis('Last location',['stood at the doorway','stood at the window','stood behind the curtain']),axis('Residue',['had wax on their cuffs','had dust on their cuffs','had jam on their cuffs'])],
   end:'The lamp is returned. The business is closed. Confessions already invoiced remain disputed.' },
 { title:'The forged eviction', intro:'A forged eviction notice appeared beside a price list for the tenants’ beds. Someone has monetised the emergency.', object:'The forged eviction notice',
   axes:[axis('Ink',['used violet ink','used black ink','used green ink']),axis('Stamp',['held a round stamp','held a square stamp','held a star stamp']),axis('Paper',['carried lined paper','carried spotted paper','carried plain paper'])],
   end:'The eviction is cancelled. The defendant must live next to the person who snores.' },
 { title:'The last word held for ransom', intro:'A resident staged its death to escape a debt. Someone bottled its last word and sold the family subscriptions. The resident has returned to demand royalties.', object:'The last word',
   axes:[axis('Container',['held a glass jar','held a wooden box','held a paper envelope']),axis('Last location',['stood near the curtain','stood near the stair','stood near the clock']),axis('Sleeve',['had a wool sleeve','had a cotton sleeve','had a silk sleeve'])],
   end:'The word is returned. It was “actually”. The resident resumes being unbearable without a paywall.' },
 { title:'The pea’s suspicious coronation', intro:'A pea has seized the throne, banned elections, and ordered the jury steamed. Someone helped with the crown.', object:'The paper crown',
   axes:[axis('Paper',['held gold paper','held silver paper','held green paper']),axis('Tool',['carried scissors','carried glue','carried a hole punch']),axis('Accessory',['wore a tiny cape','wore a paper hat','wore a ribbon sash'])],
   end:'The monarchy is dissolved into soup. The cabinet has requested separate bowls.' },
 { title:'The emergency that was a raisin', intro:'A raisin was declared a plague victim. During the evacuation, someone offered cash for the supposedly contaminated beds.', object:'The alarm bell',
   axes:[axis('Gloves',['wore wool gloves','wore silk gloves','wore paper gloves']),axis('Tool',['held a pencil','held a spoon','held a paintbrush']),axis('Last location',['stood on the top shelf','stood on the middle shelf','stood on the bottom shelf'])],
   end:'All beds are returned. The raisin remains under observation until the coroner finishes lunch.' },
 { title:'The rent paid in moths', intro:'Six moths were passed off as rent. They had been told the envelope was affordable housing. Neither claim has survived inspection.', object:'The rent envelope',
   axes:[axis('Seal',['used a wax seal','used a glue seal','used a ribbon seal']),axis('Bag',['carried a velvet bag','carried a paper bag','carried a string bag']),axis('Residue',['had glitter on their fingers','had flour on their fingers','had soot on their fingers'])],
   end:'The moths are released. The landlord tries to charge them an exit fee and is added to the docket.' },
 { title:'The inheritance portrait', intro:'A family portrait has been altered to make its owner look dead. A request to open the will arrived before the paint dried.', object:'The altered portrait',
   axes:[axis('Drawing tool',['held a charcoal stick','held a pencil','held a paintbrush']),axis('Headwear',['wore a beret','wore a bonnet','wore a paper crown']),axis('Last location',['stood by the frame','stood by the easel','stood by the sink'])],
   end:'The portrait is restored. The defendant is removed from the will and added to the portrait.' },
 { title:'The teaspoon declared dead', intro:'A teaspoon was declared dead and its pension withdrawn. The spoon turned up alive, tarnished, and understandably difficult.', object:'The travelling teaspoon',
   axes:[axis('String',['carried red thread','carried blue thread','carried white thread']),axis('Footwear',['wore slippers','wore boots','wore socks']),axis('Pocket contents',['carried a magnet','carried a button','carried a pebble'])],
   end:'The pension is restored. The spoon names a fork as its sole beneficiary out of spite.' },
 { title:'The counterfeit moon', intro:'A biscuit taped to the window triggered an eclipse cult. Someone sold evacuation subscriptions before anyone checked the sky.', object:'The fraudulent moon',
   axes:[axis('Adhesive',['held sticky tape','held a glue stick','held sealing wax']),axis('Residue',['had crumbs on their collar','had glitter on their collar','had chalk on their collar']),axis('Last location',['stood on a stool','stood on a box','stood on the floor'])],
   end:'Subscriptions are cancelled. The prophet is ordered to eat the eclipse in front of the congregation.' },
 { title:'The tiny witness protection programme', intro:'Vulnerable crumbs paid for new identities. They received false moustaches and were all hidden in a tin labelled “witnesses”.', object:'The false moustaches',
   axes:[axis('Material',['carried black yarn','carried brown wool','carried grey felt']),axis('Tool',['held small scissors','held a needle','held tweezers']),axis('Container',['carried a matchbox','carried a mint tin','carried a paper cup'])],
   end:'The programme is closed. Its director is given a new identity: the defendant in next Tuesday’s hearing.' }
];
export const COURT_DEFENCES = [
 '“The victim owed me money. Now nobody owes me money. Explain how I benefited.”',
 '“I was grieving privately. If you saw me laughing, you should respect my process.”',
 '“I did threaten them, yes. I threaten everyone. Ask my references.”',
 '“The obituary was a draft. I like to be prepared.”',
 '“My solicitor says I should stop calling it a successful misunderstanding.”',
 '“I have a receipt proving I was buying something much worse.”',
 '“Nobody was using that grave at the time.”',
 '“I reported the smell three days early. Apparently that is suspicious now.”',
 '“We had an understanding. They would leave everything to me. I was helping with the timing.”',
 '“You keep saying ‘victim’. Before this happened, they were widely considered a nuisance.”',
 '“I did not kill it. I declared it no longer cost-effective.”',
 '“Can the jury be replaced? Several of them stand to inherit.”'
];

// Each charge is a small, specific story. The factual exhibits remain separate
// from these interested parties and their very selective remorse.
export const COURT_TRANSCRIPTS = [
 { charge:'The deliberate reduction of a neighbour to leftovers.',
   opening:'The victim has been identified by dental records. Specifically, yours.',
   prosecution:'Half a biscuit is missing. The surviving half has already been offered a lower settlement.',
   plea:'It said “eat me” on the packet. I assumed that was legally binding.',
   conviction:'The court finds that hunger explains the offence. It does not explain the pre-written obituary.',
   acquittal:'Enthusiasm is not evidence, counsel. You have accused someone who merely looked pleased.',
   sentence:'The defendant will inform the family. They are still in the packet.',
   objection:'Objection. The prosecution keeps saying “remains” and making me hungry.',
   exhibits:['Residue recovered from the bite','Wax and dust transfer on the plate','Pocket impressions in the discarded wrapper'],
   reconstruction:'The laboratory reconstructed the bite and the transfer marks' },
 { charge:'Burial without a death, a permit, or the occupant’s consent.',
   opening:'The deceased has asked to stand rather than lie in evidence.',
   prosecution:'The defendant booked the burial before checking whether the crumb was dead. There was a discount for weekdays.',
   plea:'It was a very good plot. You cannot expect me to waste the deposit.',
   conviction:'The court rejects “eventually” as an answer to whether the victim was dead.',
   acquittal:'Your suspect attended the funeral. Attendance alone is not murder, whatever the catering suggests.',
   sentence:'The grave must be filled in. The victim has declined the loyalty card.',
   objection:'Objection. My client thought the scratching was settling soil.',
   exhibits:['Marks cut into the grave floor','Fibres trapped beneath the headstone','Soil tracked across the burial sheet'],
   reconstruction:'A reconstruction of the burial marks' },
 { charge:'The theft of communal light for a private interrogation business.',
   opening:'The defendant’s new business has one chair and no satisfied customers.',
   prosecution:'The lamp vanished at ten. By eleven, the defendant was charging residents to admit things.',
   plea:'Nobody had to confess. The chair was available indefinitely.',
   conviction:'Calling it a “listening service” does not improve the straps.',
   acquittal:'Looking sinister in the dark is not a crime. We would have to arrest the entire shelf.',
   sentence:'The lamp is returned. The business is closed. Confessions already invoiced remain disputed.',
   objection:'Objection. Those testimonials were given voluntarily, after a while.',
   exhibits:['Fibres caught under the lamp base','Wax trail at the scene','Residue transferred to the stolen switch'],
   reconstruction:'The recovered lamp and its transfer marks' },
 { charge:'Forgery with intent to make homelessness administratively convenient.',
   opening:'The eviction notice allows thirty days. The defendant crossed out “days”.',
   prosecution:'The forged letter orders everyone out. Beneath it is a price list for their vacant beds.',
   plea:'I prefer “accelerated estate planning”. Nobody has to die first.',
   conviction:'A signature obtained from a sleeping person is still forgery, even if you held the pen very gently.',
   acquittal:'This suspect dislikes the tenants. That establishes membership of the household, not guilt.',
   sentence:'The eviction is cancelled. The defendant must live next to the person who snores.',
   objection:'Objection. The prosecution is making property ownership sound unpleasant.',
   exhibits:['Ink analysis of the forged signature','Seal impression on the notice','Paper fibres recovered from the printing table'],
   reconstruction:'Tests of the forged notice and the tools that made it' },
 { charge:'The theft and attempted resale of someone else’s final words.',
   opening:'The alleged deceased is alive and charging the prosecution an appearance fee.',
   prosecution:'The resident was rehearsing its death to avoid a debt. Someone bottled the last word and billed the family for closure.',
   plea:'They did not have to stay subscribed. I explained that closure would stop working.',
   conviction:'The court rejects the claim that a staged death permits genuine extortion.',
   acquittal:'Cruelty is a motive, counsel. Several people in this room have it in abundance.',
   sentence:'The word is returned. It was “actually”. The resident resumes being unbearable without a paywall.',
   objection:'Objection. The relatives have already consumed part of the product.',
   exhibits:['Sound test of the recovered container','Fibres caught in its lid','Fabric impression on the bedside dust'],
   reconstruction:'The bedside recording and the container examination' },
 { charge:'Conspiracy to install an edible dictator.',
   opening:'His Majesty has ordered the jury steamed. We will proceed promptly.',
   prosecution:'Within minutes of coronation, the pea abolished elections and declared every spoon a political prisoner.',
   plea:'It promised stable government. Being round seemed like a manageable flaw.',
   conviction:'“Only following recipes” is not a defence to treason.',
   acquittal:'Wearing a stupid accessory does not establish guilt. The judge would have to recuse himself.',
   sentence:'The monarchy is dissolved into soup. The cabinet has requested separate bowls.',
   objection:'Objection. The prosecution is encouraging a serving suggestion.',
   exhibits:['Paper analysis of the royal crown','Tool marks along the crown’s edges','Fabric caught in the throne pins'],
   reconstruction:'A reconstruction of the crown-making and throne assembly' },
 { charge:'Staging a public emergency to purchase the victims’ property cheaply.',
   opening:'The alleged corpse is a raisin. The coroner has declined to revise the invoice.',
   prosecution:'Someone rang the alarm, shouted “plague”, and offered cash for the evacuated beds.',
   plea:'I was providing liquidity during a crisis I understood unusually well.',
   conviction:'The court finds the defendant guilty of panic-selling other people’s belongings.',
   acquittal:'The suspect panicked. That makes them a customer, not the architect of this unpleasant little business.',
   sentence:'All beds are returned. The raisin remains under observation until the coroner finishes lunch.',
   objection:'Objection. It looked considerably more dead before the lighting was improved.',
   exhibits:['Fibres recovered from the bell rope','Impact marks on the alarm striker','Dust transfer beneath the bell mounting'],
   reconstruction:'Tests of the alarm mechanism and evacuation footage' },
 { charge:'Rent fraud and the involuntary subletting of six moths.',
   opening:'The rent envelope is moving. The landlord has called this an encouraging market signal.',
   prosecution:'Six moths were delivered as payment. Each had been promised the envelope was a one-bedroom flat.',
   plea:'They were fully furnished. They all had wings.',
   conviction:'The court rejects “air conditioning included” as a description of a hole in an envelope.',
   acquittal:'Your suspect is a tenant. The court recognises the expression of permanent dread.',
   sentence:'The moths are released. The landlord tries to charge them an exit fee and is added to the docket.',
   objection:'Objection. Nobody asked whether the moths had references.',
   exhibits:['Seal residue on the rent envelope','Fibres recovered from the moth transport','Finger marks beneath the false payment slip'],
   reconstruction:'The envelope examination and rental-office reconstruction' },
 { charge:'Premeditated disfigurement of a portrait to accelerate an inheritance.',
   opening:'The portrait now appears gravely ill. The person in it remains irritatingly healthy.',
   prosecution:'Someone added funeral shading to the family portrait and began measuring the curtains.',
   plea:'I was helping everyone visualise a difficult transition.',
   conviction:'The court finds that an artistic interpretation of death does not open probate.',
   acquittal:'Disliking the portrait is not evidence. We have all seen it.',
   sentence:'The portrait is restored. The defendant is removed from the will and added to the portrait.',
   objection:'Objection. The subject already looked like that in certain light.',
   exhibits:['Drawing residue inside the added marks','Headwear fibres caught behind the canvas','Footprints in the disturbed studio dust'],
   reconstruction:'The studio reconstruction and examination of the altered canvas' },
 { charge:'Faking a teaspoon’s death to collect its pension.',
   opening:'The missing teaspoon has been found. It would like to know why its pension is empty.',
   prosecution:'A death notice was filed at nine. At ten, the teaspoon was seen being dragged toward the door.',
   plea:'It had retired from stirring. I thought the rest was a technicality.',
   conviction:'The court observes that the defendant spent the funeral allowance before buying a coffin.',
   acquittal:'The suspect had access to the drawer. So does everyone with a modest amount of ambition.',
   sentence:'The pension is restored. The spoon names a fork as its sole beneficiary out of spite.',
   objection:'Objection. The witness has been in hot water before.',
   exhibits:['Thread recovered from the teaspoon handle','Footprints beside the drawer','Magnetic and abrasion tests on the spoon bowl'],
   reconstruction:'The drawer reconstruction and pension-office evidence' },
 { charge:'Operating an apocalypse subscription using a biscuit taped to a window.',
   opening:'The end of the world has been postponed until the next billing cycle.',
   prosecution:'The moon was replaced with a biscuit. Residents were sold priority evacuation places in a shoebox.',
   plea:'Nobody can prove the shoebox would not have worked.',
   conviction:'The court finds that the defendant confused salvation with recurring revenue.',
   acquittal:'Your suspect bought a ticket. Bad judgment is not presently a criminal offence, for reasons of capacity.',
   sentence:'Subscriptions are cancelled. The prophet is ordered to eat the eclipse in front of the congregation.',
   objection:'Objection. Eating the moon is a protected religious practice I have just established.',
   exhibits:['Adhesive recovered from the false moon','Collar residue transferred to the window','Support marks beneath the installation'],
   reconstruction:'The window reconstruction and examination of the false moon' },
 { charge:'Selling witness protection that consists entirely of false moustaches.',
   opening:'The witnesses have been placed in one tin. The defendant labelled it “witnesses”.',
   prosecution:'Every crumb paid for a new identity. Each received a moustache and directions to the same unsafe address.',
   plea:'The moustaches were different sizes. I took their circumstances seriously.',
   conviction:'The court finds the protection programme was primarily protecting its own profit margin.',
   acquittal:'This suspect also paid for protection. You may recognise them despite the moustache.',
   sentence:'The programme is closed. Its director is given a new identity: the defendant in next Tuesday’s hearing.',
   objection:'Objection. The labels were for internal use by anyone who opened the tin.',
   exhibits:['Material analysis of the false moustaches','Tool marks on the discarded disguise offcuts','Container traces from the protected witnesses'],
   reconstruction:'The disguise workshop reconstruction and examination of the witness container' }
];
