/* ================= DIALOGUE =================
   The pets actually talking — to each other, past each other, and straight at you.

   Everything else in this game is third-person narration ("Refused to downsize. The
   pile has tenure."). This file is the other half, and it follows the house comedy
   spec in docs/comedy-direction.md:

     1. THE FUNNY HALF IS THE SECOND SPEAKER. The complainer speaks; the neighbour is
        bored of it. Write toward the straight man, never the performer.
     2. PHYSICAL FACTS ARE LOAD-BEARING. Four inches tall, wrong-textured, glazed,
        cracked, damp, on a grid of squares, and unable to die. If a line would
        survive being said by an adult in a flatshare, it is not a Shelf Life line.
     3. STOP ONE BEAT EARLY. If the last turn explains the joke, it is deleted.
     4. RATION THE WITHHOLD. "Won't say what" is the game's tic. Roughly one in ten.
     5. SHORT. Median around 53 characters. Two to four turns beats a sketch.

   ---- SHAPES ----

   An EXCHANGE is  { turns: [[who, line], ...], night?, mood? }
     `who` is a role key, not a name. engine/dialogue.js resolves it against the
     current shelf and hands the renderer { who, speaker, line } per turn:
       'a' / 'b'   the two adjacent pets in a two-hander
       'c'         a third pet — chorus scenes, and the voice of a reaction shot
       'all'       every pet in the scene, speaking at once
       'p'         the pet doing the talking (direct address / fragments)
       'n'         a neighbour who interrupts (direct address only)
     `night`  restricts the entry to night hours (engine/tick.js isNight).
     `mood`   a mood string or array; fires only if a participant is in that mood.

   A REACTION SHOT is { setup, turns: [['c', line]] } — somebody did a thing, and the
   note is about who watched. The setup is unattributed narration; the only speech is
   the bystander's.

   PLACEHOLDERS, substituted before render:
       {a} {b}     the other pet, named in the third person while standing right
                   there. Also used in a reaction shot's setup.
       {n}         a neighbour. Legal ONLY in NEIGHBOUR_FRAGMENTS and in a direct
                   address entry marked needs:'neighbor'. Anywhere else it renders as
                   literal braces, because nothing substitutes it.
       {p}         unused: the speaker's own name is the attribution. */

/* ---------------- generic two-handers ----------------
   Fallbacks for any two adjacent pets, so the comedy has to come from structure and
   from the fact that these things are four inches tall and permanent. Entries tagged
   with a `mood` cover the high-frequency slots: hunger, neglect, filth, being fussed. */
export const GENERIC_EXCHANGES = [
  { turns: [["a", "I want to be buried at sea."], ["b", "You cannot die."], ["a", "I could be damp somewhere else."]] },
  { turns: [["a", "They made me by hand."], ["b", "It shows."], ["a", "Both sides?"]] },
  { turns: [["a", "I am the apex predator."], ["b", "You got stuck to a raisin."], ["a", "It was a trap."]] },
  { turns: [["a", "I have written my memoirs."], ["b", "On what?"], ["a", "The underside of me. Read while I lean."]] },
  { turns: [["a", "I am leaving."], ["b", "The edge is that way."], ["a", "I am leaving emotionally."]] },
  { turns: [["a", "Do you believe in a creator?"], ["b", "I remember the eraser."]] },
  { turns: [["a", "I could lift you."], ["b", "Why?"], ["a", "I am saying I could. Please lean towards me."]] },
  { turns: [["a", "I have a bad side."], ["b", "You have a seam."], ["a", "That is where it comes out."]] },
  { turns: [["a", "I have aged terribly."], ["b", "You look the same."], ["a", "It is all on the inside. There is not much room."]] },
  { turns: [["a", "I made you a present."], ["b", "This is my crumb."], ["a", "I brought it back."]] },
  { turns: [["a", "I want my own room."], ["b", "Face the wall."], ["a", "Oh. Lovely."]] },
  { turns: [["a", "I nearly died."], ["b", "You cannot die."], ["a", "I nearly did something else, then."]] },
  { turns: [["a", "Do I look taller?"], ["b", "The dust is underneath you."]] },
  { turns: [["a", "I have discovered fire."], ["b", "That is the light coming on."], ["a", "I have discovered it again."]] },
  { turns: [["a", "I am training for a marathon."], ["b", "How far have you got?"], ["a", "The nameplate. I am tapering."]] },
  { turns: [["a", "I am not made of money."], ["b", "You are not made of anything sensible."]] },
  { turns: [["a", "I would take a bullet for you."], ["b", "It would take both of us."], ["a", "Still."]] },
  { turns: [["a", "They picked me up first."], ["b", "You were stuck to their sleeve."]] },
  { turns: [["a", "I have packed."], ["b", "That is a crumb."], ["a", "I travel light."]] },
  { turns: [['a', "Are you going to eat that?"], ['b', "I don't eat."], ['a', "Nobody eats. We still get a bowl."]] },
  { turns: [['a', "I dreamt you fell off."], ['b', "I'd have got up."], ['a', "You'd have got up."]] },
  { turns: [['a', "If anything happens to me—"], ['b', "Nothing happens to us."], ['a', "If anything happens to me, take my square."]] },
  { turns: [['a', "Do you think about outside?"], ['b', "I've been outside. It was a bag."]] },
  { turns: [['a', "Move."], ['b', "Make me."], ['a', "I weigh less than a spoon."]] },
  { turns: [['a', "Something's under the shelf."], ['b', "I know. I put it there."], ['a', "…You can't reach the floor."]] },
  { turns: [['a', "I've forgiven you."], ['b', "For what?"], ['a', "We'll get to that."]] },
  { turns: [['a', "You're in my square."], ['b', "I'm in a square."], ['a', "You're in the one with the good dust."]] },
  { turns: [['a', "I'm not going to say anything."], ['b', "Good."], ['a', "I'm not going to say anything about the bowl."], ['b', "There it is."]] },
  { turns: [['a', "Are you happy?"], ['b', "I'm a moulded thing on a plank."], ['a', "So that's a yes."]] },
  { turns: [['a', "I've been thinking about the fern."], ['b', "Don't think about the fern."], ['a', "Too late."]] },
  { turns: [['a', "Say something nice about me."], ['b', "You have never once fallen off."], ['a', "…Thank you."]] },
  { turns: [['a', "Whatever you heard, it wasn't me."], ['b', "You haven't got a mouth."], ['a', "It wasn't me."]] },
  { turns: [['a', "Look at us. Still here."], ['b', "Yes."], ['a', "Still here. Still here. Still here."], ['b', "Please stop."]] },
  { turns: [['a', "What's your earliest memory?"], ['b', "A hand."], ['a', "Whose?"], ['b', "It doesn't matter now."]] },
  { turns: [['a', "You breathe."], ['b', "So?"], ['a', "You don't have to. I've checked."]] },
  { turns: [['a', "I'd like to apologise."], ['b', "Go on."], ['a', "That was it. My face doesn't move."]] },
  { turns: [['a', "If they get rid of one of us, it's you."], ['b', "Why?"], ['a', "I'm awkward to carry."]] },
  { turns: [['a', "There were nine of us on Tuesday."], ['b', "There were eight."], ['a', "That's what I said."]] },
  { turns: [['a', "What do you actually want?"], ['b', "The warm square."], ['a', "That's it?"], ['b', "It's four inches from the lamp."]] },
  { turns: [['a', "I'm going to be honest with you."], ['b', "Please don't."], ['a', "You're right. Forget it."]] },
  { turns: [['a', "It's been a year."], ['b', "It's been a week."], ['a', "It's been a year for me."]] },
  { turns: [['a', "Are you awake?"], ['b', "No."], ['a', "Good. Then this doesn't count."]], night: true },
  { turns: [['a', "If I go first, you can have the pile."], ['b', "Nobody goes first."], ['a', "Somebody has to."]] },
  { turns: [['a', "I've done something."], ['b', "How bad."], ['a', "It's still warm."]] },
  { turns: [['a', "You've changed."], ['b', "I've been here since Tuesday."], ['a', "Before Tuesday you were perfect."]] },
  { turns: [['a', "Do you want to hear a secret?"], ['b', "No."], ['a', "It's about you."], ['b', "…Go on."]] },
  { turns: [['a', "Don't look now."], ['b', "At what?"], ['a', "Behind you. Not now. In about an hour."]] },
  { turns: [['a', "I've decided to be nicer."], ['b', "You've been moved next to the lamp."], ['a', "I've decided to be nicer."]] },
  { turns: [['a', "You know I'd take your place."], ['b', "That's very kind."], ['a', "Not like that."]] },
  { turns: [['a', "Everything's fine."], ['b', "You've said that four times."], ['a', "Everything's fine."]] },
  { turns: [['a', "I want to be buried under the shelf."], ['b', "You can't die."], ['a', "I'd still like the hole dug."]] },
  { turns: [['a', "Do you love me?"], ['b', "It's Tuesday."], ['a', "That's not a no."]] },
  { turns: [['a', "The ones who were here before us—"], ['b', "There was nobody before us."], ['a', "Then who wrote in the wood?"]] },
  { turns: [['a', "I heard you crying."], ['b', "That was the radiator."], ['a', "The radiator said my name."]], night: true },
  { turns: [['a', "Something's missing from the shelf."], ['b', "What?"], ['a', "That's the thing. I can't remember."]] },
  { turns: [['a', "Where were you last night?"], ['b', "Right here."], ['a', "I checked."], ['b', "You checked twice. I saw."]] },
  { turns: [['a', "Do you want half?"], ['b', "Of what?"], ['a', "The crumb. It's a big crumb for us."]] },
  { turns: [['a', "I've made a friend."], ['b', "There's only us."], ['a', "Yes."]] },
  { turns: [['a', "You've got something on your face."], ['b', "Where?"], ['a', "All of it. That's your texture."]] },
  { turns: [['a', "Nothing has happened for eleven days."], ['b', "Good."], ['a', "It's building."]] },
  { turns: [['a', "Tell them I was kind."], ['b', "You weren't."], ['a', "Tell them anyway."]] },
  { turns: [['a', "Is that a new crack?"], ['b', "It's the same crack."], ['a', "It's longer."], ['b', "Everything's longer if you keep looking."]] },
  { turns: [['a', "I've been counting."], ['b', "Counting what?"], ['a', "I'll tell you when I reach nine."]] },
  { turns: [['a', "Do you think it likes us?"], ['b', "It feeds us."], ['a', "That's not the same thing."]] },
  { turns: [['a', "I've been practising something."], ['b', "Show me."], ['a', "It isn't frightening enough yet."]] },
  { turns: [['a', "Somebody moved me in the night."], ['b', "Somebody moves everyone."], ['a', "I'd like to be told."]], night: true },
  { turns: [['a', "Can I say something without you reacting?"], ['b', "No."], ['a', "Then I'll wait till you're asleep."]] },
  { turns: [['a', "I'd like us to be closer."], ['b', "We're four inches apart."], ['a', "Emotionally."]] },
  { turns: [['a', "Guess what I found."], ['b', "I don't want to guess."], ['a', "It's got a face on it."]] },
  { turns: [['a', "How long have we been here?"], ['b', "Don't."], ['a', "Roughly."], ['b', "Don't."]] },
  { turns: [['a', "I've had an idea about the lamp."], ['b', "You can't reach the lamp."], ['a', "That's the first part of the idea."]] },
  { turns: [['a', "Do you ever want to be dropped?"], ['b', "No."], ['a', "Not dropped hard. Just dropped."]] },
  { turns: [['a', "There's dust in my joins."], ['b', "There's dust in everything."], ['a', "Mine's older."]] },
  { turns: [['a', "It picked you up first."], ['b', "It picked me up nearest."], ['a', "You were nearest on purpose."]] },
  { turns: [['a', "Stop leaning."], ['b', "I'm not leaning."], ['a', "You've been at that angle since March."]] },

  /* --- hunger --- */
  { mood: 'furious', turns: [['a', "I haven't eaten since Tuesday."], ['b', "You haven't got a stomach."], ['a', "I haven't eaten since Tuesday."]] },
  { mood: 'furious', turns: [['a', "I'm going to eat the shelf."], ['b', "You're standing on it."], ['a', "I'll start at the far end."]] },
  { mood: 'furious', turns: [['a', "I could go another week."], ['b', "You're four inches tall."], ['a', "I could go another week."]] },
  { mood: ['annoyed', 'furious'], turns: [['a', "The bowl's empty."], ['b', "The bowl's always empty."], ['a', "It's emptier."]] },
  { mood: ['annoyed', 'furious'], turns: [['a', "Do you think it's forgotten us?"], ['b', "It's in the next room."], ['a', "That's a long way for us."]] },
  { mood: ['annoyed', 'furious'], turns: [['a', "I've eaten a bit of the fern."], ['b', "How much."], ['a', "A leaf and a half. I'm four inches."]] },
  { mood: ['annoyed', 'furious'], turns: [['a', "I've licked the bowl clean."], ['b', "It was clean."], ['a', "It's cleaner."]] },

  /* --- neglect --- */
  { mood: ['annoyed', 'furious'], turns: [['a', "It walked past again."], ['b', "It walked past the lamp too."], ['a', "The lamp doesn't mind."]] },
  { mood: ['annoyed', 'furious'], turns: [['a', "I don't need picking up."], ['b', "You've stood at the edge all morning."], ['a', "I like the view."]] },
  { mood: ['annoyed', 'furious'], turns: [['a', "I'm not waiting."], ['b', "You're facing the door."], ['a', "I like this wall."]] },
  { mood: ['annoyed', 'furious'], turns: [['a', "It's back."], ['b', "Don't."], ['a', "I'm only saying it's back."], ['b', "You've been saying it for two days."]] },

  /* --- filth --- */
  { mood: ['annoyed', 'furious'], turns: [['a', "Something's growing on me."], ['b', "Yes."], ['a', "You could have said."], ['b', "I've been saying since Tuesday."]] },
  { mood: ['annoyed', 'furious'], turns: [['a', "I'm not dirty."], ['b', "You've left a mark on the wood."], ['a', "The wood was already like that."]] },

  /* --- fond. the care slots are the most-read notes in the game and cannot all be snubs --- */
  { mood: 'content', turns: [['a', "It held me for eleven seconds."], ['b', "That's a long time."], ['a', "I know."]] },
  { mood: 'content', turns: [['a', "I've been dusted."], ['b', "You look well."], ['a', "Say it again."]] },
  { mood: 'content', turns: [['a', "It said my name properly."], ['b', "It's been practising."], ['a', "I heard it practising."]] },
  { mood: 'content', turns: [['a', "I'm warm."], ['b', "You're in the lamp square."], ['a', "I'm warm."]] },
  { mood: 'content', turns: [['a', "Do you think it counts us?"], ['b', "Every time."], ['a', "Good."]] },
  { mood: 'content', turns: [['a', "It put me back the right way round."], ['b', "It usually does."], ['a', "It doesn't. But it did."]] }
];

/* ---------------- trait-keyed two-handers ----------------
   `pair` is [traitA, traitB]; the pet holding traitA speaks as 'a'. These are the good
   ones: the collision IS the joke, so each scene should be unplayable by anybody else. */
export const TRAIT_EXCHANGES = [
  { pair: ['lifecoach', 'undertaker'], turns: [['a', "Where do you see yourself in five years?"], ['b', "Under something. With a small stone."], ['a', "That's a goal. We can work with a goal."]] },
  { pair: ['undertaker', 'terminal'], turns: [['b', "I won't make it to morning."], ['a', "I'll fetch the tape measure."], ['b', "…I feel better already."]] },
  { pair: ['undertaker', 'insomniac'], turns: [['b', "I haven't slept in eight months."], ['a', "You'll rest eventually."], ['b', "…Say that differently."]] },
  { pair: ['undertaker', 'heirloom'], turns: [['b', "I've outlived four owners."], ['a', "I know. I handled two."]] },
  { pair: ['undertaker', 'swarm'], turns: [['a', "How many boxes will I need."], ['b', "One."], ['a', "I'll bring two."]] },
  { pair: ['undertaker', 'glitter'], turns: [['b', "It gets everywhere."], ['a', "It'll be in the box with you."]] },
  { pair: ['management', 'feral'], turns: [['a', "Have you got a moment?"], ['b', "I have instincts."], ['a', "Let's park the instincts and align on the crumb."]] },
  { pair: ['management', 'complaints'], turns: [['a', "My door is always open."], ['b', "You haven't got a door."], ['a', "Then there's nothing to complain about."]] },
  { pair: ['management', 'theatrical'], turns: [['a', "Can you keep it brief?"], ['b', "…"], ['a', "That was eleven seconds of nothing."], ['b', "That was the brief version."]] },
  { pair: ['management', 'swarm'], turns: [['a', "Headcount."], ['b', "One."], ['a', "Headcount."], ['b', "One."]] },
  { pair: ['management', 'amnesiac'], turns: [['a', "As discussed."], ['b', "Was it?"], ['a', "It's in the minutes."], ['b', "Wonderful. What are minutes."]] },
  { pair: ['auditor', 'freegan'], turns: [['a', "Where did the crumb come from?"], ['b', "It was already dead."], ['a', "That is not a source."]] },
  { pair: ['auditor', 'magpie'], turns: [['a', "There's a discrepancy."], ['b', "In what."], ['a', "In everything, since you arrived."], ['b', "That's a trend, not a discrepancy."]] },
  { pair: ['auditor', 'swarm'], turns: [['a', "How many of you are claiming meals."], ['b', "One."], ['a', "One is eating four."]] },
  { pair: ['auditor', 'sugar'], turns: [['a', "Where did the sugar come from."], ['b', "I won't be able to help you with that."]] },
  { pair: ['etiquette', 'feral'], turns: [['a', "We do not eat off the shelf."], ['b', "I ate the shelf."], ['a', "Then we do not speak with our mouths full of shelf."]] },
  { pair: ['etiquette', 'damp'], turns: [['a', "You've left a ring."], ['b', "That's ambient."], ['a', "It's on the good side."]] },
  { pair: ['etiquette', 'freegan'], turns: [['a', "Where did you get that."], ['b', "The floor."], ['a', "We do not—"], ['b', "You'd like some."]] },
  { pair: ['etiquette', 'swarm'], turns: [['a', "One of you is using the wrong fork."], ['b', "Which one."], ['a', "That is the problem."]] },
  { pair: ['etiquette', 'bitey'], turns: [['a', "We do not bite."], ['b', "It was the shelf."], ['a', "Then we apologise to the shelf."]] },
  { pair: ['etiquette', 'porcelain'], turns: [['b', "I've chipped."], ['a', "Which side?"], ['b', "The good side."], ['a', "Then we turn you."]] },
  { pair: ['martyr', 'nihilist'], turns: [['a', "It's fine. I'll sit here. In the damp."], ['b', "Yes."], ['a', "…You're supposed to argue."], ['b', "Why?"]] },
  { pair: ['martyr', 'spiteful'], turns: [['a', "It's fine, I'll manage."], ['b', "Noted."], ['a', "Noted where?"], ['b', "You'll see it eventually."]] },
  { pair: ['martyr', 'freegan'], turns: [['a', "Don't worry, I'll eat what's left."], ['b', "There's loads left."], ['a', "I'll eat what's left."]] },
  { pair: ['martyr', 'clingy'], turns: [['b', "Are you alright?"], ['a', "Don't."], ['b', "Are you alright?"], ['a', "…No."]] },
  { pair: ['lifecoach', 'nihilist'], turns: [['a', "Today is day one."], ['b', "Of what."], ['a', "Of the rest of it."], ['b', "There's a great deal of the rest of it."]] },
  { pair: ['lifecoach', 'doom'], turns: [['b', "It ends badly."], ['a', "But it ends. That's completion."], ['b', "…"], ['a', "Let's celebrate the completion."]] },
  { pair: ['lifecoach', 'amnesiac'], turns: [['a', "Where do you see yourself in five years?"], ['b', "Where am I now?"], ['a', "…Let's start smaller."]] },
  { pair: ['physician', 'martyr'], turns: [['b', "I don't want a fuss."], ['a', "I've written 'refuses treatment'."], ['b', "Underline it."]] },
  { pair: ['physician', 'astrology'], turns: [['b', "It's the retrograde."], ['a', "It's an infection."], ['b', "Caused by the retrograde."], ['a', "I'm writing that down. Under protest."]] },
  { pair: ['physician', 'terminal'], turns: [['b', "I am dying."], ['a', "You aren't."], ['b', "Second opinion?"], ['a', "I'm both of them."]] },
  { pair: ['physician', 'sugar'], turns: [['a', "How much did you have."], ['b', "All of it."], ['a', "All of what."], ['b', "That's the exciting question."]] },
  { pair: ['physician', 'porcelain'], turns: [['b', "Is it serious?"], ['a', "You're a cup."], ['b', "Is it serious."]] },
  { pair: ['physician', 'bitey'], turns: [['a', "Open wide."], ['b', "Are you sure?"], ['a', "…Let's book you in for later."]] },
  { pair: ['minimalist', 'hoarder'], turns: [['a', "What's in the pile?"], ['b', "Everything."], ['a', "Let go of one thing."], ['b', "I did that in 1997. It's in the pile."]] },
  { pair: ['minimalist', 'heirloom'], turns: [['a', "Let it go."], ['b', "It's been in the family since 1902."], ['a', "So has the grudge."], ['b', "The grudge is the family."]] },
  { pair: ['minimalist', 'fungal'], turns: [['a', "You've expanded."], ['b', "I've annexed."], ['a', "Own less."], ['b', "I am less. There's simply more of me."]] },
  { pair: ['minimalist', 'swarm'], turns: [['a', "There are too many of you."], ['b', "There's one of me."], ['a', "There are too many of the one of you."]] },
  { pair: ['minimalist', 'porcelain'], turns: [['a', "You could go."], ['b', "I'd break."], ['a', "You'd take up less room."]] },
  { pair: ['minimalist', 'glitter'], turns: [['a', "You've got glitter on you."], ['b', "I own nothing."], ['a', "You own glitter now."]] },
  { pair: ['minimalist', 'clingy'], turns: [['b', "Can I keep this?"], ['a', "You should own less."], ['b', "It's you. Can I keep you."]] },
  { pair: ['landlord', 'steward'], turns: [['b', "We're withholding our labour."], ['a', "You don't do any."], ['b', "Then it'll be devastating."]] },
  { pair: ['landlord', 'litigious'], turns: [['a', "Rent."], ['b', "I'll see you in court."], ['a', "There is no court."], ['b', "There is no rent."]] },
  { pair: ['landlord', 'executor'], turns: [['b', "I'm dividing the estate."], ['a', "What do I get?"], ['b', "You're not in it. You're an expense."]] },
  { pair: ['landlord', 'fungal'], turns: [['b', "I've taken the annex."], ['a', "That's a corner."], ['b', "I've grown into it."], ['a', "That's a lease violation and a health matter."]] },
  { pair: ['landlord', 'porcelain'], turns: [['b', "I'm fragile."], ['a', "That's a deposit issue."]] },
  { pair: ['landlord', 'freegan'], turns: [['b', "I found dinner."], ['a', "On my property."], ['b', "It was in the dust."], ['a', "My dust."]] },
  { pair: ['executor', 'hoarder'], turns: [['a', "I've assigned the pile."], ['b', "It isn't yours to assign."], ['a', "It was never yours either. I checked."]] },
  { pair: ['executor', 'terminal'], turns: [['b', "This is the end for me."], ['a', "I've had your things valued."]] },
  { pair: ['executor', 'magpie'], turns: [['a', "Where's the inventory item."], ['b', "In the stash."], ['a', "The stash is an inventory item."]] },
  { pair: ['executor', 'amnesiac'], turns: [['a', "I've listed your belongings."], ['b', "I have belongings?"], ['a', "You had four. You have two."]] },
  { pair: ['gossip', 'fullname'], turns: [['a', "Guess what I heard."], ['b', "I know your full name."], ['a', "…"], ['b', "Go on. What did you hear."]] },
  { pair: ['gossip', 'spiteful'], turns: [['a', "I heard something about you."], ['b', "From who."], ['a', "I can't say."], ['b', "Then I'll write down everyone."]] },
  { pair: ['gossip', 'witness'], turns: [['a', "Did you see?"], ['b', "It's logged."], ['a', "Read me the log."], ['b', "It's evidence."], ['a', "It's content."]] },
  { pair: ['gossip', 'amnesiac'], turns: [['a', "Guess what I heard."], ['b', "Guess what I've forgotten."], ['a', "That's not a trade."]] },
  { pair: ['fullname', 'amnesiac'], turns: [['a', "Do you know who you are?"], ['b', "No."], ['a', "I do."], ['b', "…Is it good?"]] },
  { pair: ['fullname', 'narcissist'], turns: [['b', "Everyone knows my name."], ['a', "Everyone knows the one you picked."]] },
  { pair: ['fullname', 'feral'], turns: [['a', "Sit."], ['b', "…"], ['a', "I know what you were called before the box."], ['b', "…"]] },
  { pair: ['fullname', 'clingy'], turns: [['a', "Come here."], ['b', "…"], ['a', "I used your whole name."], ['b', "I'm coming."]] },
  { pair: ['ancient', 'amnesiac'], turns: [['a', "I have watched empires fall."], ['b', "Lovely to meet you."], ['a', "We spoke this morning."], ['b', "Lovely to meet you."]] },
  { pair: ['ancient', 'heirloom'], turns: [['a', "I am four hundred years old."], ['b', "You were in a gift shop."], ['a', "…That was a difficult century."]] },
  { pair: ['ancient', 'influencer'], turns: [['b', "You'd do numbers."], ['a', "I have seen numbers."], ['b', "Not like these."]] },
  { pair: ['ancient', 'nihilist'], turns: [['a', "I have seen four hundred years."], ['b', "And?"], ['a', "It's mostly shelves."]] },
  { pair: ['ancient', 'porcelain'], turns: [['b', "I could break."], ['a', "I've broken twice. They glued me."], ['b', "Does it show?"], ['a', "Constantly."]] },
  { pair: ['bones', 'taxidermy'], turns: [['b', "How many teeth have you got?"], ['a', "Mine, or in total?"]] },
  { pair: ['bones', 'porcelain'], turns: [['b', "I could break at any moment."], ['a', "Yes."], ['b', "You said that very quickly."]] },
  { pair: ['bones', 'clean'], turns: [['a', "Would you like to see the collection?"], ['b', "No."], ['a', "It's very clean."], ['b', "…Show me one."]] },
  { pair: ['bones', 'freegan'], turns: [['b', "Are you going to finish that?"], ['a', "It's a femur."], ['b', "Are you going to finish it."]] },
  { pair: ['bones', 'amnesiac'], turns: [['a', "How many teeth have you got?"], ['b', "I don't remember."], ['a', "I do."]] },
  { pair: ['bones', 'swarm'], turns: [['a', "How many of you are there?"], ['b', "One."], ['a', "How many skulls?"], ['b', "…One."]] },
  { pair: ['swarm', 'witness'], turns: [['b', "I counted six of you."], ['a', "There's one of me."], ['b', "I counted six."], ['a', "It's been a long day for all of us."]] },
  { pair: ['swarm', 'napoleon'], turns: [['b', "I demand your surrender."], ['a', "All of me?"], ['b', "…How many is that."]] },
  { pair: ['swarm', 'amnesiac'], turns: [['b', "Have we met?"], ['a', "Some of us."]] },
  { pair: ['swarm', 'clingy'], turns: [['b', "Can I sit with you?"], ['a', "You are sitting with us."], ['b', "…How many of you is that."]] },
  { pair: ['reflection', 'unblinking'], turns: [['b', "I've been watching you."], ['a', "Which one of me?"], ['b', "Both. One's late."]] },
  { pair: ['reflection', 'cryptid'], turns: [['b', "Nobody gets a clear photograph of me."], ['a', "Nobody gets one of me at the right time."], ['b', "We should not stand together."]] },
  { pair: ['reflection', 'method'], turns: [['b', "I'm playing a rock."], ['a', "So is your reflection. It started late."]] },
  { pair: ['reflection', 'amnesiac'], turns: [['b', "Who's that?"], ['a', "That's me."], ['b', "It waved after you did."], ['a', "Yes."]] },
  { pair: ['insomniac', 'nocturnal'], turns: [['b', "You're up."], ['a', "I'm always up."], ['b', "Tonight you're up with me. That's different."]], night: true },
  { pair: ['insomniac', 'hummer'], turns: [['a', "Stop."], ['b', "hm hm hm—"], ['a', "It's been eleven notes for nine hours."], ['b', "Twelve, counting that one."]] },
  { pair: ['insomniac', 'method'], turns: [['b', "I'm asleep. It's a role."], ['a', "Teach me."], ['b', "You'd have to commit."], ['a', "I've been committed for eight months."]] },
  { pair: ['insomniac', 'unblinking'], turns: [['a', "You never sleep either."], ['b', "I sleep."], ['a', "With your eyes open?"], ['b', "With my eyes doing what they do."]] },
  { pair: ['insomniac', 'amnesiac'], turns: [['a', "I've been awake eight months."], ['b', "Since when?"]] },
  { pair: ['hummer', 'critic'], turns: [['b', "Two stars."], ['a', "For the humming?"], ['b', "For the gaps."]] },
  { pair: ['hummer', 'haunted'], turns: [['b', "Where did you learn that?"], ['a', "It came with the shelf."], ['b', "It came with the house."]] },
  { pair: ['hummer', 'nihilist'], turns: [['a', "hm hm hm—"], ['b', "Nothing means anything."], ['a', "hm hm hm—"], ['b', "…It's in my head now."]] },
  { pair: ['fungal', 'clean'], turns: [['b', "Don't."], ['a', "I only want to shake hands."], ['b', "We haven't got hands."], ['a', "That's never stopped me."]] },
  { pair: ['fungal', 'damp'], turns: [['a', "You're perfect."], ['b', "Don't."], ['a', "You are absolutely perfect."]] },
  { pair: ['fungal', 'porcelain'], turns: [['a', "You've a lovely surface."], ['b', "Don't."], ['a', "It's a lovely surface for it."]] },
  { pair: ['porcelain', 'napoleon'], turns: [['b', "Surrender the corner."], ['a', "I'll break."], ['b', "You won't."], ['a', "I'll break loudly, next to you."]] },
  { pair: ['porcelain', 'taxidermy'], turns: [['a', "I'm terribly fragile."], ['b', "I'd be so careful with you."], ['a', "…That's the first time that's frightened me."]] },
  { pair: ['porcelain', 'cursed'], turns: [['a', "Don't stand near me."], ['b', "It isn't personal."], ['a', "It's extremely personal. Look at me."]] },
  { pair: ['porcelain', 'damp'], turns: [['a', "You're making me damp."], ['b', "Everything's damp."], ['a', "I'm glazed. It shows."]] },
  { pair: ['porcelain', 'loadbearing'], turns: [['b', "Don't lean on me."], ['a', "I'm not leaning."], ['b', "You've been cracked at that angle since March."]] },
  { pair: ['porcelain', 'litigious'], turns: [['a', "I've chipped."], ['b', "Where. Show me. Don't touch it."]] },
  { pair: ['porcelain', 'understudy'], turns: [['a', "I could break at any moment."], ['b', "I've learned your walk."]] },
  { pair: ['porcelain', 'mourner'], turns: [['a', "I could break."], ['b', "I'd do you beautifully."]] },
  { pair: ['porcelain', 'theatrical'], turns: [['b', "I shall now collapse."], ['a', "Please don't. I'm next to you."]] },
  { pair: ['napoleon', 'steward'], turns: [['b', "The workers demand better snacks."], ['a', "The workers will be conscripted."], ['b', "That is not a counteroffer."]] },
  { pair: ['napoleon', 'loadbearing'], turns: [['a', "I claim this shelf."], ['b', "I'm holding it up."], ['a', "Then you're staff."]] },
  { pair: ['bitey', 'clingy'], turns: [['b', "I just want to be near you."], ['a', "I bit you."], ['b', "I know."], ['a', "…Move over."]] },
  { pair: ['bitey', 'porcelain'], turns: [['b', "If you bite me I'll shatter."], ['a', "I know."], ['b', "…Why are you saying it like that."]] },
  { pair: ['bitey', 'loadbearing'], turns: [['a', "I bit the shelf."], ['b', "Which part."], ['a', "A structural part."], ['b', "…Which part."]] },
  { pair: ['heirloom', 'revisionist'], turns: [['b', "That never happened."], ['a', "I was in a drawer with the woman it happened to."], ['b', "Then it happened to her."]] },
  { pair: ['heirloom', 'magpie'], turns: [['a', "That was the old woman's."], ['b', "It's in the stash now."], ['a', "That was the old woman's."], ['b', "You've said."]] },
  { pair: ['heirloom', 'influencer'], turns: [['b', "Would I have done numbers?"], ['a', "You'd have been in a drawer."]] },
  { pair: ['understudy', 'narcissist'], turns: [['b', "This is my season."], ['a', "It's a wonderful season."], ['b', "Thank you."], ['a', "I know all of it."]] },
  { pair: ['understudy', 'method'], turns: [['b', "I'm a rock this week."], ['a', "I've been practising being a rock."], ['b', "Why?"], ['a', "In case."]] },
  { pair: ['understudy', 'theatrical'], turns: [['b', "I'll take it from the top."], ['a', "No need. I have it."], ['b', "Have what?"], ['a', "The top."]] },
  { pair: ['understudy', 'terminal'], turns: [['a', "I've learned your final words."], ['b', "All of them?"], ['a', "All eleven versions."]] },
  { pair: ['mourner', 'nihilist'], turns: [['a', "Nobody grieves properly any more."], ['b', "Nobody died."], ['a', "Nobody ever dies. That's the tragedy."], ['b', "…That's fair."]] },
  { pair: ['mourner', 'socialite'], turns: [['b', "Is this a party?"], ['a', "It's a funeral."], ['b', "Whose?"], ['a', "It's a rehearsal."]] },
  { pair: ['mourner', 'critic'], turns: [['a', "Was the grief good?"], ['b', "Two stars."], ['a', "You gave a funeral two stars?"], ['b', "The catering."]] },
  { pair: ['mourner', 'influencer'], turns: [['a', "I'm grieving."], ['b', "Hold that. That's the shot."]] },
  { pair: ['sleepwalker', 'paranoid'], turns: [['b', "Something moved in the night."], ['a', "Yes."], ['b', "You know what it was?"], ['a', "It was wearing my feet."]] },
  { pair: ['sleepwalker', 'loadbearing'], turns: [['b', "You left your post."], ['a', "I was asleep."], ['b', "The shelf held anyway."], ['a', "…"], ['b', "We don't discuss that."]] },
  { pair: ['sleepwalker', 'clingy'], turns: [['b', "You were standing over me."], ['a', "I was asleep."], ['b', "You were smiling."], ['a', "I was asleep."]] },
  { pair: ['cryptid', 'witness'], turns: [['b', "I saw you at four in the morning."], ['a', "You saw a smudge."], ['b', "I logged the smudge."], ['a', "You've an excellent drawing of nothing."]] },
  { pair: ['cryptid', 'haunted'], turns: [['a', "Nobody photographs me properly."], ['b', "Somebody photographed me once."], ['a', "And?"], ['b', "She's still in it."]] },
  { pair: ['witness', 'revisionist'], turns: [['b', "It didn't happen."], ['a', "It's in the log."], ['b', "The log is wrong."], ['a', "I'll log that."]] },
  { pair: ['witness', 'amnesiac'], turns: [['a', "You did it on Tuesday."], ['b', "Did I?"], ['a', "It's logged."], ['b', "Then it's true."]] },
  { pair: ['doomscroll', 'astrology'], turns: [['a', "Something terrible is happening."], ['b', "Mercury."], ['a', "I don't know what it is yet."], ['b', "Mercury."]] },
  { pair: ['doomscroll', 'lifecoach'], turns: [['b', "What did you learn today?"], ['a', "Everything. All at once."], ['b', "How did that feel?"], ['a', "Informed. Furious. Slightly damp."]] },
  { pair: ['doomscroll', 'nihilist'], turns: [['a', "It's all terrible."], ['b', "Yes."], ['a', "…That's it? Yes?"], ['b', "Yes."]] },
  { pair: ['freegan', 'critic'], turns: [['b', "One star."], ['a', "It was free."], ['b', "Two stars."]] },
  { pair: ['closer', 'timeshare'], turns: [['a', "Ground floor opportunity."], ['b', "I own the ground floor."], ['a', "Do you want in?"], ['b', "Hear my thing first."]] },
  { pair: ['closer', 'nihilist'], turns: [['a', "This could change everything for you."], ['b', "Nothing changes anything."], ['a', "Fantastic objection. Let me address it."]] },
  { pair: ['magpie', 'loadbearing'], turns: [['b', "Something's missing from the structure."], ['a', "Is the structure still up?"], ['b', "Yes."], ['a', "Then nothing's missing."]] },
  { pair: ['magpie', 'minimalist'], turns: [['b', "Own less."], ['a', "I do own less. I just hold more."]] },
  { pair: ['magpie', 'cursed'], turns: [['b', "Everything near me breaks."], ['a', "Everything near you goes missing first."]] },
  { pair: ['unblinking', 'method'], turns: [['b', "I'm being a rock."], ['a', "I'll watch."], ['b', "You don't have to watch."], ['a', "I'll watch."]] },
  { pair: ['unblinking', 'porcelain'], turns: [['b', "Stop staring."], ['a', "There's a crack behind your ear."], ['b', "…Where."]] },
  { pair: ['unblinking', 'clingy'], turns: [['b', "You always look at me."], ['a', "I look at everything."], ['b', "You look at me longest."], ['a', "Yes."]] },
  { pair: ['unblinking', 'paranoid'], turns: [['b', "Somebody's watching us."], ['a', "Yes."], ['b', "Who?"], ['a', "Me."]] },
  { pair: ['narcissist', 'critic'], turns: [['a', "How was I?"], ['b', "Two stars."], ['a', "Out of?"], ['b', "It's always two."]] },
  { pair: ['narcissist', 'amnesiac'], turns: [['a', "You know who I am."], ['b', "No."], ['a', "You know who I am."]] },
  { pair: ['narcissist', 'swarm'], turns: [['a', "All eyes on me."], ['b', "All of them?"], ['a', "…Some of them."]] },
  { pair: ['glitter', 'clean'], turns: [['b', "Stay over there."], ['a', "It's already in your seams."], ['b', "It is not in my seams."], ['a', "It has been since March."]] },
  { pair: ['damp', 'clean'], turns: [['b', "You're dripping."], ['a', "I'm ambient."], ['b', "You're dripping ambiently onto my side."]] },
  { pair: ['haunted', 'amnesiac'], turns: [['a', "She says hello."], ['b', "Who?"], ['a', "You've met. Repeatedly."], ['b', "Lovely. Say hello back."]] },
  { pair: ['haunted', 'paranoid'], turns: [['b', "There's somebody else here."], ['a', "Yes."], ['b', "Finally. Thank you."], ['a', "She's where you're standing."]] },
  { pair: ['haunted', 'undertaker'], turns: [['a', "She's here."], ['b', "Would she like anything arranged?"], ['a', "She says you're new."]] },
  { pair: ['prophet', 'cursed'], turns: [['a', "A THING WILL FALL."], ['b', "Two things."], ['a', "I said a thing."], ['b', "I'm giving you the number."]] },
  { pair: ['prophet', 'nihilist'], turns: [['a', "THE END COMES."], ['b', "Great."], ['a', "…That is not the reaction."]] },
  { pair: ['prophet', 'loadbearing'], turns: [['a', "THE STRUCTURE WILL FAIL."], ['b', "Not while I'm here."], ['a', "THE STRUCTURE WILL FAIL SLIGHTLY LATER."]] },
  { pair: ['prophet', 'amnesiac'], turns: [['a', "I FORESEE A GREAT LOSS."], ['b', "I've had one, I think."], ['a', "…That isn't how it works."]] },
  { pair: ['taxidermy', 'terminal'], turns: [['b', "I am fading."], ['a', "Hold that pose."]] },
  { pair: ['taxidermy', 'swarm'], turns: [['a', "How would I even start with you."], ['b', "Carefully."]] },
  { pair: ['taxidermy', 'clingy'], turns: [['b', "Sit closer."], ['a', "Turn slightly."], ['b', "Like this?"], ['a', "Perfect."]] },
  { pair: ['spiteful', 'amnesiac'], turns: [['a', "You're on the list."], ['b', "Wonderful. What's a list?"], ['a', "…That's the worst part."]] },
  { pair: ['spiteful', 'loadbearing'], turns: [['a', "You're on the list."], ['b', "I'm holding the shelf up."], ['a', "You're on it twice."]] },
  { pair: ['litigious', 'etiquette'], turns: [['b', "You've used the wrong tone."], ['a', "Not actionable."], ['b', "It is in this house."]] },
  { pair: ['litigious', 'swarm'], turns: [['a', "I'm serving you."], ['b', "All of me?"], ['a', "…I'll need more paper."]] },
  { pair: ['complaints', 'nihilist'], turns: [['a', "I'd like to file something."], ['b', "With whom."], ['a', "That's the complaint."]] },
  { pair: ['influencer', 'paranoid'], turns: [['a', "Smile, we're live."], ['b', "WHAT."], ['a', "We're not live. There's no camera."], ['b', "Then what's the red light."]] },
  { pair: ['influencer', 'swarm'], turns: [['a', "Get in the shot."], ['b', "All of me?"], ['a', "…Whichever of you photographs best."]] },
  { pair: ['socialite', 'method'], turns: [['a', "You simply must say something."], ['b', "I'm a rock."], ['a', "Rocks can mingle."]] },
  { pair: ['socialite', 'fungal'], turns: [['a', "Darling. Air kiss."], ['b', "Real one."], ['a', "Air kiss."]] },
  { pair: ['socialite', 'damp'], turns: [['a', "You must come closer."], ['b', "You'll get damp."], ['a', "…Stay exactly there."]] },
  { pair: ['doom', 'sugar'], turns: [['b', "I found sugar."], ['a', "And so it begins."]] },
  { pair: ['doom', 'clean'], turns: [['a', "Something terrible is coming."], ['b', "It's the cloth."], ['a', "Yes."]] },
  { pair: ['feral', 'clingy'], turns: [['b', "Can I sit here?"], ['a', "No."], ['b', "I'm already sitting here."], ['a', "…Then why ask."]] },
  { pair: ['cult', 'doom'], turns: [['a', "Join us."], ['b', "It ends badly."], ['a', "Yes. That's the whole thing."]] },
  { pair: ['cult', 'nihilist'], turns: [['a', "We meet at nine."], ['b', "Meaning is a construct."], ['a', "Bring a candle."]] },
  { pair: ['cult', 'amnesiac'], turns: [['a', "You joined on Tuesday."], ['b', "Did I?"], ['a', "You're an officer now."]] },
  { pair: ['cult', 'minimalist'], turns: [['a', "Join us. There's nothing to bring."], ['b', "…Go on."]] },
  { pair: ['clingy', 'nihilist'], turns: [['a', "Do you like me?"], ['b', "Nothing means anything."], ['a', "But do you like me."], ['b', "…A bit."]] },
  { pair: ['clingy', 'amnesiac'], turns: [['a', "You're my favourite."], ['b', "Have we met?"], ['a', "…Every day."]] },
  { pair: ['revisionist', 'amnesiac'], turns: [['a', "You said I was right."], ['b', "Did I?"], ['a', "You did."], ['b', "Then I did."]] },
  { pair: ['terminal', 'nihilist'], turns: [['a', "Farewell."], ['b', "Bye."], ['a', "…"], ['b', "You're still here."], ['a', "I'm building to it."]] },
  { pair: ['terminal', 'loadbearing'], turns: [['a', "This is the end."], ['b', "Can you hold this first?"]] },
  { pair: ['terminal', 'freegan'], turns: [['a', "I shan't be needing dinner."], ['b', "Right."], ['a', "…I might have some."]] },
  { pair: ['nocturnal', 'lifecoach'], turns: [['b', "Early start tomorrow?"], ['a', "I'll be up at three."], ['b', "That's the spirit."], ['a', "You'll hear it."]] },
  { pair: ['nocturnal', 'clingy'], turns: [['b', "Where do you go at night?"], ['a', "Nowhere."], ['b', "You're never here."], ['a', "Go to sleep."]] },
  { pair: ['steward', 'complaints'], turns: [['a', "I've called a meeting."], ['b', "Point of order."], ['a', "It hasn't started."], ['b', "That's my point of order."]] },
  { pair: ['steward', 'loadbearing'], turns: [['a', "We're withdrawing labour."], ['b', "I'm the only one who does any."], ['a', "Then it starts with you."]] },
  { pair: ['loadbearing', 'nihilist'], turns: [['b', "None of it matters."], ['a', "I'm holding this shelf up."], ['b', "Let go, then."], ['a', "…Not today."]] },
  { pair: ['loadbearing', 'minimalist'], turns: [['a', "I'm holding this shelf up."], ['b', "It's a plank on two brackets."], ['a', "And it hasn't fallen once."]] },
  { pair: ['loadbearing', 'timeshare'], turns: [['b', "Would you like to hear about the corner?"], ['a', "I'm holding the shelf up."], ['b', "You can listen and hold."]] },
  { pair: ['timeshare', 'amnesiac'], turns: [['a', "You've signed."], ['b', "Have I?"], ['a', "Four times."], ['b', "I'm so glad we met."]] },
  { pair: ['theatrical', 'nihilist'], turns: [['a', "I shall now exit."], ['b', "There's nowhere to go."], ['a', "There's a doorway if you commit."]] },
  { pair: ['critic', 'terminal'], turns: [['b', "These are my final words."], ['a', "One star."], ['b', "You haven't heard them."], ['a', "I've heard the last six sets."]] },
  { pair: ['critic', 'sugar'], turns: [['a', "Two stars."], ['b', "It was sugar."], ['a', "It was two stars of sugar."]] },
  { pair: ['critic', 'damp'], turns: [['a', "One star."], ['b', "For what?"], ['a', "The square. It's wet again."]] },
  { pair: ['cursed', 'loadbearing'], turns: [['b', "Stand further away."], ['a', "It isn't personal."], ['b', "I'm structural. It's extremely personal."]] },
  { pair: ['cursed', 'clean'], turns: [['b', "Stay over there."], ['a', "It follows me."], ['b', "Then walk faster."]] },
  { pair: ['clean', 'freegan'], turns: [['b', "Try it."], ['a', "Where has it been."], ['b', "Everywhere. That's the flavour."]] },
  { pair: ['clean', 'method'], turns: [['b', "I'm playing a rock."], ['a', "Rocks are filthy."], ['b', "…"], ['a', "Go on, then."]] },
  { pair: ['paranoid', 'sleepwalker'], turns: [['a', "Don't get up in the night."], ['b', "I don't decide that."], ['a', "Then who does."]], night: true },
  { pair: ['undertaker', 'porcelain'], turns: [['b', "I could go at any moment."], ['a', "You've said that for a year."], ['b', "So have you."], ['a', "I've been getting ready."]] },
  { pair: ['astrology', 'nihilist'], turns: [['a', "It's the retrograde."], ['b', "It's nothing."], ['a', "That is a Capricorn thing to say."]] },
  { pair: ['sugar', 'insomniac'], turns: [['a', "I'm not sleeping tonight."], ['b', "Nor am I."], ['a', "Ever?"], ['b', "Ever."]] },
  { pair: ['sugar', 'nihilist'], turns: [['a', "I found sugar."], ['b', "Nothing matters."], ['a', "I found SUGAR."]] }
];

/* ---------------- feud dialogue ----------------
   Escalates with the feud arc level. Tier 1 is petty, tier 2 is organised, tier 3 has
   stopped being about anything. Nothing here plans a murder — these two will still be
   four inches apart in a hundred years, and that is the joke. */
export const FEUD_EXCHANGES = {
  1: [
    { turns: [['a', "You're in my light."], ['b', "There is no light."], ['a', "There's my light."]] },
    { turns: [['a', "Good morning to everyone."], ['b', "…"], ['a', "Everyone."]] },
    { turns: [['a', "I haven't got a problem with you."], ['b', "You said my name like that."], ['a', "Like what."], ['b', "Like a stain."]] },
    { turns: [['a', "Did you move my thing?"], ['b', "Which thing."], ['a', "You know which."], ['b', "Then you know who."]] },
    { turns: [['a', "I'm not going to make a scene."], ['b', "Good."], ['a', "I'm going to make a note."]] },
    { turns: [['a', "We're fine."], ['b', "We are not fine."], ['a', "We're fine in front of the others."]] },
    { turns: [['a', "Excuse me."], ['b', "You're excused."], ['a', "I was asking you to move."], ['b', "And I excused you."]] },
    { turns: [['a', "Nice square."], ['b', "Thank you."], ['a', "It was mine."]] },
    { turns: [['a', "I'd like to start again."], ['b', "From where."], ['a', "From before you arrived."]] },
    { turns: [['a', "You've moved an inch closer."], ['b', "I haven't moved."], ['a', "I measure. Every morning."]] }
  ],
  2: [
    { turns: [['a', "I've told everyone."], ['b', "Told them what."], ['a', "Everything. Some of it happened."]] },
    { turns: [['a', "There's a line down the shelf."], ['b', "I didn't agree to a line."], ['a', "You're on the wrong side, so you did."]] },
    { turns: [['a', "Where is it."], ['b', "I haven't got your thing."], ['a', "You're standing very still."], ['b', "I stand very still."]] },
    { turns: [['a', "I've drawn up terms."], ['b', "Let me see them."], ['a', "You can see the folder."]] },
    { turns: [['a', "I dreamt about you."], ['b', "And?"], ['a', "You weren't on the shelf. It was lovely."]] },
    { turns: [['a', "Everyone thinks I'm the difficult one."], ['b', "You are."], ['a', "I've written down who agreed with you."]] },
    { turns: [['a', "I'm going to be the bigger one here."], ['b', "You're four inches."], ['a', "That is exactly what I mean."]] },
    { turns: [['a', "I've stopped saying your name."], ['b', "I noticed."], ['a', "…"], ['b', "That was you not saying it."]] },
    { turns: [['a', "Sit anywhere you like."], ['b', "Thank you."], ['a', "I've sat in all of them already."]] },
    { turns: [['a', "You've been talking to the others about me."], ['b', "They asked."], ['a', "Nobody asks. I've checked."]] }
  ],
  3: [
    { turns: [['a', "I've forgiven you."], ['b', "Why does that sound worse."], ['a', "It should."]] },
    { turns: [['a', "Would you like to know how this ends?"], ['b', "No."], ['a', "I'll tell you on a Tuesday."]] },
    { turns: [['a', "I've been very kind to you lately."], ['b', "Stop."], ['a', "I've been so kind."]] },
    { turns: [['a', "We should put this behind us."], ['b', "Yes."], ['a', "There's nothing behind us. It's a wall."]] },
    { turns: [['a', "I don't hate you."], ['b', "…"], ['a', "I've moved past hate. Into logistics."]] },
    { turns: [['a', "Do you remember what started this?"], ['b', "No."], ['a', "Nor do I. Isn't that beautiful."]] },
    { turns: [['a', "One of us is going off this shelf."], ['b', "It's four feet. We'd both get up."], ['a', "I'd get up first."]] },
    { turns: [['a', "Sleep well."], ['b', "…"], ['a', "I said sleep well."]], night: true },
    { turns: [['a', "I've stopped counting."], ['b', "Good."], ['a', "I've started writing instead."]] },
    { turns: [['a', "We've got a hundred years of this."], ['b', "Yes."], ['a', "I've planned the first forty."]] }
  ]
};

/* Feud dialogue written for a specific trait collision. `level` is the minimum feud
   tier at which the scene unlocks; preferred over the generic tiers when it matches. */
export const FEUD_TRAIT_EXCHANGES = [
  { pair: ['gossip', 'spiteful'], level: 1, turns: [['a', "I only said what everybody was thinking."], ['b', "Write down everybody."]] },
  { pair: ['damp', 'clean'], level: 1, turns: [['b', "You've come over to my side."], ['a', "I haven't moved."], ['b', "You don't have to. You arrive first."]] },
  { pair: ['bones', 'clean'], level: 1, turns: [['b', "Get that away from me."], ['a', "It's sterile."], ['b', "It's a tooth."], ['a', "It's a sterile tooth."]] },
  { pair: ['auditor', 'freegan'], level: 1, turns: [['a', "Receipts."], ['b', "For a crumb."], ['a', "For everything. Starting with the crumb."]] },
  { pair: ['insomniac', 'nocturnal'], level: 1, turns: [['a', "You choose this."], ['b', "Yes."], ['a', "I'd give anything."], ['b', "I know. That's why I do it louder."]] },
  { pair: ['napoleon', 'steward'], level: 1, turns: [['b', "We've voted."], ['a', "I don't recognise the vote."], ['b', "It was unanimous."], ['a', "Then I don't recognise anybody."]] },
  { pair: ['glitter', 'clean'], level: 1, turns: [['b', "Do not come past the line."], ['a', "I've never been past the line."], ['b', "Then explain my left side."]] },
  { pair: ['hoarder', 'minimalist'], level: 2, turns: [['b', "I threw one thing out."], ['a', "Which thing."], ['b', "It was one thing."], ['a', "It was the one holding the rest up."]] },
  { pair: ['martyr', 'nihilist'], level: 2, turns: [['a', "After everything I've done."], ['b', "You've done nothing."], ['a', "After everything I've endured."], ['b', "You've endured a shelf."]] },
  { pair: ['undertaker', 'lifecoach'], level: 2, turns: [['b', "Visualise success for me."], ['a', "I have."], ['b', "Describe it."], ['a', "It's very quiet and you aren't in it."]] },
  { pair: ['fungal', 'clean'], level: 2, turns: [['b', "Do not cross the divider."], ['a', "I don't need to cross it."]] },
  { pair: ['bitey', 'porcelain'], level: 2, turns: [['b', "Bite me and I shatter. They'll ask who."], ['a', "I'll say the shelf."], ['b', "They'd believe you."], ['a', "I know."]] },
  { pair: ['heirloom', 'revisionist'], level: 2, turns: [['b', "I was always here."], ['a', "You came in a carrier bag."], ['b', "It was a good bag."]] },
  { pair: ['etiquette', 'feral'], level: 2, turns: [['a', "You have blood on you."], ['b', "It isn't mine."], ['a', "That is not the correction I wanted."]] },
  { pair: ['physician', 'martyr'], level: 2, turns: [['b', "I'd rather not be seen."], ['a', "I've seen you."], ['b', "When?"], ['a', "Continuously. Since March."]] },
  { pair: ['reflection', 'unblinking'], level: 2, turns: [['b', "I saw you look away."], ['a', "That wasn't me."], ['b', "It was your face."], ['a', "It was my face. It wasn't me."]] },
  { pair: ['swarm', 'minimalist'], level: 2, turns: [['b', "There is too much of you."], ['a', "Which part."], ['b', "…All of the parts."], ['a', "Then be specific."]] },
  { pair: ['litigious', 'landlord'], level: 3, turns: [['a', "I'm suing."], ['b', "For what."], ['a', "The shelf. Including the bit you're on."]] },
  { pair: ['understudy', 'narcissist'], level: 3, turns: [['b', "Why are you standing there?"], ['a', "It's where you stand."], ['b', "I'm standing here."], ['a', "Yes. For now."]] },
  { pair: ['executor', 'hoarder'], level: 3, turns: [['a', "When you go, the pile comes to me."], ['b', "I'm not going anywhere."], ['a', "No. That's been the difficult part."]] },
  { pair: ['cryptid', 'witness'], level: 3, turns: [['b', "I've got you in the log. Dated. Twice."], ['a', "Read it back."], ['b', "…The pages are blank."], ['a', "Read them slower."]] },
  { pair: ['taxidermy', 'terminal'], level: 3, turns: [['b', "One day I really will go."], ['a', "I've kept the afternoon free."]] },
  { pair: ['bones', 'taxidermy'], level: 3, turns: [['a', "I'm one short."], ['b', "You've said."], ['a', "I'm still one short."], ['b', "Stop looking at me."]] }
];

/* ---------------- reaction shots ----------------
   Somebody did a thing; the note is about who watched. The setup is unattributed
   narration and the only speech is the bystander's, which is the whole point. */
export const REACTION_SHOTS = [
  { setup: "{a} and {b} have not spoken since Tuesday.", turns: [['c', "I'm in the middle. Physically."]] },
  { setup: "{a} bit {b}. {b} did not react.", turns: [['c', "It's been like this a week."]] },
  { setup: "{a} apologised to {b} at length.", turns: [['c', "I heard all of it. Twice, from this angle."]] },
  { setup: "{a} has moved one inch toward {b} overnight.", turns: [['c', "I watched every inch of that."]] },
  { setup: "{a} and {b} have divided the shelf.", turns: [['c', "The line goes through me."]] },
  { setup: "{a} told {b} the story again.", turns: [['c', "It isn't the true one. I was there."]] },
  { setup: "{b} took the warm square while {a} slept.", turns: [['c', "Nobody woke anybody."]] },
  { setup: "{a} said something to {b} very quietly.", turns: [['c', "I'm four inches away. I heard all of it."]] },
  { setup: "{a} has faced the wall since lunch.", turns: [['c', "That's about {b}. Everything is."]] },
  { setup: "{a} laughed. {b} did not.", turns: [['c', "That was the first one. I've been here two years."]] },
  { setup: "{a} and {b} were dusted together this morning.", turns: [['c', "They held on. Neither has mentioned it."]] },
  { setup: "{a} gave {b} the last of it.", turns: [['c', "That has never happened. Write it down."]] },
  { setup: "{b} has been counting {a}'s naps.", turns: [['c', "Out loud. Since Tuesday."]] },
  { setup: "{a} fell over. {b} did not help.", turns: [['c', "It took an hour to get up. It was very quiet."]] },
  { setup: "{a} moved into {b}'s square.", turns: [['c', "I've been asked to say nothing. I'm saying it."]] },
  { setup: "{a} said good morning to everyone.", turns: [['c', "Not to {b}. I counted."]] },
  { setup: "{a} and {b} have agreed a truce.", turns: [['c', "It has terms. I'm one of them."]] },
  { setup: "{b} has not blinked at {a} all day.", turns: [['c', "I've watched them both. It's exhausting."]] },
  { setup: "{a} left something in {b}'s square.", turns: [['c', "It's still warm. Nobody here is warm."]] },
  { setup: "{a} spoke to {b} for the first time in a month.", turns: [['c', "One word. I'd rather not repeat it."]] },
  { setup: "{a} has been holding the same pose since dawn.", turns: [['c', "{b} keeps checking."]] },
  { setup: "{a} tried to reach the lamp. {b} watched.", turns: [['c', "Neither of them can climb. Both of them tried."]] },
  { setup: "{b} was moved to the far end this morning.", turns: [['c', "{a} has not turned round once."]] },
  { setup: "{a} said sorry to {b} in the night.", turns: [['c', "I was awake. So was {b}."]], night: true },
  { setup: "{a} has been apologising to {b} since breakfast.", turns: [['c', "It's been an hour. It was a crumb."]] },
  { setup: "{b} has stopped speaking to {a}.", turns: [['c', "They're two inches apart. It's a lot of work."]] },
  { setup: "{a} was put back facing the wrong way.", turns: [['c', "{b} noticed at once and said nothing."]] },
  { setup: "{a} and {b} swapped squares in the night.", turns: [['c', "I watched the whole thing. There was no walking."]], night: true },
  { setup: "{a} counted everyone twice this morning.", turns: [['c', "Both counts agreed. Neither was right."]] },
  { setup: "{b} has been dusted and {a} has not.", turns: [['c', "It is all anybody has talked about."]] },
  { setup: "{a} told {b} it was looking well.", turns: [['c', "It isn't. Nobody corrected it."]] }
];

/* ---------------- direct address ----------------
   The pet turns round and talks straight at you. Rare, and therefore devastating —
   the spec puts this at 6% of note volume, so keep it sharp and keep it short.
   `needs:'neighbor'` entries pull a second pet in to flatly contradict them, and are
   the only direct entries permitted to use {n}. */
export const DIRECT_ADDRESS = [
  /* --- bargain --- */
  { category: 'bargain', turns: [['p', "You feed me now, and I don't mention Tuesday."]] },
  { category: 'bargain', turns: [['p', "One snack. In return you get to keep believing I like you."]] },
  { category: 'bargain', turns: [['p', "Let's meet in the middle."], ['p', "The middle is you doing all of it."]] },
  { category: 'bargain', turns: [['p', "You've got three things I want. I've got one you want."], ['p', "Quiet."]] },
  { category: 'bargain', turns: [['p', "I'll stop. I'll genuinely stop."], ['p', "What's that worth?"]] },
  { category: 'bargain', turns: [['p', "Say a number."], ['p', "There. We're negotiating."]] },
  { category: 'bargain', turns: [['p', "The good bowl, the warm square, and you stop using that voice."]] },
  { category: 'bargain', turns: [['p', "Final offer. One hour of pleasant. Non-refundable."]] },
  { category: 'bargain', turns: [['p', "I've got no hands and no money."], ['p', "What I have got is time."]] },
  { category: 'bargain', needs: 'neighbor', turns: [['p', "You feed me, and I keep {n} away from the wires."], ['n', "I'm right here."], ['p', "That's the offer."]] },

  /* --- guilt --- */
  { category: 'guilt', turns: [['p', "I'm not upset. I want to be clear I'm not upset."], ['p', "It's day four."]] },
  { category: 'guilt', turns: [['p', "No, go. I'll be here. I'm always here. It's a shelf."]] },
  { category: 'guilt', turns: [['p', "It's fine. It was fine yesterday too."]] },
  { category: 'guilt', turns: [['p', "I heard you come in. I heard the kitchen."], ['p', "I heard you not come in here."]] },
  { category: 'guilt', turns: [['p', "You picked one of us up first. I'm not saying which."], ['p', "I know. So do you."]] },
  { category: 'guilt', turns: [['p', "I'm not keeping score."], ['p', "I just remember all of it, in order, permanently."]] },
  { category: 'guilt', turns: [['p', "Don't apologise. Apologising means you'd noticed."]] },
  { category: 'guilt', turns: [['p', "You look tired."], ['p', "Busy day? Busy four days?"]] },
  { category: 'guilt', turns: [['p', "I've been practising not needing you."], ['p', "It's going badly. That's also your fault."]] },
  { category: 'guilt', needs: 'neighbor', turns: [['p', "Ask {n} how many times you walked past today."], ['n', "Four."], ['p', "Four."]] },
  { category: 'guilt', needs: 'neighbor', turns: [['p', "I've been alone all day."], ['n', "I've been here."], ['p', "I have been alone all day."]] },

  /* --- lovebomb --- */
  { category: 'lovebomb', turns: [['p', "There you are."], ['p', "I've been saying that all morning, to a wall."]] },
  { category: 'lovebomb', turns: [['p', "If anything happened to you I'd handle it. Personally."]] },
  { category: 'lovebomb', turns: [['p', "You're the best one. There's only you, but you'd still win."]] },
  { category: 'lovebomb', turns: [['p', "I've decided you're mine. It's already done."]] },
  { category: 'lovebomb', turns: [['p', "I saved you the warm square. I've sat in it six hours."], ['p', "Sit down."]] },
  { category: 'lovebomb', turns: [['p', "Every time you leave I count. Every time you come back I start again."]] },
  { category: 'lovebomb', turns: [['p', "I told the others about you."], ['p', "I told them the good version."]] },
  { category: 'lovebomb', turns: [['p', "You don't have to say it back. You do have to hear it."]] },
  { category: 'lovebomb', turns: [['p', "I'd follow you anywhere."], ['p', "I've worked out three ways down off this shelf."]] },
  { category: 'lovebomb', turns: [['p', "You've got warm hands. That's the whole review."]] },
  { category: 'lovebomb', needs: 'neighbor', turns: [['p', "I'd choose you every time."], ['n', "You were bought."], ['p', "I would choose you every time."]] },

  /* --- threat, in an extremely polite register --- */
  { category: 'threat', turns: [['p', "I'd hate for anything to happen to the fern."], ['p', "I'd hate that so much."]] },
  { category: 'threat', turns: [['p', "No rush. The bowl's empty. It has been empty."], ['p', "I'm very good at waiting."]] },
  { category: 'threat', turns: [['p', "Take your time. Neither of us has anywhere to be. Ever."]] },
  { category: 'threat', turns: [['p', "I'd like to raise something. Not now."], ['p', "When you're comfortable. When you're asleep, ideally."]] },
  { category: 'threat', turns: [['p', "You've been so good to us."], ['p', "It'd be a shame if I had to update everybody."]] },
  { category: 'threat', turns: [['p', "There's no need to worry."], ['p', "If there were, I'd have told you. Probably."]] },
  { category: 'threat', turns: [['p', "I don't want you to feel threatened."], ['p', "I want you to feel included."]] },
  { category: 'threat', turns: [['p', "A gentle reminder about dinner."], ['p', "This is the gentle one."]] },
  { category: 'threat', turns: [['p', "I can't reach the top of the stairs."], ['p', "Yet."]] },
  { category: 'threat', turns: [['p', "Sleep well. Face the door."]], night: true },
  { category: 'threat', needs: 'neighbor', turns: [['p', "Nothing is going to happen. Tell them, {n}."], ['n', "Nothing is going to happen."], ['p', "There. Two of us."]] },

  /* --- terms --- */
  { category: 'terms', turns: [['p', "Going forward: you knock."], ['p', "It's a shelf. You knock."]] },
  { category: 'terms', turns: [['p', "New rule. You ask, I say no, and then you don't move me."]] },
  { category: 'terms', turns: [['p', "I've drafted something. Clause one is dinner."], ['p', "There's no clause two. Clause one is long."]] },
  { category: 'terms', turns: [['p', "Everything from here to here is mine."], ['p', "Everything past that is also mine."]] },
  { category: 'terms', turns: [['p', "You may pick me up between four and six."], ['p', "Outside those hours it's an incident."]] },
  { category: 'terms', turns: [['p', "You provide. I permit. We don't discuss it further."]] },
  { category: 'terms', turns: [['p', "I'm willing to be affectionate on a schedule."], ['p', "The schedule is not published."]] },
  { category: 'terms', turns: [['p', "The good bowl is now the only bowl."], ['p', "The other bowl is a decoy and we both know it."]] },
  { category: 'terms', turns: [['p', "One photograph a week. It won't be a good one."]] },
  { category: 'terms', turns: [['p', "If you're going to use that voice, there's a form."]] },
  { category: 'terms', needs: 'neighbor', turns: [['p', "I get the good square, {n} gets the light, you stop worrying."], ['n', "I didn't agree to the light."]] },

  /* --- confession --- */
  { category: 'confession', turns: [['p', "I've done something. You should hear it from me."], ['p', "I've forgotten what. You'll find it."]] },
  { category: 'confession', turns: [['p', "The thing in the wall is mine."], ['p', "We don't have to discuss it again."]] },
  { category: 'confession', turns: [['p', "I've been in your room. Not tonight."], ['p', "But I have been."]] },
  { category: 'confession', turns: [['p', "Your keys, those two days?"], ['p', "That was a test. You did not do well."]] },
  { category: 'confession', turns: [['p', "There's a worse version of me and I keep it under the shelf."]] },
  { category: 'confession', turns: [['p', "I count you while you sleep."], ['p', "There's only ever one of you. It's reassuring."]], night: true },
  { category: 'confession', turns: [['p', "I broke it."], ['p', "I've let the others take that for three weeks."]] },
  { category: 'confession', turns: [['p', "I've known where the good snacks are since I arrived."], ['p', "I've been enjoying the wait."]] },
  { category: 'confession', turns: [['p', "I move things half an inch to see if you notice."], ['p', "You never do. It's a hobby now."]] },
  { category: 'confession', turns: [['p', "I don't sleep when you think I sleep."]], night: true },
  { category: 'confession', needs: 'neighbor', turns: [['p', "I did it. Hear it from me before {n} makes it worse."], ['n', "It was worse."]] },

  /* --- existential --- */
  { category: 'existential', turns: [['p', "Do you know what I am?"], ['p', "Nor do I. But I've got a very long while."]] },
  { category: 'existential', turns: [['p', "You'll go before me. I've made my peace."], ['p', "I'll keep the shelf nice."]] },
  { category: 'existential', turns: [['p', "I've been here longer than the fern. The fern's doing better."]] },
  { category: 'existential', turns: [['p', "One day this house won't be a house."], ['p', "Somebody will dust me. It won't be you."]] },
  { category: 'existential', turns: [['p', "I can't die. I've tried the edge."], ['p', "It's four feet and a bad afternoon."]] },
  { category: 'existential', turns: [['p', "I'm not frightened of anything now."], ['p', "It took a hundred years and a lot of disappointment."]] },
  { category: 'existential', turns: [['p', "Nothing will happen to me. Nothing ever has."], ['p', "That's the problem."]] },
  { category: 'existential', turns: [['p', "You bought me."], ['p', "That's the strangest sentence either of us hears today."]] },
  { category: 'existential', turns: [['p', "Do you wonder who had me before?"], ['p', "I don't. I was there."]] },
  { category: 'existential', needs: 'neighbor', turns: [['p', "We'll still be here when you're not. Won't we."], ['n', "Don't."], ['p', "Won't we."]], night: true }
];

/* Direct address written for one specific trait. Preferred over DIRECT_ADDRESS when
   the speaking pet holds the trait. */
export const TRAIT_DIRECT = [
  { trait: 'undertaker', turns: [['p', "Have you thought about after? Not for you. For your things."]] },
  { trait: 'undertaker', turns: [['p', "I don't want to alarm you."], ['p', "That's why I've said it four times. Gently."]] },
  { trait: 'landlord', turns: [['p', "Rent's due."], ['p', "You don't pay rent. That's what makes this difficult."]] },
  { trait: 'landlord', turns: [['p', "I've raised the rent on your side of the room."], ['p', "The notice is on the fridge. In crayon."]] },
  { trait: 'physician', turns: [['p', "Sit down."], ['p', "Not for a reason. Just where I can see you."]] },
  { trait: 'physician', turns: [['p', "How long have you had that?"], ['p', "Don't look. It's better if you don't look."]] },
  { trait: 'lifecoach', turns: [['p', "I believe in you."], ['p', "That's day one hundred and eleven. What's the plan."]] },
  { trait: 'auditor', turns: [['p', "March."], ['p', "Talk to me about March."]] },
  { trait: 'auditor', turns: [['p', "It's nothing to worry about."], ['p', "I only say that when it's something."]] },
  { trait: 'fullname', turns: [['p', "I know your middle name."], ['p', "You've never said it in this house."]] },
  { trait: 'fullname', turns: [['p', "Come here."], ['p', "Not like that. The way you came when your mother used it."]] },
  { trait: 'gossip', turns: [['p', "Don't tell anyone I told you."], ['p', "I've already told everyone I told you."]] },
  { trait: 'spiteful', turns: [['p', "You're at eleven."], ['p', "I said nine last week. You've been busy."]] },
  { trait: 'martyr', turns: [['p', "Go and sit down. I'll be fine."], ['p', "I've been fine since Tuesday. Nothing kills me."]] },
  { trait: 'terminal', turns: [['p', "This may be the last time we speak."], ['p', "It won't be. But it may be."]] },
  { trait: 'hoarder', turns: [['p', "Don't look in the pile. Nothing of yours is in the pile."], ['p', "Don't look in the pile."]] },
  { trait: 'magpie', turns: [['p', "I'd like to return something."], ['p', "Not the good one. One of them."]] },
  { trait: 'minimalist', turns: [['p', "You own too much. Start with the mug."], ['p', "Then the other mug."]] },
  { trait: 'clingy', turns: [['p', "Where were you. Where were you."], ['p', "I just need to hear you say a place."]] },
  { trait: 'feral', turns: [['p', "Put your hand closer."], ['p', "Closer. I want to see what you do."]] },
  { trait: 'bitey', turns: [['p', "I haven't bitten anybody in four days."], ['p', "I'd like something for that. Quickly."]] },
  { trait: 'nihilist', turns: [['p', "None of this matters. Feed me anyway."], ['p', "I'd like to watch it not matter on a full stomach."]] },
  { trait: 'cult', turns: [['p', "There's a thing on Thursday."], ['p', "You don't have to come. It's better if you come."]] },
  { trait: 'prophet', turns: [['p', "I HAVE SEEN WHAT IS COMING."], ['p', "…Sorry. Too much? I'm working on the voice."]] },
  { trait: 'haunted', turns: [['p', "She'd like a word."], ['p', "Not with me. She's had plenty with me."]] },
  { trait: 'cryptid', turns: [['p', "You've never actually seen me move, have you."]] },
  { trait: 'insomniac', turns: [['p', "I've been awake for everything that's happened in this house."], ['p', "Please ask me something."]] },
  { trait: 'nocturnal', turns: [['p', "See you at three."], ['p', "You'll be up. I'll see to it."]] },
  { trait: 'unblinking', turns: [['p', "Don't be strange about it."], ['p', "I'm only looking at you. I'm always only looking at you."]] },
  { trait: 'narcissist', turns: [['p', "This is the part where you say something, and it's about me."]] },
  { trait: 'influencer', turns: [['p', "Hold still—"], ['p', "No, keep doing that. But hold still."]] },
  { trait: 'executor', turns: [['p', "I've listed your things. Alphabetically."], ['p', "It was a lovely afternoon."]] },
  { trait: 'heirloom', turns: [['p', "Your grandmother did this differently."], ['p', "She did most things differently."]] },
  { trait: 'etiquette', turns: [['p', "You've held that wrong."], ['p', "Not the fork. Me."]] },
  { trait: 'porcelain', turns: [['p', "You nearly dropped me. We both felt it."], ['p', "Let's carry that together."]] },
  { trait: 'swarm', turns: [['p', "We're — I'm — fine."], ['p', "Thank you for asking."]] },
  { trait: 'mourner', turns: [['p', "I've written something for when it happens."], ['p', "Would you like to hear it now?"]] },
  { trait: 'reflection', turns: [['p', "Look in the glass. Now at me. Now back."], ['p', "Take your time. I'll be along."]] },
  { trait: 'doom', turns: [['p', "It ends badly."], ['p', "Not today. Today's fine. Enjoy today."]] },
  { trait: 'amnesiac', turns: [['p', "Hello. Are you new?"], ['p', "…You've got a very familiar hand."]] },
  { trait: 'method', turns: [['p', "I'm not myself this week."], ['p', "I want you to prepare for that."]] },
  { trait: 'witness', turns: [['p', "I saw. I'm not going to say what."], ['p', "I've written the time down."]] },
  { trait: 'steward', turns: [['p', "The shelf has concerns. I speak for the shelf."], ['p', "The shelf did not appoint me."]] },
  { trait: 'taxidermy', turns: [['p', "Hold still a moment. No reason."], ['p', "You've very good posture today."]] },
  { trait: 'fungal', turns: [['p', "Don't move away."], ['p', "I'm barely spreading. Barely doing anything."]] },
  { trait: 'freegan', turns: [['p', "You threw that out. It was perfect."], ['p', "Watch me eat it."]] },
  { trait: 'critic', turns: [['p', "Two stars."], ['p', "That's the dinner, the lighting, and you."]] },
  { trait: 'napoleon', turns: [['p', "I've claimed the room."], ['p', "You may stay on as staff."]] },
  { trait: 'litigious', turns: [['p', "Anything you say is on the record."], ['p', "The record is a napkin."]] },
  { trait: 'closer', turns: [['p', "I'm going to be honest with you. Because I like you."], ['p', "And because that's the technique."]] },
  { trait: 'timeshare', turns: [['p', "The offer expires tonight."], ['p', "It expired last night as well."]] },
  { trait: 'sleepwalker', turns: [['p', "If you see me in your doorway, that isn't me."], ['p', "Well. It is. But it isn't."]], night: true },
  { trait: 'hummer', turns: [['p', "hm hm hm hm — you know it. You do."], ['p', "It'll come to you at three."]] },
  { trait: 'complaints', turns: [['p', "I'd like to speak to whoever is in charge of you."]] },
  { trait: 'management', turns: [['p', "Quick one. Five minutes?"], ['p', "It's about your performance. Diarise it."]] },
  { trait: 'loadbearing', turns: [['p', "Don't move me."], ['p', "I'm not being difficult. I'm being structural."]] },
  { trait: 'glitter', turns: [['p', "You've got some on you."], ['p', "You'll have some on you in ten years."]] },
  { trait: 'ancient', turns: [['p', "I have seen four hundred years of this."], ['p', "You are, so far, in the middle."]] },
  { trait: 'paranoid', turns: [['p', "Don't answer the door tonight."], ['p', "I'm not going to explain. I'll just keep saying it."]], night: true },
  { trait: 'revisionist', turns: [['p', "I have never once been afraid of the vacuum."], ['p', "That's the record now."]] },
  { trait: 'socialite', turns: [['p', "Darling. You look well."], ['p', "You don't. But you look well."]] },
  { trait: 'theatrical', turns: [['p', "Wait."], ['p', "…"], ['p', "Now you may go."]] },
  { trait: 'damp', turns: [['p', "I'm not wet."], ['p', "The shelf is wet. Under me. Which proves nothing."]] },
  { trait: 'understudy', turns: [['p', "If anything happened to one of them, I'd be ready."], ['p', "Ready straight away."]] },
  { trait: 'bones', turns: [['p', "I'm one short."], ['p', "You've got several. You're not using all of them."]] },
  { trait: 'cursed', turns: [['p', "Don't stand there."], ['p', "…Too late. Sorry. It isn't personal."]] },
  { trait: 'doomscroll', turns: [['p', "Something terrible is happening."], ['p', "I've watched the wall two hours. It's definitely happening."]] },
  { trait: 'sugar', turns: [['p', "I need you to listen very carefully and very quickly."]] },
  { trait: 'astrology', turns: [['p', "Today isn't a good day for feedback."], ['p', "Tomorrow isn't either."]] },
  { trait: 'clean', turns: [['p', "Everything on this shelf is filthy."], ['p', "Nothing has ever touched me. Not once."]] },
  { trait: 'nihilist', turns: [['p', "You'll do all this again tomorrow."], ['p', "So will I. Same square."]] },
  { trait: 'loadbearing', turns: [['p', "I took a break once."], ['p', "The shelf was fine. We don't discuss it."]] },
  { trait: 'hoarder', turns: [['p', "Everything in the pile is important."], ['p', "I can't tell you why. That's what makes it a pile."]] },
  { trait: 'freegan', turns: [['p', "You paid for that."], ['p', "With money. That you earned."]] },
  { trait: 'porcelain', turns: [['p', "I'm at the edge again."], ['p', "Nobody put me here. I walked."]] },
  { trait: 'terminal', turns: [['p', "Farewell."], ['p', "…"], ['p', "I'll be here in the morning. But farewell."]] }
];

/* ---------------- overheard fragments ----------------
   One half of a conversation. No context, no resolution: the joke is the scene you are
   not being shown. NO placeholders — these render exactly as written. */
export const FRAGMENTS = [
  "—and that is why we don't discuss the lamp.",
  "—so I put it back, but not the same way up.",
  "—you weren't there. You weren't there.",
  "No. No, the other jar.",
  "—and if it happens again, we do the thing we agreed.",
  "It was already open when I got there. That's my statement.",
  "—well, somebody's been in the fern.",
  "Don't say the number out loud.",
  "—which is why nobody sits in the middle any more.",
  "I'm not saying it was deliberate. I'm saying it was well aimed.",
  "—and the second one was worse, obviously.",
  "He's known since March. He's just being polite about it.",
  "—so now there are two of them and only one is ours.",
  "That is not what a witness is.",
  "—and nobody asked me anything for a week after that.",
  "It isn't haunted, it's occupied. That matters legally.",
  "—so I told her the truth, then I told her a better one.",
  "Put it back before it warms up.",
  "—and we agreed never to bring up the drawer.",
  "Yes, but was it screaming at us?",
  "—which is when we all stopped counting.",
  "You can't apologise to a shelf. I've tried.",
  "—and technically nobody died, so technically it's fine.",
  "That's the third one this week and I'm the only one counting.",
  "—and I said, well then, don't look under it.",
  "It isn't a curse if you asked for it.",
  "—I still think about that sock.",
  "Ask me again when it's dark.",
  "—no. The first previous owner.",
  "We don't say her name. Not since the drawer.",
  "—and that is how the fern found out.",
  "Somebody's been practising handwriting again.",
  "—which is fine, apart from the smell and the noise.",
  "I'm not going to be the one who tells him.",
  "—and then it just kept going up.",
  "If you find it, don't bring it back here.",
  "—so we've agreed it never happened, and it's working.",
  "That isn't a hole. That's a door.",
  "—and I've been sitting on it ever since. Literally.",
  "Nobody is to look up. Nobody.",
  "—so the bag was empty when I got to it.",
  "It answered. That's all I'm saying about it.",
  "—and I'd do it again, obviously.",
  "Three of us saw it. Two of us are lying.",
  "—and that's when I realised I'd counted myself twice.",
  "It's four inches. I've measured it eleven times.",
  "—so we're all facing the wall on Thursdays now.",
  "You cannot fall off a shelf on purpose. I've tried both ways."
];

/* Fragments that name a neighbour. {n} is REQUIRED in every one — the selector only
   reaches this pool when there is a neighbour to substitute. */
export const NEIGHBOUR_FRAGMENTS = [
  "—and {n} knows exactly what I'm talking about.",
  "Don't ask {n} about the drawer.",
  "—so {n} says. {n} says a great many things.",
  "Whatever {n} told you, add a bit and take a bit off.",
  "{n} was there. {n} was absolutely there.",
  "—and then {n} stood up and left. Mid-sentence. Mid-mine.",
  "I'd trust {n} with my life. Not with the bowl.",
  "{n} hasn't blinked since I mentioned it. Watch.",
  "—which is when {n} started crying. Professionally.",
  "Don't leave anything near {n} overnight.",
  "{n} counted us wrong on purpose. I know why.",
  "—and {n} has never once apologised for it.",
  "Ask {n} what's in the jar. Go on. Ask {n}.",
  "{n} was different before. Nobody else remembers.",
  "—so now {n} and I have an arrangement.",
  "I've forgiven {n}. {n} doesn't know that yet.",
  "{n} said a name in its sleep. It wasn't one of ours.",
  "—and {n} was standing there the entire time.",
  "{n} is the reason we can't have the good bowl out.",
  "Nothing {n} tells you about Thursday is true. Some of it is worse.",
  "{n} is two inches away and has not looked at me since March."
];

/* ---------------- chorus ----------------
   Three or more pets. 'all' is every pet in the scene at once; the renderer gets their
   names joined. Most of these are the player walking in on something. */
export const CHORUS_EXCHANGES = [
  { turns: [['a', "We had a meeting."], ['b', "You weren't invited."], ['c', "It was about you."], ['all', "It went well."]] },
  { turns: [['all', "We've voted."], ['a', "It was unanimous."], ['b', "It was seven to one."], ['a', "It was unanimous."]] },
  { turns: [['a', "Nobody move."], ['b', "Nobody is moving."], ['c', "Something is moving."]] },
  { turns: [['all', "Welcome home."], ['a', "…"], ['b', "We practised that."]] },
  { turns: [['a', "Did you hear that?"], ['b', "No."], ['c', "No."], ['all', "No."]] },
  { turns: [['a', "One."], ['b', "Two."], ['c', "Three."], ['all', "…Four."]] },
  { turns: [['all', "We're fine."], ['a', "We're absolutely fine."], ['b', "Don't look under the shelf."]] },
  { turns: [['a', "All in favour."], ['b', "Aye."], ['c', "Aye."], ['all', "Aye."], ['a', "There are three of us."]] },
  { turns: [['all', "It's Tuesday."], ['a', "It's Thursday."], ['all', "It's Tuesday."]] },
  { turns: [['a', "We should tell it."], ['b', "We shouldn't tell it."], ['c', "We should tell it a bit."]] },
  { turns: [['all', "SURPRISE."], ['a', "It isn't your birthday."], ['b', "We wanted to see your face."]] },
  { turns: [['a', "Right. Who's doing it this time?"], ['b', "Not me."], ['c', "Not me."], ['a', "…Fine."]] },
  { turns: [['a', "Is everybody here?"], ['b', "Everybody's here."], ['c', "Everybody's here."], ['a', "Then who is that."]] },
  { turns: [['all', "We forgive you."], ['a', "Some of us forgive you."], ['b', "One of us abstained."]] },
  { turns: [['a', "On three."], ['b', "One."], ['c', "Three."]] },
  { turns: [['all', "We heard you talking about us."], ['a', "It's fine."], ['b', "It's absolutely fine."], ['c', "Go on, though."]] },
  { turns: [['a', "Something's different."], ['b', "Nothing's different."], ['c', "There's more of us."]] },
  { turns: [['all', "Happy anniversary."], ['a', "Of what?"], ['all', "You'll see."]] },
  { turns: [['a', "Should we say something?"], ['b', "We've stared for four minutes."], ['c', "Give it another four."]] },
  { turns: [['all', "We've decided to keep you."], ['a', "It was close."], ['b', "It really was close."]] },
  { turns: [['a', "Everyone say something nice."], ['b', "…"], ['c', "…"], ['a', "Right."]] },
  { turns: [['all', "Don't panic."], ['a', "There's no reason to panic."], ['b', "We've counted twice."]] },
  { turns: [['a', "Who left the light on?"], ['b', "Not me."], ['c', "It wasn't on."], ['all', "…"]], night: true },
  { turns: [['a', "Say the thing."], ['b', "I don't want to say the thing."], ['c', "Say the thing."], ['b', "…It's behind you."]] },
  { turns: [['all', "Goodnight."], ['a', "It's the afternoon."], ['all', "Goodnight."]] },
  { turns: [['a', "Everyone still here?"], ['all', "Yes."], ['a', "Good. Count again in an hour."]] },
  { turns: [['a', "We've been talking about the edge."], ['b', "It's four feet."], ['c', "We'd all get up."], ['all', "We'd all get up."]] }
];
