export const FRAMES = [
  {id:'wood',name:'Found timber',at:0,line:'It was a tree. It has adjusted poorly.'},
  {id:'brass',name:'Brass exhibition',at:6,line:'Museum standards. Pawn-shop provenance.'},
  {id:'moon',name:'Moon cabinet',at:16,line:'For objects that look different when you blink.'},
  {id:'velvet',name:'Velvet mausoleum',at:32,line:'Nothing has died. The velvet is optimistic.'}
];
export const RELICS = [
  {id:'market:0',name:'A receipt for questionable judgement',shape:'receipt',line:'All sales final. Several opinions provisional.'},
  {id:'market:1',name:'The silver shopping thimble',shape:'medal',line:'Awarded for bringing home objects that actually go together. A rare household event.'},
  {id:'market:2',name:'The crown of suspicious bargains',shape:'crown',line:'The market has recognised your talent. The vendors have raised your rent.'},
  {id:'drawer:0',name:'A sock with diplomatic immunity',shape:'sock',line:'The left sock is still being questioned.'},
  {id:'drawer:1',name:'The missing button’s alibi',shape:'button',line:'It was sewn up. Suspiciously neatly.'},
  {id:'drawer:2',name:'A medal for being lost',shape:'medal',line:'First place. Location unknown.'},
  {id:'fridge:0',name:'A prehistoric pea',shape:'pea',line:'It has outlived three diets and a marriage.'},
  {id:'fridge:1',name:'The spoon of last resort',shape:'spoon',line:'Too small for soup. Exactly right for revenge.'},
  {id:'fridge:2',name:'A refrigerator sun',shape:'sun',line:'They brought back the light. The butter is furious.'},
  {id:'cupboard:0',name:'A thimble full of weather',shape:'rain',line:'Forecast: localised unpleasantness.'},
  {id:'cupboard:1',name:'A formally retired tooth',shape:'tooth',line:'No longer biting. Advising in a consultancy role.'},
  {id:'cupboard:2',name:'The key to a smaller problem',shape:'key',line:'Opens something. Nobody has admitted what.'}
];

// The market is a small planning game. Every price and future stall is visible;
// a good basket comes from combining requests, not guessing concealed odds.
export const MARKET_TAGS = {cozy:'Comfort',odd:'Strange',bright:'Shiny',snack:'Edible'};
export const MARKET_ITEMS = [
 {id:'tea-sock',name:'A tea cosy for one toe',shape:'sock',cost:2,charm:2,tags:['cozy'],line:'The matching nine were sold separately. So was the owner.'},
 {id:'jam-button',name:'A jam-filled button',shape:'button',cost:3,charm:3,tags:['bright','snack'],line:'Fastens your coat. Slowly attracts a different coat.'},
 {id:'haunted-pea',name:'The haunted pea',shape:'pea',cost:3,charm:3,tags:['odd','snack'],line:'Contains the soul of a man who sent soup back. He can taste the soup from here.'},
 {id:'warm-moon',name:'A second-hand moon',shape:'moon',cost:4,charm:4,tags:['cozy','bright'],line:'Only used at night. One careful werewolf.'},
 {id:'tooth-pillow',name:'A tooth’s retirement pillow',shape:'tooth',cost:3,charm:3,tags:['cozy','odd'],line:'The tooth still expects something under it each morning. The fairy stopped coming after the finger.'},
 {id:'sugar-star',name:'A sugar constellation',shape:'sun',cost:4,charm:4,tags:['bright','snack'],line:'Each star is a dead relative. The packet says five a day.'},
 {id:'bedtime-biscuit',name:'A bedtime biscuit',shape:'medal',cost:2,charm:2,tags:['cozy','snack'],line:'Reads you a story. Becomes progressively harder to hear as you eat it.'},
 {id:'echo-jar',name:'A jar of last words',shape:'echo',cost:2,charm:2,tags:['odd'],line:'Mostly “watch this.” The deluxe jar contains “I know what I’m doing.”'},
 {id:'brass-sun',name:'The brass breakfast sun',shape:'sun',cost:3,charm:4,tags:['bright'],line:'Rises whenever somebody drops the toaster.'},
 {id:'rain-scarf',name:'The professional mourner’s scarf',shape:'rain',cost:4,charm:4,tags:['cozy','odd'],line:'Weeps on contact. Has attended seventeen funerals and cared at none of them.'},
 {id:'mirror-spoon',name:'A spoon that flatters you',shape:'spoon',cost:3,charm:3,tags:['bright','odd'],line:'“You haven’t aged a day.” It said that to the previous owner for six weeks before anyone checked.'},
 {id:'crumb-crown',name:'The shortbread crown',shape:'crown',cost:4,charm:4,tags:['bright','snack'],line:'Uneasy lies the head that smells this much like butter.'},
 {id:'pocket-rug',name:'The pocket-sized rug',shape:'sock',cost:2,charm:3,tags:['cozy'],line:'Excellent at hiding stains. The salesman refuses to turn it over.'},
 {id:'tiny-prophecy',name:'Tomorrow’s shopping receipt',shape:'receipt',cost:2,charm:3,tags:['odd'],line:'One shovel. One apology card. The vendor recommends buying the shovel first.'},
 {id:'glow-thread',name:'A spool of borrowed daylight',shape:'needle',cost:3,charm:3,tags:['bright','cozy'],line:'Removed from a tunnel just as somebody was approaching it.'},
 {id:'opera-raisin',name:'A raisin with formal training',shape:'pea',cost:3,charm:3,tags:['snack','odd'],line:'Sings for its supper. Is increasingly concerned about the wording.'},
 {id:'comfort-crumbs',name:'Emergency comfort crumbs',shape:'medal',cost:2,charm:2,tags:['snack','cozy'],line:'Left over from a wake. The deceased would have wanted them. They were quite greedy.'},
 {id:'button-comet',name:'A comet on a safety pin',shape:'button',cost:4,charm:4,tags:['bright','odd'],line:'A mass extinction you can wear to dinner. The smaller guests have asked you to take it off.'}
];
export const MARKET_REQUESTS = [
 {id:'tea',name:'Tea with the recently deceased',tags:['cozy','odd'],line:'Bring comfort and something strange. They keep asking what happened to their good china.'},
 {id:'midnight',name:'A midnight feast',tags:['snack','snack'],line:'Two edible objects. Calling the napkin a salad will not count.'},
 {id:'museum',name:'A deeply suspicious museum',tags:['bright','odd'],line:'One shiny exhibit and one inexplicable exhibit. The curator can be both.'},
 {id:'nest',name:'A nest with standards',tags:['cozy','cozy'],line:'Two comforts. It has started calling the empty nest a coffin, then looking at you.'},
 {id:'gala',name:'The crumb gala',tags:['bright','snack'],line:'Something to admire and something to eat. The guests need clear instructions.'},
 {id:'spectacle',name:'A very small coronation',tags:['bright','bright'],line:'Two shiny objects. The previous monarch is under the rug, which is why we need the distraction.'},
 {id:'sleepover',name:'A respectable sleepover',tags:['cozy','snack'],line:'Comfort and a snack. Bring your own pillow. The host has been using guests as stuffing.'},
 {id:'haunting',name:'A haunting with refreshments',tags:['odd','snack'],line:'Something strange and something edible. The ghost has been dead nine years and is still a terrible guest.'},
 {id:'cabinet',name:'A cabinet of bad ideas',tags:['odd','odd'],line:'Two separate peculiarities. One large peculiarity is still only one.'}
];
export const MARKET_STALLS = [
 {name:'The Sock Exchange',line:'“Pairs cost extra. Nobody here died together.”'},
 {name:'Mother Needle’s Almost Antiques',line:'“Old enough to be valuable. Too young to testify.”'},
 {name:'The Pea’s Personal Effects',line:'“Everything must go. The fridge has changed the locks.”'},
 {name:'The Unlicensed Moon Shop',line:'“That dark patch? Previous owner. We tried bleach.”'},
 {name:'Miss Afterbell’s Quiet Sale',line:'Miss Afterbell is underneath the stall, insisting this is not what she meant by clearing her things out.'},
 {name:'Last Chance, Probably',line:'“Everything must go. They’re exhuming the landlord at six.”'}
];
export const GEAR = [{id:'thread',name:'Thread & safety pin',hint:'Bridges gaps; rescues things without a speech.'},{id:'lantern',name:'Pocket lantern',hint:'Reveals small print, warm routes, and things pretending to be furniture.'},{id:'biscuit',name:'Emergency biscuit',hint:'A bribe, a distraction, or a last-minute relative.'}];
export const OUTINGS = [
 {id:'drawer',name:'The Lost Sock Drawer',tone:'lilac',intro:'Beyond the runners lies a nation of single socks. They have paired off politically.',steps:[
  {title:'The elastic frontier',text:'A sock blocks the crossing. It wants a toll. The toll is a smaller sock.',good:'thread',stat:'menace',options:['Build a thread bridge','Negotiate with the sock'],outcomes:['They crossed above the border. The sock has annexed the air.','The sock accepted a promise. It now owns a timeshare in your laundry.']},
  {title:'The button tribunal',text:'A button insists it has four eyes. It has four holes. This is a sensitive distinction.',quiet:'They waited for recess. The scissors left to cut a ribbon at a memorial they had personally made necessary.',good:'lantern',stat:'mystique',options:['Inspect its four eyewitnesses','Distract the tribunal'],outcomes:['All four witnesses could see through the story. None had seen a thing.','The tribunal adjourned to investigate a biscuit-shaped disturbance.']},
  {title:'The long way home',text:'The drawer starts closing. Someone has found a medal marked OUTSTANDING ABSENCE.',good:'thread',stat:'cute',options:['Lower the treasure on a thread','Ask the socks for safe passage'],outcomes:['The treasure descended with dignity. The residents followed with considerably less.','The socks formed a guard of honour. Half of them had been through this before.']}]},
 {id:'fridge',name:'Under the Fridge',tone:'mint',intro:'A cold kingdom of fossilised dinners. The peas remember your ancestors.',steps:[
  {title:'The frozen pass',text:'A crack in the floor exhales cold air. On the far side, a pea is wearing a crown.',good:'lantern',stat:'damp',options:['Find a warm route with the lantern','Offer a biscuit to the pea'],outcomes:['They followed the warm pipe. The pipe is now their spiritual leader.','The pea accepted tribute and declared winter slightly less personal.']},
  {title:'The cheese oracle',text:'A fragment of cheese predicts that someone will eat it. Its accuracy is troubling.',good:'biscuit',stat:'mystique',options:['Give it a biscuit bodyguard','Question the prophecy'],outcomes:['The bodyguard was eaten first. The cheese has revised its forecast.','The oracle admitted the future was mostly a smell. They wrote that down.']},
  {title:'The light expedition',text:'The fridge opens. A tiny sun appears. The residents have three seconds to invent astronomy.',good:'lantern',stat:'menace',options:['Capture the reflection in the lantern','Demand an audience with the sun'],outcomes:['They bottled a reflection. The original remains on a strict door schedule.','The sun went out mid-speech. The delegation has filed a complaint with the butter.']}]},
 {id:'cupboard',name:'The Cupboard Nobody Opens',tone:'amber',intro:'Nobody opens it. Naturally, somebody small has arranged a guided tour.',steps:[
  {title:'The teaspoon canyon',text:'A stack of teaspoons spans a gap. Every spoon claims to be the load-bearing one.',good:'thread',stat:'cute',options:['Secure a thread handrail','Compliment every spoon'],outcomes:['The handrail held. The spoons have requested equal credit.','Each spoon stood a little straighter. Structural flattery remains unregulated.']},
  {title:'The jar of teeth',text:'A tooth taps the glass. It says it has retired. The jar is full of references.',good:'lantern',stat:'menace',options:['Read its retirement papers','Offer it a softer career'],outcomes:['The papers were tiny and entirely in bite marks. Early retirement confirmed.','The tooth now opens letters. It has described this as a lateral move.']},
  {title:'A key with no door',text:'A key hangs inside a thimble. A cloud rains on it in a very local way.',good:'biscuit',stat:'damp',options:['Shelter the key under a biscuit','Interview the cloud'],outcomes:['The biscuit roof held until someone remembered it was food.','The cloud said it was going through something. They brought the whole situation home.']}]}
];


// New expeditions use this field book. The original OUTINGS steps above remain
// available to trips that were already in progress before the planning upgrade.
export const OUTING_TRAIL_SCENES = {
 drawer:[
  {title:'The next-of-kin desk',text:'A sock blocks the crossing. It declared its missing partner dead after one wash. The pension is paying for a much younger ankle.',quiet:'They went around. The sock reported a death anyway. The paperwork was already printed.',good:'thread',stat:'menace',options:['Build a thread bridge','Ask who collects the pension'],outcomes:['The bridge held. The guard listed them as missing and immediately applied for bereavement leave.','The sock waived the toll. In return, nobody tells its husband he is dead.']},
  {title:'The button tribunal',text:'A button was cut loose in suspicious circumstances. The scissors have appointed themselves coroner.',good:'lantern',stat:'mystique',options:['Read the suppressed report','Call the scissors as a witness'],outcomes:['The report says natural causes. Every time the scissors visit, another button dies naturally.','The scissors invoked their right to remain sharpened. The tribunal ruled it a wardrobe malfunction.']},
  {title:'A closing arrangement',text:'The drawer starts closing. An undertaker in a black sock has already measured the crew. He calls the measurements a courtesy.',quiet:'They took the stairs. The undertaker called after them that the first fitting had been free.',good:'thread',stat:'cute',options:['Lower the treasure on a thread','Promise the undertaker a referral'],outcomes:['They escaped on the thread. The undertaker sent an invoice for wasted optimism.','He let them leave with the medal. Their appointment card says REPEAT BUSINESS.']}
 ],
 fridge:[
  {title:'The frost ward',text:'A crowned pea is charging the frozen peas rent. They cannot move out. He describes the occupancy rate as excellent.',quiet:'They walked around the ward. A frozen pea winked. Apparently the rent is lower if the king thinks you are dead.',good:'lantern',stat:'damp',options:['Find the warm maintenance pipe','Threaten a thaw inspection'],outcomes:['They found the warm pipe. The king announced a regrettable loss of tenants and raised the survivors’ rent.','The king waived the toll. Three frozen peas were quietly reclassified as decorative features.']},
  {title:'The cheese’s last wishes',text:'The cheese has hired a biscuit bodyguard. It has also named the biscuit as sole beneficiary. Neither has read the whole contract.',quiet:'They left the cheese and biscuit to discuss the will. Both asked the crew to come back as a witness. Separately.',good:'biscuit',stat:'mystique',options:['Replace the compromised bodyguard','Read the will aloud'],outcomes:['The replacement biscuit ate the appointment letter. A conflict of interest has become a digestive issue.','The biscuit resigned. The cheese removed it from the will, then asked whether it would stay for dinner.']},
  {title:'The light at the end',text:'The fridge opens. A pea announces that this is the afterlife. The butter immediately starts charging for better seats.',quiet:'They waited for the door to close. The butter kept the ticket money. Heaven has a strict cancellation policy.',good:'lantern',stat:'menace',options:['Bottle a reflection of the light','Demand a refund from the afterlife'],outcomes:['They brought the light home. The butter is still invoicing the people who blinked.','The butter refunded one seat. The pea insisted the darkness was a premium spiritual experience.']}
 ],
 cupboard:[
  {title:'The teaspoon trustees',text:'A bridge of teaspoons wants the crew to sign a liability waiver. The final clause gives the spoons custody of the bodies.',quiet:'They used the steps. A spoon crossed their names out of its will with rather more pressure than necessary.',good:'thread',stat:'cute',options:['Rig a thread handrail','Point out how little they weigh'],outcomes:['The crew crossed safely. The spoons shredded the waiver with the quiet resentment of disappointed heirs.','The spoons waived the fee. One had already ordered a tiny coffin and is being unpleasant about it.']},
  {title:'The retirement jar',text:'A tooth says it retired voluntarily. The pliers keep interrupting to confirm this. Nobody asked the pliers.',quiet:'They let the pliers finish talking. The tooth asked them to remember that it had been smiling under duress.',good:'lantern',stat:'menace',options:['Examine the retirement papers','Ask the pliers to step outside'],outcomes:['The signature is a skid mark. The pension consists of being allowed to keep the root.','Without the pliers present, the tooth described its retirement rather differently. It now wants a lawyer with a stronger jaw.']},
  {title:'The return department',text:'A key is locked inside a thimble. The refund desk says the key is required to open the thimble. The complaints box is the same thimble.',quiet:'They joined a different queue. It led outside. Several applicants wept with relief.',good:'biscuit',stat:'damp',options:['Wedge the lid with a biscuit','Wait until the clerk needs a break'],outcomes:['The biscuit cracked the seal. The clerk marked the claim CUSTOMER DECEASED, then looked annoyed when they left.','The clerk stepped out. They took the key and left a complaint inside. It finally has someone to ignore.']}
 ]
};
// Eight editions combine the familiar stops with these alternate incidents.
export const OUTING_ALTERNATES = {
 drawer:[
  {title:'The Ministry of Loose Ends',text:'A ribbon processes death certificates for missing socks. It is wearing a scarf made from the applicants. Expedited grief costs extra.',quiet:'They took a number and left. The ribbon billed their absence as a private funeral.',good:'thread',stat:'cute',options:['Unpick the office uniform','Request the original death certificates'],outcomes:['Three missing socks fell out of the scarf. The ribbon demanded they repay their own funeral expenses.','The certificates were blank. The ribbon said the bereaved were paying for closure, not accuracy.']},
  {title:'A very small jailbreak',text:'Three buttons are on death row for coming loose. The warden is selling replacement buttons through a company registered to his mother.',quiet:'They walked past the cells. The warden asked whether they had any loose buttons at home. Strictly for the census.',good:'biscuit',stat:'menace',options:['Bribe the guard with crumbs','Ask to inspect the warden’s accounts'],outcomes:['The guard opened the cell. He has billed the crumbs as execution expenses.','The warden released all three buttons. His mother has inexplicably moved the company offshore.']},
  {title:'The seam nobody mentions',text:'A silver seam offers a shortcut. A black sock beside it sells return tickets. Every ticket in the drawer is unused.',quiet:'They used the marked exit. The ticket seller called it dangerous. He did not offer to explain the urns.',good:'lantern',stat:'mystique',options:['Check what lies beyond the seam','Ask to see a satisfied customer'],outcomes:['The lantern revealed a dead end and a second ticket booth. Same sock. Different hat.','The sock produced a testimonial in its own handwriting. They took the exit while it was explaining the coincidence.']}
 ],
 fridge:[
  {title:'The butter border',text:'The butter keeps confiscating peas for “health inspections”. The inspection room contains a fork and no medical equipment.',quiet:'They found another crossing. A sign described it as the bereaved entrance. It had suspiciously heavy traffic.',good:'biscuit',stat:'cute',options:['Offer a biscuit instead','Ask for the inspector’s qualifications'],outcomes:['The butter took the biscuit. A pea slipped out carrying a bill for a procedure it very nearly received.','The certificate says TABLE MANNERS, LEVEL ONE. The butter quietly opened the border.']},
  {title:'The ice-cube farewell',text:'An ice cube is rehearsing its funeral. The peas keep bringing up people who owe it money. It has stopped melting out of spite.',quiet:'They waited through the eulogy. The ice cube interrupted twice to correct how much it was owed.',good:'thread',stat:'damp',options:['Tow it back to the cold pipe','Help collect its final debts'],outcomes:['The cube froze solid again. It has cancelled the funeral but refuses to refund the catering.','One pea paid. The cube immediately extended its life expectancy to cover the remaining accounts.']},
  {title:'The sealed inquiry',text:'A sealed tub holds a hearing about a missing lasagne. The chairman has sauce on his tie. The transcript already says no evidence found.',quiet:'They waited outside. The verdict arrived before the evidence. The chairman had a table booked.',good:'lantern',stat:'menace',options:['Hold the tub up to the light','Ask the chairman to empty his pockets'],outcomes:['The lantern revealed six witnesses and a fork. Every witness had been threatened with being reheated.','The chairman produced a sheet of pasta. He called it a personal document and ate it.']}
 ],
 cupboard:[
  {title:'The mug’s second handle',text:'A mug has hired a replacement handle without telling the first one. There is a hammer on the table. It has been invited to the meeting.',quiet:'They used another shelf. Behind them, the hammer began explaining that it was only following orders.',good:'biscuit',stat:'mystique',options:['Delay the meeting with biscuits','Ask the hammer who authorised this'],outcomes:['The handles took a biscuit break together. The hammer was removed from the minutes and told to wait outside.','The hammer blamed procurement. Procurement is a teapot with three former spouts buried behind it.']},
  {title:'The saucer society',text:'The saucer club has expelled a bowl for having depth. The bowl has paid twenty years of dues and brought a list of who sleeps with whose cutlery.',quiet:'They left the bowl to negotiate. The club lowered its blinds when it reached the third name on the list.',good:'thread',stat:'cute',options:['Make the bowl a saucer disguise','Offer to read the list aloud'],outcomes:['The disguise passed. The bowl now sits on the membership committee and remembers every vote.','The club admitted the bowl unanimously. The chair’s wife quietly confiscated the dessert forks.']},
  {title:'The expiry-date appeal',text:'A preserve is appealing its disposal order. The jar beside it volunteered as character witness, then moved into its shelf space during the recess.',quiet:'They waited in the corridor. The helpful neighbour offered to hold the preserve’s house keys. Again.',good:'lantern',stat:'damp',options:['Read the date in proper light','Cross-examine the helpful neighbour'],outcomes:['The date was a batch number. The preserve has returned home and is making the neighbour unpack one item at a time.','The neighbour admitted it had ordered a commemorative plaque. Delivery was scheduled before the hearing.']}
 ]
};

// Each caller brings a distinct, solvable small problem. First visits establish
// the joke; returning visits remember the previous intervention.
export const VISITOR_ACTS = {
 moth:{title:'The lamp examination',clue:'The warm lamp attracts her. The cold mirror only imitates a light.',choices:['Offer the warm lamp','Recommend the cold mirror'],right:0,win:'Madam Moth circles the lamp, slowly. “A sound bulb. Appalling bedside manner.” She leaves a wing-print of approval.',miss:'She headbutts the reflection once. “A fraudulent light. I shall be leaving a very small review.”',later:'She remembers the lamp inspection. This time she has brought reading glasses for the bulb.'},
 lint:{title:'A border negotiation',clue:'The Baron claims land only when a line encloses it. Leave an opening and it remains a public footpath.',choices:['Tie the lint into a ring','Leave a gap in the boundary'],right:1,win:'The Baron strides through the gap. His empire has become a pedestrian right of way.',miss:'The ring is now a country. Its economy consists of him charging himself rent.',later:'The Baron has returned with a passport the size of his own photograph.'},
 bell:{title:'The missing note',clue:'The bell has lost its sound, but the table still vibrates when it is struck.',choices:['Listen with a fingertip','Shout into the bell'],right:0,win:'Miss Afterbell lets the vibration travel through the plank. The silence gets its pulse back.',miss:'Your shout returns. The bell has outsourced its entire personality to you.',later:'Miss Afterbell brings a second silence. The first one has been getting lonely.'},
 needle:{title:'A stitch in the evidence',clue:'The coat is torn at the seam. A short running stitch joins both edges; a knot tied to only one edge joins nothing.',choices:['Stitch through both edges','Tie a knot in one edge'],right:0,win:'The Mother Needle repairs the seam. “Case closed. Please do not test the verdict by breathing.”',miss:'One edge is now legally bound to itself. The other has fled the jurisdiction.',later:'Mother Needle brings a warrant stitched in very neat letters.'},
 widow:{title:'Mourning dress',clue:'The loose thread belongs to the black coat. The brass button belongs to someone still wearing it.',choices:['Borrow the brass button','Repair the loose black thread'],right:1,win:'The Button Widow closes her coat. “One less opening for grief. Or draughts.”',miss:'The donor arrives still attached. The funeral now has a plus-one.',later:'The widow is no longer looking for closure. She has brought a zip.'},
 spore:{title:'A portrait of the damp',clue:'The painted fungus needs shade and moisture. The sunlit patch is dry; the cup’s shadow is damp.',choices:['Hang it in the damp shade','Frame it in direct sunlight'],right:0,win:'The portrait grows a second subject. “Family resemblance,” says the spore. “Do not ask about the frame.”',miss:'The portrait dries into a landscape of personal regret. The artist declares a new period.',later:'The artist returns with a portrait that is developing opinions.'},
 echo:{title:'Return to sender',clue:'The echo returns from hard surfaces. The cushion absorbs it; the empty cup reflects it.',choices:['Speak into the empty cup','Confide in the cushion'],right:0,win:'The cup repeats the greeting. The echo has finally found somebody who agrees with it for structural reasons.',miss:'The cushion keeps the secret. The echo calls this a hostile takeover of the conversation.',later:'The echo returns with something it heard you say. It has improved the punctuation.'},
 undertow:{title:'A second opinion',clue:'The patient is a raisin. It has no pulse because it is a raisin.',choices:['Prescribe a smaller funeral','Explain the dried-fruit diagnosis'],right:1,win:'The doctor confirms chronic raisin. Prognosis: indefinitely wrinkled.',miss:'The funeral cures nothing, but the catering is remarkably convenient.',later:'The doctor has brought a grape for comparison. It looks worried.'},
 tooth:{title:'A bite-sized dispute',clue:'A clean bite in the biscuit fits one tooth. The fork has three prongs.',choices:['Question the lone tooth','Arrest the fork'],right:0,win:'The tooth admits involvement. It was acting in a chewing capacity.',miss:'The fork demands three lawyers. One for each point of contention.',later:'The tooth is back on probation. No biscuits within biting distance.'},
 clock:{title:'Borrowed minutes',clue:'The stopped clock is right twice a day. The fast clock is never right at the promised time.',choices:['Trust the fast clock','Meet when the stopped clock agrees'],right:1,win:'Mr Borrowed Time arrives exactly once. He considers this a personal record.',miss:'He arrives before the invitation and complains about the lack of suspense.',later:'Mr Borrowed Time has brought back your minute. Slightly chewed.'},
 receipt:{title:'The suspicious total',clue:'Two crumbs at three each cost six. The invoice says nine. The extra three are labelled emotional postage.',choices:['Pay all nine','Challenge the extra three'],right:1,win:'The Receipt Eater eats the surcharge first. “A clerical flavour. Quite bitter.”',miss:'The surcharge is paid. Your grief will arrive in three to five working days.',later:'The Receipt Eater has brought an itemised apology. Several items are edible.'},
 rain:{title:'An indoor forecast',clue:'The captain’s cloud follows its reflection. Turn the mirror toward the basin.',choices:['Aim the mirror at the basin','Put a hat on the cloud'],right:0,win:'Rain falls into the basin. The captain calls this irrigation and immediately promotes himself.',miss:'The hat becomes a lake. Its previous owner has requested swimming lessons.',later:'Captain Indoor Rain brings a smaller cloud. It has inherited the rank.'}
};

// Return chapters have new evidence and decisions, rather than replaying the
// first encounter with a changed greeting. No missed-day or wrong-answer penalty.
const RETURNS = {
 moth:[['Reading by a naked flame','The paper shade scorches beside the flame. The glass shade stays clear.','Choose the glass shade','Move the paper closer','The lamp passes its fire inspection. Madam Moth fails hers by falling in love with it.'],['The farewell rehearsal','The porch lamp points outside. The wardrobe light points into a coat.','Leave the porch lamp on','Illuminate the coat','She follows the porch light, then returns to say goodbye again. The bulb has never felt so needed.']],
 lint:[['The passport office','The Baron’s passport has his portrait but no signature. The blank line is labelled Signature.','Sign the blank line','Add a second portrait','The Baron signs. His entire government is now travelling abroad.'],['An empire in miniature','The treaty gives everyone access to the shelf. The alternative charges residents rent for standing still.','Ratify shared access','Tax the stationary','The Baron opens the border. “An empire of friends,” he says, with the pain of a man discovering public services.']],
 bell:[['A padded complaint','The felt pad stops the bell touching the table. Removing it lets the vibration reach the wood.','Remove the felt pad','Add another pad','The table hums along. Afterbell has founded a choir with excellent attendance and no lungs.'],['The quiet concert','A gentle tap makes one clear note. A hard shake makes several clashing notes.','Give one gentle tap','Shake it vigorously','One note travels the whole shelf. Nobody speaks until it ends. Even the crumb behaves as if it has a mother.']],
 needle:[['The missing stitch','The tear is three stitches wide. Two stitches leave a gap; three close it.','Make three stitches','Make two stitches','Mother Needle closes the gap. “Nothing gets through.” A draught immediately hires a lawyer.'],['A warrant for warmth','The scarf has a loose end. Securing it keeps the stitches from unravelling.','Secure the loose end','Pull the loose end','The scarf stays a scarf. Mother Needle leaves it with you, marked EVIDENCE OF AFFECTION.']],
 widow:[['A zip without closure','The two sides of the zip start at different heights. Aligning the base lets the slider join them.','Align the base first','Pull harder from the top','The coat closes. The widow permits herself a draught-free sigh.'],['The memorial button','The memorial coat already has six buttonholes and five buttons. One more button completes the row.','Sew on one button','Cut a seventh hole','The sixth button takes its place. “He always liked an orderly exit,” she says. Nobody asks which he.']],
 spore:[['A growing resemblance','The frame is squeezing the growing portrait. A wider frame gives it room.','Use a wider frame','Tighten the existing frame','The portrait grows into its frame. It is still a poor likeness, but now confidently so.'],['The exhibition opens','The new painting sheds spores when shaken. A still stand keeps them on the canvas.','Place it on a still stand','Shake it for the audience','The artist unveils a still life that is only technically still. You are thanked in the catalogue as a supporting surface.']],
 echo:[['An original thought','The cup repeats the final word. To hear welcome, end the sentence with welcome.','Say: You are welcome','Say: Welcome, probably','“Welcome,” says the cup. The echo looks surprised to be wanted without a qualifying clause.'],['A voice of its own','Two cups repeat each other forever. Turning one away ends the loop.','Turn one cup away','Bring the cups closer','For once, the echo speaks only once. “Thank you.” The silence afterwards is its own choice.']],
 undertow:[['The grape comparison','The raisin is dry and wrinkled. The grape is plump with water. Both are fruit.','Record the water difference','Diagnose a missing skeleton','Undertow files the report under Natural Causes, Extremely Natural. The grape requests a second opinion anyway.'],['Discharge papers','The raisin is stable and needs no treatment. The invoice includes a charge for imaginary resuscitation.','Discharge it without the charge','Bill the imaginary procedure','The raisin is discharged in the same condition it arrived. Undertow calls this continuity of care.']],
 tooth:[['Terms of probation','The biscuit line is marked DO NOT CROSS. Standing behind it leaves the biscuits beyond reach.','Stay behind the line','Move the line past the biscuits','The tooth obeys. Its parole officer records “promising, though visibly enamelled.”'],['A letter-opening ceremony','The envelope seam is unglued. Opening the seam preserves the letter; biting the middle tears it.','Open along the seam','Bite through the middle','The tooth opens its first letter. It is a reference praising its restraint. It does not bite the reference.']],
 clock:[['A punctual apology','The invitation says noon. The clock is five minutes fast. At noon it will show 12:05.','Arrive when it shows 12:05','Arrive when it shows 11:55','He arrives at noon carrying five minutes of unnecessary anxiety. A personal best.'],['A minute freely given','The timer runs for sixty seconds. Turning it twice measures two minutes.','Turn it once','Turn it twice','For one minute nobody owes anyone anything. He leaves before anyone can issue a receipt.']],
 receipt:[['The itemised apology','The apology lists two errors at zero cost. The total should also be zero.','Accept a zero total','Add an apology surcharge','The Receipt Eater swallows the invoice. “On the house,” it says, tasting the unfamiliar sensation of accountability.'],['A clean account','The ledger shows a debt of six and a payment of six. The balance is zero.','Mark the account settled','Carry six forward','The account is closed. The Receipt Eater keeps the blank page. “For something that isn’t owed.”']],
 rain:[['Cloud nursery','The tiny cloud drips above an open cup. A lid would send the water onto the shelf.','Leave the cup open','Put a lid on the cup','The little cloud fills its first cup. The captain salutes so hard he waters his own shoes.'],['The weather retirement','The umbrella covers the residents. The basin catches the rain. Together they keep the shelf dry.','Keep the umbrella over the residents','Use the umbrella to cover the basin','A small rain falls into its proper place. The captain calls it a peaceful transfer of weather.']]
};
export function visitorActFor(id, chapter) {
 const base=VISITOR_ACTS[id];if(!base)return null;
 const next=RETURNS[id]?.[chapter-1];if(!next)return base;
 // Alternate the correct side in return chapters. Evidence determines the answer.
 const right=chapter%2;
 return {...base,title:next[0],clue:next[1],choices:right?[next[3],next[2]]:[next[2],next[3]],right,win:next[4],miss:'The plan goes sideways. '+next[3]+': an idea now preserved in the minutes under “Before we knew better.” They try again together. '+next[4]};
}
