export const FRAMES = [
  {id:'wood',name:'Found timber',at:0,line:'It was a tree. It has adjusted poorly.'},
  {id:'brass',name:'Brass exhibition',at:6,line:'Museum standards. Pawn-shop provenance.'},
  {id:'moon',name:'Moon cabinet',at:16,line:'For objects that look different when you blink.'},
  {id:'velvet',name:'Velvet mausoleum',at:32,line:'Nothing has died. The velvet is optimistic.'}
];
export const RELICS = [
  {id:'market:0',name:'A receipt for questionable judgement',shape:'receipt',line:'All sales final. Several opinions provisional.'},
  {id:'market:1',name:'The silver shopping thimble',shape:'medal',line:'Awarded for bringing home objects that actually go together. A rare household event.'},
  {id:'market:2',name:'The crown of suspicious bargains',shape:'crown',line:'The market has recognised your talent. The vendors have raised your rent.'},
  {id:'drawer:0',name:'A sock with diplomatic immunity',shape:'sock',line:'The left sock is still being questioned.'},
  {id:'drawer:1',name:'The missing button’s alibi',shape:'button',line:'It was sewn up. Suspiciously neatly.'},
  {id:'drawer:2',name:'A medal for being lost',shape:'medal',line:'First place. Location unknown.'},
  {id:'fridge:0',name:'A prehistoric pea',shape:'pea',line:'It has outlived three diets and a marriage.'},
  {id:'fridge:1',name:'The spoon of last resort',shape:'spoon',line:'Too small for soup. Exactly right for revenge.'},
  {id:'fridge:2',name:'A refrigerator sun',shape:'sun',line:'They brought back the light. The butter is furious.'},
  {id:'cupboard:0',name:'A thimble full of weather',shape:'rain',line:'Forecast: localised unpleasantness.'},
  {id:'cupboard:1',name:'A formally retired tooth',shape:'tooth',line:'No longer biting. Advising in a consultancy role.'},
  {id:'cupboard:2',name:'The key to a smaller problem',shape:'key',line:'Opens something. Nobody has admitted what.'}
];

export const GEAR = [{id:'thread',name:'Thread & safety pin',hint:'Bridges gaps; rescues things without a speech.'},{id:'lantern',name:'Pocket lantern',hint:'Reveals small print, warm routes, and things pretending to be furniture.'},{id:'biscuit',name:'Emergency biscuit',hint:'A bribe, a distraction, or a last-minute relative.'}];
export const OUTINGS = [
 {id:'drawer',name:'The Lost Sock Drawer',tone:'lilac',intro:'Beyond the runners lies a nation of single socks. They have paired off politically.',steps:[
  {title:'The elastic frontier',text:'A sock blocks the crossing. It wants a toll. The toll is a smaller sock.',good:'thread',stat:'menace',options:['Build a thread bridge','Negotiate with the sock'],outcomes:['They crossed above the border. The sock has annexed the air.','The sock accepted a promise. It now owns a timeshare in your laundry.']},
  {title:'The button tribunal',text:'A button insists it has four eyes. It has four holes. This is a sensitive distinction.',quiet:'They waited for recess. The scissors left to cut a ribbon at a memorial they had personally made necessary.',good:'lantern',stat:'mystique',options:['Inspect its four eyewitnesses','Distract the tribunal'],outcomes:['All four witnesses could see through the story. None had seen a thing.','The tribunal adjourned to investigate a biscuit-shaped disturbance.']},
  {title:'The long way home',text:'The drawer starts closing. Someone has found a medal marked OUTSTANDING ABSENCE.',good:'thread',stat:'cute',options:['Lower the treasure on a thread','Ask the socks for safe passage'],outcomes:['The treasure descended with dignity. The residents followed with considerably less.','The socks formed a guard of honour. Half of them had been through this before.']}]},
 {id:'fridge',name:'Under the Fridge',tone:'mint',intro:'A cold kingdom of fossilised dinners. The peas remember your ancestors.',steps:[
  {title:'The frozen pass',text:'A crack in the floor exhales cold air. On the far side, a pea is wearing a crown.',good:'lantern',stat:'damp',options:['Find a warm route with the lantern','Offer a biscuit to the pea'],outcomes:['They followed the warm pipe. The pipe is now their spiritual leader.','The pea accepted tribute and declared winter slightly less personal.']},
  {title:'The cheese oracle',text:'A fragment of cheese predicts that someone will eat it. Its accuracy is troubling.',good:'biscuit',stat:'mystique',options:['Give it a biscuit bodyguard','Question the prophecy'],outcomes:['The bodyguard was eaten first. The cheese has revised its forecast.','The oracle admitted the future was mostly a smell. They wrote that down.']},
  {title:'The light expedition',text:'The fridge opens. A tiny sun appears. The residents have three seconds to invent astronomy.',good:'lantern',stat:'menace',options:['Capture the reflection in the lantern','Demand an audience with the sun'],outcomes:['They bottled a reflection. The original remains on a strict door schedule.','The sun went out mid-speech. The delegation has filed a complaint with the butter.']}]},
 {id:'cupboard',name:'The Cupboard Nobody Opens',tone:'amber',intro:'Nobody opens it. Naturally, somebody small has arranged a guided tour.',steps:[
  {title:'The teaspoon canyon',text:'A stack of teaspoons spans a gap. Every spoon claims to be the load-bearing one.',good:'thread',stat:'cute',options:['Secure a thread handrail','Compliment every spoon'],outcomes:['The handrail held. The spoons have requested equal credit.','Each spoon stood a little straighter. Structural flattery remains unregulated.']},
  {title:'The jar of teeth',text:'A tooth taps the glass. It says it has retired. The jar is full of references.',good:'lantern',stat:'menace',options:['Read its retirement papers','Offer it a softer career'],outcomes:['The papers were tiny and entirely in bite marks. Early retirement confirmed.','The tooth now opens letters. It has described this as a lateral move.']},
  {title:'A key with no door',text:'A key hangs inside a thimble. A cloud rains on it in a very local way.',good:'biscuit',stat:'damp',options:['Shelter the key under a biscuit','Interview the cloud'],outcomes:['The biscuit roof held until someone remembered it was food.','The cloud said it was going through something. They brought the whole situation home.']}]}
];


// New expeditions use this field book. The original OUTINGS steps above remain
// available to trips that were already in progress before the planning upgrade.
export const OUTING_TRAIL_SCENES = {
 drawer:[
  {title:'The next-of-kin desk',text:'A sock blocks the crossing. It declared its missing partner dead after one wash. The pension is paying for a much younger ankle.',quiet:'They went around. The sock reported a death anyway. The paperwork was already printed.',good:'thread',stat:'menace',options:['Build a thread bridge','Ask who collects the pension'],outcomes:['The bridge held. The guard listed them as missing and immediately applied for bereavement leave.','The sock waived the toll. In return, nobody tells its husband he is dead.']},
  {title:'The scissors’ nursery',text:'The scissors have tucked six buttons into little beds. They call them orphans. Six coats are hanging nearby with their throats open.',quiet:'The crew backed away. The scissors sang a lullaby and opened themselves a little wider.',good:'lantern',stat:'mystique',options:['Look under the blankets','Ask where the mothers are'],outcomes:['Each bed had a price tag under the blanket. The scissors said adoption could be expensive and began polishing a seventh cot.','The scissors pointed at the coats. The crew pointed at the scissors. Six buttons quietly got out of bed.']},
  {title:'A closing arrangement',text:'The drawer starts closing. An undertaker in a black sock has already measured the crew. He calls the measurements a courtesy.',quiet:'They took the stairs. The undertaker called after them that the first fitting had been free.',good:'thread',stat:'cute',options:['Lower the treasure on a thread','Promise the undertaker a referral'],outcomes:['They escaped on the thread. The undertaker sent an invoice for wasted optimism.','He let them leave with the medal. Their appointment card says REPEAT BUSINESS.']}
 ],
 fridge:[
  {title:'The pea king’s supper',text:'The pea king invites a different subject to dinner every night. Nobody comes back. He says they loved it so much they stayed in the soup.',quiet:'They went around the kitchen. The king asked whether they knew any peas who travelled alone.',good:'lantern',stat:'damp',options:['Shine the lantern into the soup','Ask why dinner needs a guest list'],outcomes:['The soup contained six tiny crowns. The king said those were croutons. One of them said hello.','The king crossed out the crew’s names. He asked them to send a friend. Someone plump, if possible.']},
  {title:'The cheese’s last wishes',text:'The cheese has hired a biscuit bodyguard. It has also named the biscuit as sole beneficiary. Neither has read the whole contract.',quiet:'They left the cheese and biscuit to discuss the will. Both asked the crew to come back as a witness. Separately.',good:'biscuit',stat:'mystique',options:['Replace the compromised bodyguard','Read the will aloud'],outcomes:['The replacement biscuit ate the appointment letter. A conflict of interest has become a digestive issue.','The biscuit resigned. The cheese removed it from the will, then asked whether it would stay for dinner.']},
  {title:'The light at the end',text:'The fridge opens. A pea announces that this is the afterlife. The butter immediately starts charging for better seats.',quiet:'They waited for the door to close. The butter kept the ticket money. Heaven has a strict cancellation policy.',good:'lantern',stat:'menace',options:['Bottle a reflection of the light','Demand a refund from the afterlife'],outcomes:['They brought the light home. The butter is still invoicing the people who blinked.','The butter refunded one seat. The pea insisted the darkness was a premium spiritual experience.']}
 ],
 cupboard:[
  {title:'The teaspoon funeral band',text:'A bridge of teaspoons rehearses a funeral march as the crew approaches. The conductor asks everyone to cross in single file. It only has one coffin.',quiet:'The crew found some steps. The conductor threw its little baton into the coffin and sat down in it.',good:'thread',stat:'cute',options:['Rig a thread handrail','Ask the band to play something faster'],outcomes:['The crew crossed on the handrail. The spoons finished the funeral march anyway. One of them had hired a photographer.','The spoons played so fast that the crew marched across before the bridge remembered to collapse. The conductor bit its baton in half.']},
  {title:'The retirement jar',text:'A tooth says it retired voluntarily. The pliers keep interrupting to confirm this. Nobody asked the pliers.',quiet:'They let the pliers finish talking. The tooth asked them to remember that it had been smiling under duress.',good:'lantern',stat:'menace',options:['Examine the retirement papers','Ask the pliers to step outside'],outcomes:['The signature is a skid mark. The pension consists of being allowed to keep the root.','Without the pliers present, the tooth described its retirement rather differently. It now wants a lawyer with a stronger jaw.']},
  {title:'The thimble’s dinner party',text:'A thimble invites the crew inside for dinner. The key at the bottom keeps mouthing NO. The thimble says it is doing an impression.',quiet:'They declined dinner. The thimble asked whether anybody would miss them if they stayed for a drink.',good:'biscuit',stat:'damp',options:['Wedge the lid with a biscuit','Ask the key to repeat the impression'],outcomes:['The biscuit held the lid open. The key climbed out with three toothpicks and a guest who had been listed as cutlery.','The key shouted NO. The thimble said it was a difficult room. The crew took the key while it tried the joke again.']}
 ]
};
// Eight editions combine the familiar stops with these alternate incidents.
export const OUTING_ALTERNATES = {
 drawer:[
  {title:'The Ministry of Loose Ends',text:'A ribbon processes death certificates for missing socks. It is wearing a scarf made from the applicants. Expedited grief costs extra.',quiet:'They took a number and left. The ribbon billed their absence as a private funeral.',good:'thread',stat:'cute',options:['Unpick the office uniform','Request the original death certificates'],outcomes:['Three missing socks fell out of the scarf. The ribbon demanded they repay their own funeral expenses.','The certificates were blank. The ribbon said the bereaved were paying for closure, not accuracy.']},
  {title:'The button farm',text:'A farmer is growing buttons on a coat. The coat is tied to a chair and keeps asking when the harvest is over. “Perennial,” says the farmer.',quiet:'They took the long path. The farmer shouted that he was looking for seasonal help, preferably wearing a cardigan.',good:'biscuit',stat:'menace',options:['Distract the farmer with a biscuit','Cut the coat loose'],outcomes:['The farmer bit the biscuit. The coat ran while he was working out why it did not have sleeves.','They untied the coat. It hit the farmer with both sleeves, then went back for the buttons. Not one was left behind.']},
  {title:'The seam nobody mentions',text:'A silver seam offers a shortcut. A black sock beside it sells return tickets. Every ticket in the drawer is unused.',quiet:'They used the marked exit. The ticket seller called it dangerous. He did not offer to explain the urns.',good:'lantern',stat:'mystique',options:['Check what lies beyond the seam','Ask to see a satisfied customer'],outcomes:['The lantern revealed a dead end and a second ticket booth. Same sock. Different hat.','The sock produced a testimonial in its own handwriting. They took the exit while it was explaining the coincidence.']}
 ],
 fridge:[
  {title:'The butter border',text:'The butter keeps confiscating peas for “health inspections”. The inspection room contains a fork and no medical equipment.',quiet:'They found another crossing. A sign described it as the bereaved entrance. It had suspiciously heavy traffic.',good:'biscuit',stat:'cute',options:['Offer a biscuit instead','Ask for the inspector’s qualifications'],outcomes:['The butter took the biscuit. A pea slipped out carrying a bill for a procedure it very nearly received.','The certificate says TABLE MANNERS, LEVEL ONE. The butter quietly opened the border.']},
  {title:'The ice-cube farewell',text:'An ice cube is rehearsing its funeral. The peas keep bringing up people who owe it money. It has stopped melting out of spite.',quiet:'They waited through the eulogy. The ice cube interrupted twice to correct how much it was owed.',good:'thread',stat:'damp',options:['Tow it back to the cold pipe','Help collect its final debts'],outcomes:['The cube froze solid again. It has cancelled the funeral but refuses to refund the catering.','One pea paid. The cube immediately extended its life expectancy to cover the remaining accounts.']},
  {title:'The leftovers’ séance',text:'A tub of leftovers is trying to contact a missing lasagne. The medium has sauce around its mouth. It says the spirit is at peace and quite filling.',quiet:'They passed the séance. The medium asked whether anyone else had recently lost a loved one with a cheese topping.',good:'lantern',stat:'menace',options:['Hold the tub up to the light','Ask the medium to open its mouth'],outcomes:['The lantern showed a fork behind the curtain. The medium called it a spiritual antenna and quietly lowered its napkin.','A sheet of pasta fell out. The medium said it was ectoplasm. Nobody had asked why it was chewing.']}
 ],
 cupboard:[
  {title:'The mug’s second handle',text:'A mug has hired a replacement handle without telling the first one. There is a hammer on the table. It has been invited to the meeting.',quiet:'They used another shelf. Behind them, the hammer began explaining that it was only following orders.',good:'biscuit',stat:'mystique',options:['Delay the meeting with biscuits','Ask the hammer who authorised this'],outcomes:['The handles took a biscuit break together. The hammer was removed from the minutes and told to wait outside.','The hammer blamed procurement. Procurement is a teapot with three former spouts buried behind it.']},
  {title:'The saucer society',text:'The saucer club has expelled a bowl for having depth. The bowl has paid twenty years of dues and brought a list of who sleeps with whose cutlery.',quiet:'They left the bowl to negotiate. The club lowered its blinds when it reached the third name on the list.',good:'thread',stat:'cute',options:['Make the bowl a saucer disguise','Offer to read the list aloud'],outcomes:['The disguise passed. The bowl now sits on the membership committee and remembers every vote.','The club admitted the bowl unanimously. The chair’s wife quietly confiscated the dessert forks.']},
  {title:'The expiry-date appeal',text:'A preserve is appealing its disposal order. The jar beside it volunteered as character witness, then moved into its shelf space during the recess.',quiet:'They waited in the corridor. The helpful neighbour offered to hold the preserve’s house keys. Again.',good:'lantern',stat:'damp',options:['Read the date in proper light','Cross-examine the helpful neighbour'],outcomes:['The date was a batch number. The preserve has returned home and is making the neighbour unpack one item at a time.','The neighbour admitted it had ordered a commemorative plaque. Delivery was scheduled before the hearing.']}
 ]
};

// Each caller brings a distinct, solvable small problem. First visits establish
// the joke; returning visits remember the previous intervention.
export const VISITOR_ACTS = {
 moth:{title:'The lamp examination',clue:'The warm lamp attracts her. The cold mirror only imitates a light.',choices:['Offer the warm lamp','Recommend the cold mirror'],right:0,win:'Madam Moth circles the warm lamp. “I could die here.” She says it with the relief of someone cancelling several appointments.',miss:'She strikes the mirror and drops. “Nothing behind the glass.” She looks at you. “I thought we had that in common.”',later:'She remembers the lamp. She has brought a photograph of herself for its bedside.'},
 lint:{title:'A border negotiation',clue:'The Baron claims land only when a line encloses it. Leave an opening and it remains a public footpath.',choices:['Tie the lint into a ring','Leave a gap in the boundary'],right:1,win:'The Baron walks through the gap. The boundary is a footpath now. He watches a resident use it for free and briefly seems unwell.',miss:'The ring becomes a country. The Baron charges himself rent, falls behind, and has his own possessions carried out. He calls it a healthy market.',later:'The Baron returns with a passport and a list of residents he considers foreign. It is the same list.'},
 bell:{title:'The missing note',clue:'The bell has lost its sound, but the table still vibrates when it is struck.',choices:['Listen with a fingertip','Shout into the bell'],right:0,win:'The vibration travels through the plank into your fingertip. Miss Afterbell closes her eyes. “There. Somebody else felt it.”',miss:'Your shout returns from the bell. Miss Afterbell moves away. “That is how the others started.”',later:'Miss Afterbell brings another silence. She keeps the two bells facing away from each other.'},
 needle:{title:'A stitch in the evidence',clue:'The coat is torn at the seam. A short running stitch joins both edges; a knot tied to only one edge joins nothing.',choices:['Stitch through both edges','Tie a knot in one edge'],right:0,win:'Mother Needle stitches both edges together. “Try moving.” She watches closely. “Good. The last one did not.”',miss:'One edge is tied to itself. The tear stays open. Mother Needle asks who taught you. She takes out a second needle for them.',later:'Mother Needle returns with a sample of your stitching. She has been showing it to clients who complain about her prices.'},
 widow:{title:'Mourning dress',clue:'The loose thread belongs to the black coat. The brass button belongs to someone still wearing it.',choices:['Borrow the brass button','Repair the loose black thread'],right:1,win:'The widow repairs the black thread and closes her coat. Something small stops rattling inside. “Much better.”',miss:'The brass button arrives with its owner still wearing it. The widow sets a second place at the funeral lunch.',later:'The widow returns with a zip. Buttons have become difficult to explain to the police.'},
 spore:{title:'A portrait of the damp',clue:'The painted fungus needs shade and moisture. The sunlit patch is dry; the cup’s shadow is damp.',choices:['Hang it in the damp shade','Frame it in direct sunlight'],right:0,win:'A second face grows in the damp portrait. Auntie Spore studies it. “That one was supposed to stay dead.” She makes room anyway.',miss:'The portrait dries in the sunlight. Auntie Spore counts the lost relatives. She uses the same voice other people use for ruined groceries.',later:'Auntie Spore returns with a larger portrait. Someone in it has crossed out your name and written Mother.'},
 echo:{title:'Return to sender',clue:'The echo returns from hard surfaces. The cushion absorbs it; the empty cup reflects it.',choices:['Speak into the empty cup','Confide in the cushion'],right:0,win:'The cup repeats the greeting. Little Echo listens twice. “That one sounds like me.” It has not said that about a voice before.',miss:'The cushion absorbs the greeting. Little Echo presses closer. “It heard me. It is choosing not to answer.”',later:'Little Echo brings back something you said while you thought you were alone. It wants to know who you were talking to.'},
 undertow:{title:'A second opinion',clue:'The patient is a raisin. It has no pulse because it is a raisin.',choices:['Prescribe a smaller funeral','Explain the dried-fruit diagnosis'],right:1,win:'Undertow confirms the patient is a raisin. He crosses out the surgery and leaves the consultation fee. “You are paying for certainty.”',miss:'The raisin receives a funeral. Undertow eats the patient at the reception and bills for disposal.',later:'Undertow brings a grape for comparison. It is marked BEFORE. He has left the second label blank.'},
 tooth:{title:'The bite in the biscuit',clue:'A clean bite in the biscuit fits one tooth. The fork has three prongs.',choices:['Question the lone tooth','Arrest the fork'],right:0,win:'The tooth matches the bite. It confesses to that biscuit and asks how closely you have examined the others.',miss:'The fork is arrested. Behind it, the tooth quietly eats the rest of the evidence.',later:'The tooth returns on probation. Someone has brought biscuits to the review. It is not clear whether this is incompetence or a test.'},
 clock:{title:'Borrowed minutes',clue:'The stopped clock is right twice a day. The fast clock is never right at the promised time.',choices:['Trust the fast clock','Meet when the stopped clock agrees'],right:1,win:'The stopped clock agrees with the hour. Mr Borrowed Time arrives on time and looks briefly younger. “I had forgotten what this felt like.”',miss:'The fast clock brings him too early. He sits through the empty room describing which of its current occupants will be missed.',later:'Mr Borrowed Time brings back your minute. He will not tell you who had it in between.'},
 receipt:{title:'The suspicious total',clue:'Two crumbs at three each cost six. The invoice says nine. The extra three are labelled emotional postage.',choices:['Pay all nine','Challenge the extra three'],right:1,win:'The Receipt Eater removes the extra three. It eats the surcharge slowly, watching to see whether you check the rest.',miss:'You pay nine for six worth of crumbs. The Receipt Eater writes GOOD CUSTOMER beside your name. It underlines it twice.',later:'The Receipt Eater brings an itemised apology. It has already eaten the part explaining who authorised the fraud.'},
 rain:{title:'An indoor forecast',clue:'The captain’s cloud follows its reflection. Turn the mirror toward the basin.',choices:['Aim the mirror at the basin','Put a hat on the cloud'],right:0,win:'The cloud follows its reflection into the basin. The captain counts everyone on the shelf, then counts again. He puts his hat back on.',miss:'The hat fills with water. The captain removes it very carefully. He has already lost people to a better idea than this.',later:'Captain Indoor Rain returns with a smaller cloud. He has given it the name of the last crew member to answer roll call.'}
};

// Return chapters have new evidence and decisions, rather than replaying the
// first encounter with a changed greeting. No missed-day or wrong-answer penalty.
const RETURNS = {
 moth:[['Reading by a naked flame','The paper shade scorches beside the flame. The glass shade stays clear.','Choose the glass shade','Move the paper closer','The glass shade holds. Madam Moth presses close enough to leave a mark. “I would like to amend my emergency contact.”'],['The farewell rehearsal','The porch lamp points outside. The wardrobe light points into a coat.','Leave the porch lamp on','Illuminate the coat','She follows the porch light outside. “Leave it on.” For once, she sounds less interested in reaching a flame than in finding her way back.']],
 lint:[['The passport office','The Baron’s passport has his portrait but no signature. The blank line is labelled Signature.','Sign the blank line','Add a second portrait','The Baron signs the passport. For the first time, his name authorises his own movement instead of somebody else’s removal.'],['An empire in miniature','The treaty gives everyone access to the shelf. The alternative charges residents rent for standing still.','Ratify shared access','Tax the stationary','The Baron opens the border. Nobody pays him. He stays beside it all afternoon, waiting for gratitude to become a currency.']],
 bell:[['A padded complaint','The felt pad stops the bell touching the table. Removing it lets the vibration reach the wood.','Remove the felt pad','Add another pad','The felt comes away. The table hums. Miss Afterbell laughs once and looks horrified by the sound of it.'],['The quiet concert','A gentle tap makes one clear note. A hard shake makes several clashing notes.','Give one gentle tap','Shake it vigorously','One clear note travels the shelf. Miss Afterbell waits for an answer. None comes. This time, she looks relieved.']],
 needle:[['The missing stitch','The tear is three stitches wide. Two stitches leave a gap; three close it.','Make three stitches','Make two stitches','Three stitches close the tear. Mother Needle holds it up to the light. “People leave gaps when they expect to come back.”'],['A warrant for warmth','The scarf has a loose end. Securing it keeps the stitches from unravelling.','Secure the loose end','Pull the loose end','The loose end is secured. Mother Needle leaves the scarf with you and refuses payment. “You shiver. It interferes with my work.”']],
 widow:[['A zip without closure','The two sides of the zip start at different heights. Aligning the base lets the slider join them.','Align the base first','Pull harder from the top','The aligned zip closes. The widow moves without a rattle. She asks whether you heard anything. She waits for the answer.'],['The memorial button','The memorial coat already has six buttonholes and five buttons. One more button completes the row.','Sew on one button','Cut a seventh hole','The sixth button fills the final hole. “All accounted for,” the widow says. She has brought a seventh button in a separate envelope.']],
 spore:[['A growing resemblance','The frame is squeezing the growing portrait. A wider frame gives it room.','Use a wider frame','Tighten the existing frame','The wider frame gives the family room. A face at the edge exhales. It has been holding its breath since the portrait arrived.'],['The exhibition opens','The new painting sheds spores when shaken. A still stand keeps them on the canvas.','Place it on a still stand','Shake it for the audience','The portrait rests on its stand without shedding spores. Auntie Spore introduces the family. All the painted eyes move towards you. “They remember the help.”']],
 echo:[['An original thought','The cup repeats the final word. To hear welcome, end the sentence with welcome.','Say: You are welcome','Say: Welcome, probably','“Welcome,” says the cup. Little Echo waits for the rest of the sentence. When nothing worse follows, it sits down.'],['A voice of its own','Two cups repeat each other forever. Turning one away ends the loop.','Turn one cup away','Bring the cups closer','The cups stop repeating. Little Echo says “Thank you” once, in a voice you have not heard before. It seems frightened to have kept something for itself.']],
 undertow:[['The grape comparison','The raisin is dry and wrinkled. The grape is plump with water. Both are fruit.','Record the water difference','Diagnose a missing skeleton','Undertow records the water difference. He asks whether you would like to hear the cheaper explanation without the Latin.'],['Discharge papers','The raisin is stable and needs no treatment. The invoice includes a charge for imaginary resuscitation.','Discharge it without the charge','Bill the imaginary procedure','The raisin leaves without a resuscitation charge. Undertow watches it go. “Some families would have paid.” It is the closest he gets to an apology.']],
 tooth:[['Terms of probation','The biscuit line is marked DO NOT CROSS. Standing behind it leaves the biscuits beyond reach.','Stay behind the line','Move the line past the biscuits','The tooth stays behind the line. It asks you to move the biscuits out of sight. The request sounds less like a threat than usual.'],['A letter-opening ceremony','The envelope seam is unglued. Opening the seam preserves the letter; biting the middle tears it.','Open along the seam','Bite through the middle','The seam opens cleanly. Inside is a reference praising the tooth’s restraint. It reads the word restraint several times, without using its jaw.']],
 clock:[['A punctual apology','The invitation says noon. The clock is five minutes fast. At noon it will show 12:05.','Arrive when it shows 12:05','Arrive when it shows 11:55','He arrives at noon. Nobody has aged unexpectedly. He checks the room, then allows himself to take off his coat.'],['A minute freely given','The timer runs for sixty seconds. Turning it twice measures two minutes.','Turn it once','Turn it twice','For sixty seconds, Mr Borrowed Time asks for nothing. He stays until the timer finishes. “That one was mine to give.”']],
 receipt:[['The itemised apology','The apology lists two errors at zero cost. The total should also be zero.','Accept a zero total','Add an apology surcharge','The apology totals zero. The Receipt Eater swallows it before anyone can add conditions. “Let one thing be finished.”'],['A clean account','The ledger shows a debt of six and a payment of six. The balance is zero.','Mark the account settled','Carry six forward','Six paid against six owed. The Receipt Eater closes the account and keeps the blank page. It has spent its life destroying records. It seems unsure how to start one.']],
 rain:[['Cloud nursery','The tiny cloud drips above an open cup. A lid would send the water onto the shelf.','Leave the cup open','Put a lid on the cup','The little cloud fills the open cup. The captain empties it before it overflows. He has learned to intervene before giving the speech.'],['The weather retirement','The umbrella covers the residents. The basin catches the rain. Together they keep the shelf dry.','Keep the umbrella over the residents','Use the umbrella to cover the basin','The umbrella shelters the residents while the basin catches the rain. The captain counts everyone once. He sits down before he can start again.']]
};
export function visitorActFor(id, chapter) {
 const base=VISITOR_ACTS[id];if(!base)return null;
 const next=RETURNS[id]?.[chapter-1];if(!next)return base;
 // Alternate the correct side in return chapters. Evidence determines the answer.
 const right=chapter%2;
 return {...base,title:next[0],clue:next[1],choices:right?[next[3],next[2]]:[next[2],next[3]],right,win:next[4],miss:'They try your suggestion. Nobody volunteers to put their name on it afterward. A second attempt follows. '+next[4]};
}
