export const FRAMES = [
  {id:'wood',name:'Found timber',at:0,line:'It was a tree. It has adjusted poorly.'},
  {id:'brass',name:'Brass exhibition',at:6,line:'Museum standards. Pawn-shop provenance.'},
  {id:'moon',name:'Moon cabinet',at:16,line:'For objects that look different when you blink.'},
  {id:'velvet',name:'Velvet mausoleum',at:32,line:'Nothing has died. The velvet is optimistic.'}
];
export const RELICS = [
  {id:'drawer:0',name:'A sock with diplomatic immunity',shape:'sock',line:'The left sock is still being questioned.'},
  {id:'drawer:1',name:'The missing button’s alibi',shape:'button',line:'It was sewn up. Suspiciously neatly.'},
  {id:'drawer:2',name:'A medal for being lost',shape:'medal',line:'First place. Location unknown.'},
  {id:'fridge:0',name:'A prehistoric pea',shape:'pea',line:'It has outlived three diets and a marriage.'},
  {id:'fridge:1',name:'The spoon of last resort',shape:'spoon',line:'Too small for soup. Exactly right for revenge.'},
  {id:'fridge:2',name:'A refrigerator sun',shape:'sun',line:'They brought back the light. The butter is furious.'},
  {id:'cupboard:0',name:'A thimble full of weather',shape:'rain',line:'Forecast: localised unpleasantness.'},
  {id:'cupboard:1',name:'A formally retired tooth',shape:'tooth',line:'No longer biting. Advising in a consultancy role.'},
  {id:'cupboard:2',name:'The key to a smaller problem',shape:'key',line:'Opens something. Nobody has admitted what.'}
];
export const GEAR = [{id:'thread',name:'Thread & safety pin',hint:'Bridges gaps; rescues things without a speech.'},{id:'lantern',name:'Pocket lantern',hint:'Reveals small print, warm routes, and things pretending to be furniture.'},{id:'biscuit',name:'Emergency biscuit',hint:'A bribe, a distraction, or a last-minute relative.'}];
export const OUTINGS = [
 {id:'drawer',name:'The Lost Sock Drawer',tone:'lilac',intro:'Beyond the runners lies a nation of single socks. They have paired off politically.',steps:[
  {title:'The elastic frontier',text:'A sock blocks the crossing. It wants a toll. The toll is a smaller sock.',good:'thread',stat:'menace',options:['Build a thread bridge','Negotiate with the sock'],outcomes:['They crossed above the border. The sock has annexed the air.','The sock accepted a promise. It now owns a timeshare in your laundry.']},
  {title:'The button tribunal',text:'A button insists it has four eyes. It has four holes. This is a sensitive distinction.',good:'lantern',stat:'mystique',options:['Inspect its four eyewitnesses','Distract the tribunal'],outcomes:['All four witnesses could see through the story. None had seen a thing.','The tribunal adjourned to investigate a biscuit-shaped disturbance.']},
  {title:'The long way home',text:'The drawer starts closing. Someone has found a medal marked OUTSTANDING ABSENCE.',good:'thread',stat:'cute',options:['Lower the treasure on a thread','Ask the socks for safe passage'],outcomes:['The treasure descended with dignity. The residents followed with considerably less.','The socks formed a guard of honour. Half of them had been through this before.']}]},
 {id:'fridge',name:'Under the Fridge',tone:'mint',intro:'A cold kingdom of fossilised dinners. The peas remember your ancestors.',steps:[
  {title:'The frozen pass',text:'A crack in the floor exhales cold air. On the far side, a pea is wearing a crown.',good:'lantern',stat:'damp',options:['Find a warm route with the lantern','Offer a biscuit to the pea'],outcomes:['They followed the warm pipe. The pipe is now their spiritual leader.','The pea accepted tribute and declared winter slightly less personal.']},
  {title:'The cheese oracle',text:'A fragment of cheese predicts that someone will eat it. Its accuracy is troubling.',good:'biscuit',stat:'mystique',options:['Give it a biscuit bodyguard','Question the prophecy'],outcomes:['The bodyguard was eaten first. The cheese has revised its forecast.','The oracle admitted the future was mostly a smell. They wrote that down.']},
  {title:'The light expedition',text:'The fridge opens. A tiny sun appears. The residents have three seconds to invent astronomy.',good:'lantern',stat:'menace',options:['Capture the reflection in the lantern','Demand an audience with the sun'],outcomes:['They bottled a reflection. The original remains on a strict door schedule.','The sun went out mid-speech. The delegation has filed a complaint with the butter.']}]},
 {id:'cupboard',name:'The Cupboard Nobody Opens',tone:'amber',intro:'Nobody opens it. Naturally, somebody small has arranged a guided tour.',steps:[
  {title:'The teaspoon canyon',text:'A stack of teaspoons spans a gap. Every spoon claims to be the load-bearing one.',good:'thread',stat:'cute',options:['Secure a thread handrail','Compliment every spoon'],outcomes:['The handrail held. The spoons have requested equal credit.','Each spoon stood a little straighter. Structural flattery remains unregulated.']},
  {title:'The jar of teeth',text:'A tooth taps the glass. It says it has retired. The jar is full of references.',good:'lantern',stat:'menace',options:['Read its retirement papers','Offer it a softer career'],outcomes:['The papers were tiny and entirely in bite marks. Early retirement confirmed.','The tooth now opens letters. It has described this as a lateral move.']},
  {title:'A key with no door',text:'A key hangs inside a thimble. A cloud rains on it in a very local way.',good:'biscuit',stat:'damp',options:['Shelter the key under a biscuit','Interview the cloud'],outcomes:['The biscuit roof held until someone remembered it was food.','The cloud said it was going through something. They brought the whole situation home.']}]}
];

// Each caller brings a distinct, solvable small problem. First visits establish
// the joke; returning visits remember the previous intervention.
export const VISITOR_ACTS = {
 moth:{title:'The lamp examination',clue:'The warm lamp attracts her. The cold mirror only imitates a light.',choices:['Offer the warm lamp','Recommend the cold mirror'],right:0,win:'Madam Moth circles the lamp, slowly. “A sound bulb. Appalling bedside manner.” She leaves a wing-print of approval.',miss:'She headbutts the reflection once. “A fraudulent light. I shall be leaving a very small review.”',later:'She remembers the lamp inspection. This time she has brought reading glasses for the bulb.'},
 lint:{title:'A border negotiation',clue:'The Baron claims land only when a line encloses it. Leave an opening and it remains a public footpath.',choices:['Tie the lint into a ring','Leave a gap in the boundary'],right:1,win:'The Baron strides through the gap. His empire has become a pedestrian right of way.',miss:'The ring is now a country. Its economy consists of him charging himself rent.',later:'The Baron has returned with a passport the size of his own photograph.'},
 bell:{title:'The missing note',clue:'The bell has lost its sound, but the table still vibrates when it is struck.',choices:['Listen with a fingertip','Shout into the bell'],right:0,win:'Miss Afterbell lets the vibration travel through the plank. The silence gets its pulse back.',miss:'Your shout returns. The bell has outsourced its entire personality to you.',later:'Miss Afterbell brings a second silence. The first one has been getting lonely.'},
 needle:{title:'A stitch in the evidence',clue:'The coat is torn at the seam. A short running stitch joins both edges; a knot tied to only one edge joins nothing.',choices:['Stitch through both edges','Tie a knot in one edge'],right:0,win:'The Mother Needle repairs the seam. “Case closed. Please do not test the verdict by breathing.”',miss:'One edge is now legally bound to itself. The other has fled the jurisdiction.',later:'Mother Needle brings a warrant stitched in very neat letters.'},
 widow:{title:'Mourning dress',clue:'The loose thread belongs to the black coat. The brass button belongs to someone still wearing it.',choices:['Borrow the brass button','Repair the loose black thread'],right:1,win:'The Button Widow closes her coat. “One less opening for grief. Or draughts.”',miss:'The donor arrives still attached. The funeral now has a plus-one.',later:'The widow is no longer looking for closure. She has brought a zip.'},
 spore:{title:'A portrait of the damp',clue:'The painted fungus needs shade and moisture. The sunlit patch is dry; the cup’s shadow is damp.',choices:['Hang it in the damp shade','Frame it in direct sunlight'],right:0,win:'The portrait grows a second subject. “Family resemblance,” says the spore. “Do not ask about the frame.”',miss:'The portrait dries into a landscape of personal regret. The artist declares a new period.',later:'The artist returns with a portrait that is developing opinions.'},
 echo:{title:'Return to sender',clue:'The echo returns from hard surfaces. The cushion absorbs it; the empty cup reflects it.',choices:['Speak into the empty cup','Confide in the cushion'],right:0,win:'The cup repeats the greeting. The echo has finally found somebody who agrees with it for structural reasons.',miss:'The cushion keeps the secret. The echo calls this a hostile takeover of the conversation.',later:'The echo returns with something it heard you say. It has improved the punctuation.'},
 undertow:{title:'A second opinion',clue:'The patient is a raisin. It has no pulse because it is a raisin.',choices:['Prescribe a smaller funeral','Explain the dried-fruit diagnosis'],right:1,win:'The doctor confirms chronic raisin. Prognosis: indefinitely wrinkled.',miss:'The funeral cures nothing, but the catering is remarkably convenient.',later:'The doctor has brought a grape for comparison. It looks worried.'},
 tooth:{title:'A bite-sized dispute',clue:'A clean bite in the biscuit fits one tooth. The fork has three prongs.',choices:['Question the lone tooth','Arrest the fork'],right:0,win:'The tooth admits involvement. It was acting in a chewing capacity.',miss:'The fork demands three lawyers. One for each point of contention.',later:'The tooth is back on probation. No biscuits within biting distance.'},
 clock:{title:'Borrowed minutes',clue:'The stopped clock is right twice a day. The fast clock is never right at the promised time.',choices:['Trust the fast clock','Meet when the stopped clock agrees'],right:1,win:'Mr Borrowed Time arrives exactly once. He considers this a personal record.',miss:'He arrives before the invitation and complains about the lack of suspense.',later:'Mr Borrowed Time has brought back your minute. Slightly chewed.'},
 receipt:{title:'The suspicious total',clue:'Two crumbs at three each cost six. The invoice says nine. The extra three are labelled emotional postage.',choices:['Pay all nine','Challenge the extra three'],right:1,win:'The Receipt Eater eats the surcharge first. “A clerical flavour. Quite bitter.”',miss:'The surcharge is paid. Your grief will arrive in three to five working days.',later:'The Receipt Eater has brought an itemised apology. Several items are edible.'},
 rain:{title:'An indoor forecast',clue:'The captain’s cloud follows its reflection. Turn the mirror toward the basin.',choices:['Aim the mirror at the basin','Put a hat on the cloud'],right:0,win:'Rain falls into the basin. The captain calls this irrigation and immediately promotes himself.',miss:'The hat becomes a lake. Its previous owner has requested swimming lessons.',later:'Captain Indoor Rain brings a smaller cloud. It has inherited the rank.'}
};

// Return chapters have new evidence and decisions, rather than replaying the
// first encounter with a changed greeting. No missed-day or wrong-answer penalty.
const RETURNS = {
 moth:[['Reading by a naked flame','The paper shade scorches beside the flame. The glass shade stays clear.','Choose the glass shade','Move the paper closer','The lamp passes its fire inspection. Madam Moth fails hers by falling in love with it.'],['The farewell rehearsal','The porch lamp points outside. The wardrobe light points into a coat.','Leave the porch lamp on','Illuminate the coat','She follows the porch light, then returns to say goodbye again. The bulb has never felt so needed.']],
 lint:[['The passport office','The Baron’s passport has his portrait but no signature. The blank line is labelled Signature.','Sign the blank line','Add a second portrait','The Baron signs. His entire government is now travelling abroad.'],['An empire in miniature','The treaty gives everyone access to the shelf. The alternative charges residents rent for standing still.','Ratify shared access','Tax the stationary','The Baron opens the border. “An empire of friends,” he says, with the pain of a man discovering public services.']],
 bell:[['A padded complaint','The felt pad stops the bell touching the table. Removing it lets the vibration reach the wood.','Remove the felt pad','Add another pad','The table hums along. Afterbell has founded a choir with excellent attendance and no lungs.'],['The quiet concert','A gentle tap makes one clear note. A hard shake makes several clashing notes.','Give one gentle tap','Shake it vigorously','One note travels the whole shelf. Nobody speaks until it ends. Even the crumb behaves as if it has a mother.']],
 needle:[['The missing stitch','The tear is three stitches wide. Two stitches leave a gap; three close it.','Make three stitches','Make two stitches','Mother Needle closes the gap. “Nothing gets through.” A draught immediately hires a lawyer.'],['A warrant for warmth','The scarf has a loose end. Securing it keeps the stitches from unravelling.','Secure the loose end','Pull the loose end','The scarf stays a scarf. Mother Needle leaves it with you, marked EVIDENCE OF AFFECTION.']],
 widow:[['A zip without closure','The two sides of the zip start at different heights. Aligning the base lets the slider join them.','Align the base first','Pull harder from the top','The coat closes. The widow permits herself a draught-free sigh.'],['The memorial button','The memorial coat already has six buttonholes and five buttons. One more button completes the row.','Sew on one button','Cut a seventh hole','The sixth button takes its place. “He always liked an orderly exit,” she says. Nobody asks which he.']],
 spore:[['A growing resemblance','The frame is squeezing the growing portrait. A wider frame gives it room.','Use a wider frame','Tighten the existing frame','The portrait grows into its frame. It is still a poor likeness, but now confidently so.'],['The exhibition opens','The new painting sheds spores when shaken. A still stand keeps them on the canvas.','Place it on a still stand','Shake it for the audience','The artist unveils a still life that is only technically still. You are thanked in the catalogue as a supporting surface.']],
 echo:[['An original thought','The cup repeats the final word. To hear welcome, end the sentence with welcome.','Say: You are welcome','Say: Welcome, probably','“Welcome,” says the cup. The echo looks surprised to be wanted without a qualifying clause.'],['A voice of its own','Two cups repeat each other forever. Turning one away ends the loop.','Turn one cup away','Bring the cups closer','For once, the echo speaks only once. “Thank you.” The silence afterwards is its own choice.']],
 undertow:[['The grape comparison','The raisin is dry and wrinkled. The grape is plump with water. Both are fruit.','Record the water difference','Diagnose a missing skeleton','Undertow files the report under Natural Causes, Extremely Natural. The grape requests a second opinion anyway.'],['Discharge papers','The raisin is stable and needs no treatment. The invoice includes a charge for imaginary resuscitation.','Discharge it without the charge','Bill the imaginary procedure','The raisin is discharged in the same condition it arrived. Undertow calls this continuity of care.']],
 tooth:[['Terms of probation','The biscuit line is marked DO NOT CROSS. Standing behind it leaves the biscuits beyond reach.','Stay behind the line','Move the line past the biscuits','The tooth obeys. Its parole officer records “promising, though visibly enamelled.”'],['A letter-opening ceremony','The envelope seam is unglued. Opening the seam preserves the letter; biting the middle tears it.','Open along the seam','Bite through the middle','The tooth opens its first letter. It is a reference praising its restraint. It does not bite the reference.']],
 clock:[['A punctual apology','The invitation says noon. The clock is five minutes fast. At noon it will show 12:05.','Arrive when it shows 12:05','Arrive when it shows 11:55','He arrives at noon carrying five minutes of unnecessary anxiety. A personal best.'],['A minute freely given','The timer runs for sixty seconds. Turning it twice measures two minutes.','Turn it once','Turn it twice','For one minute nobody owes anyone anything. He leaves before anyone can issue a receipt.']],
 receipt:[['The itemised apology','The apology lists two errors at zero cost. The total should also be zero.','Accept a zero total','Add an apology surcharge','The Receipt Eater swallows the invoice. “On the house,” it says, tasting the unfamiliar sensation of accountability.'],['A clean account','The ledger shows a debt of six and a payment of six. The balance is zero.','Mark the account settled','Carry six forward','The account is closed. The Receipt Eater keeps the blank page. “For something that isn’t owed.”']],
 rain:[['Cloud nursery','The tiny cloud drips above an open cup. A lid would send the water onto the shelf.','Leave the cup open','Put a lid on the cup','The little cloud fills its first cup. The captain salutes so hard he waters his own shoes.'],['The weather retirement','The umbrella covers the residents. The basin catches the rain. Together they keep the shelf dry.','Keep the umbrella over the residents','Use the umbrella to cover the basin','A small rain falls into its proper place. The captain calls it a peaceful transfer of weather.']]
};
export function visitorActFor(id, chapter) {
 const base=VISITOR_ACTS[id];if(!base)return null;
 const next=RETURNS[id]?.[chapter-1];if(!next)return base;
 // Alternate the correct side in return chapters. Evidence determines the answer.
 const right=chapter%2;
 return {...base,title:next[0],clue:next[1],choices:right?[next[3],next[2]]:[next[2],next[3]],right,win:next[4],miss:'The plan goes sideways. '+next[3]+': an idea now preserved in the minutes under “Before we knew better.” They try again together. '+next[4]};
}
