// Recovery contracts: any two distinct components build a working household toy.
export const PROJECTS = [
 {id:'drawer',name:'The Button Lift',shape:'button',need:'fuss',benefit:'Give every resident up to 6 attention each day',goal:'Build a lift so the residents can reach the good shelf.',line:'The old lift was a loose thread and a verbal promise. The thread outlived the promise.',parts:['A funeral spool','An unclaimed button','A length of bell cord'],action:'Take a ride',reaction:'The lift rises. Everyone cheers except the former safety inspector, whose portrait has fallen off again.'},
 {id:'fridge',name:'The Midnight Larder',shape:'pea',need:'food',benefit:'Feed every resident up to 6 food each day',goal:'Build a tiny larder that keeps a proper midnight supper.',line:'Someone has labelled the empty food cupboard “open casket”. Recover the fittings before the joke becomes a catering policy.',parts:['A frost-proof jar','A silver serving spoon','A brass door latch'],action:'Serve supper',reaction:'Supper is served. The gravy forms a face, sees the cutlery, and stops.'},
 {id:'cupboard',name:'The Thimble Bath',shape:'spoon',need:'clean',benefit:'Give every resident up to 6 cleanliness each day',goal:'Build a working bath. The residents have begun shedding evidence.',line:'The cleaning rota lists three names and the word “presumed”. A bath would settle several outstanding questions.',parts:['A copper thimble','A kettle spout','A spring-loaded plug'],action:'Run the bath',reaction:'The bath bubbles. Something with too many legs climbs out of the drain and asks if breakfast is included.'}
];
export const PROJECT_STOPS = {
 drawer:[
  {title:'The undertaker’s spool',prop:'spool',text:'A spool holds the thread that lowers tiny coffins. The undertaker offers it free if you agree to demonstrate. You need its axle for the lift.',good:'biscuit',stat:'menace',options:['Pay with the emergency biscuit','Unbolt it while he measures you'],outcomes:['He puts the biscuit in the demonstration coffin. It is a surprisingly good fit. You leave with the spool.','You take the axle. Behind you, the coffin descends much faster than advertised. Nobody was in it. The undertaker checks twice.'],quiet:'You decline the fitting and leave the spool. Outside, everyone confirms they are still the same height.'},
  {title:'The button in the glass',prop:'button',text:'A brass button sits behind cracked glass: LAST KNOWN PART OF MR WICK. It would make a perfect lift brake. The display has no alarm. It has a widow.',good:'thread',stat:'cute',options:['Fish it out with the safety pin','Distract the widow and lift the glass'],outcomes:['The pin retrieves the button. The widow asks whether Mr Wick said anything on the way up.','You point out that the portrait has been hung upside down. She apologises to it while you take the button.'],quiet:'You leave the button with the widow. She has already set a second place for it.'},
  {title:'The bell that rings below',prop:'cord',text:'A cord disappears through the drawer floor. Three tugs mean “still alive”. Two mean “cord for sale”. The lift needs a cable.',good:'lantern',stat:'mystique',options:['Light the hole and inspect the knot','Offer two tugs and haul'],outcomes:['The light reveals a knot tied by a bored moth. You take the cord. The moth is relieved to be out of the funeral business.','You tug twice. The cord comes up with a note: NO RETURNS. There is nothing on the other end. You count the tugs again.'],quiet:'You leave the cord and take a long breath. Below, someone copies you.'}
 ],
 fridge:[
  {title:'The jar with a heartbeat',prop:'jar',text:'A preserving jar is tapping from inside. You need its insulated glass for the larder. The label says “best before Tuesday”. Tuesday is tapping back.',good:'lantern',stat:'mystique',options:['Shine through the label','Negotiate vacant possession'],outcomes:['It is a clockwork pea. You wind it down and rehouse it in an egg cup. The jar is yours.','The occupant accepts a warmer shelf. It takes the jam with it. You decide the glass is clean enough.'],quiet:'You leave the jar. The tapping pauses while you pass, which is worse.'},
  {title:'The spoon at the wake',prop:'spoon',text:'A silver spoon is conducting a wake for the yoghurt. You need a serving utensil. The yoghurt died three weeks ago; the wake is waiting for someone to notice.',good:'biscuit',stat:'cute',options:['Offer a biscuit for the mourners','Point out the yoghurt is moving'],outcomes:['The mourners carry the biscuit away shoulder-high. The spoon follows you, grateful to have a smaller job.','The yoghurt sits up. The spoon resigns on the spot. You accept its application.'],quiet:'You wait outside until the smell has a name. It costs you the spoon and restores your nerve.'},
  {title:'The meat drawer latch',prop:'latch',text:'A brass latch guards the meat drawer. The lock is on the inside. Your larder needs a door that opens from the correct side.',good:'thread',stat:'menace',options:['Hook the latch from a distance','Knock, then duck'],outcomes:['The safety pin lifts the latch. Something thanks you through the gap. You install it backwards later.','A chop opens the drawer, holding a smaller chop. You take the latch while they argue about who answered.'],quiet:'You leave the latch. The door knocks politely until you are out of earshot.'}
 ],
 cupboard:[
  {title:'The tailor’s last thimble',prop:'thimble',text:'A copper thimble is being used as an urn. The tailor inside insists it is a bedsit. Your bath needs a basin; there is a larger bottle cap nearby.',good:'biscuit',stat:'cute',options:['Offer biscuit crumbs as a moving fee','Pitch the bottle cap as a penthouse'],outcomes:['The tailor moves, complaining about the commute to his own grave. You rinse the thimble twice.','He asks whether the cap has a sea view. You point it at a leak. He signs before you can feel bad.'],quiet:'You leave the thimble. The tailor raises the rent on himself, just in case.'},
  {title:'The kettle’s loose tooth',prop:'spout',text:'The old kettle calls its removable spout a tooth. It bites the people who argue. You need the spout to get warm water into the bath.',good:'thread',stat:'menace',options:['Loop thread around the loose spout','Tell it this will only hurt briefly'],outcomes:['One careful pull and the spout comes free. The kettle whistles through the gap. It sounds proud.','The kettle asks for a second opinion. You say “loose”. It laughs hard enough to dislodge the spout.'],quiet:'You back away from the kettle. It begins brushing its remaining spout.'},
  {title:'The plug under the floor',prop:'plug',text:'A spring plug seals a hole marked DO NOT DRAIN. Your bath needs it. The warning is written on the underside, where only the trapped would see it.',good:'lantern',stat:'damp',options:['Check the hole with the lantern','Lift the plug and step aside'],outcomes:['The light finds an empty mouse theatre. You take the plug after the final bow. Reviews were poor.','A long sigh escapes. Then a shorter sigh. The third one apologises for making a thing of it. You collect the plug.'],quiet:'You leave the plug and sit somewhere with fewer implications. Two nerve restored.'}
 ]
};
