/* ================= PROPS =================
   Every SVG uses a fixed 0 0 60 60 viewBox (same convention as the original canvas-era
   props), with themeable parts referencing CSS custom properties (var(--wood),
   var(--wood-lip), var(--pink), var(--amber), var(--mint), var(--blood)) so the room/
   wood/accent decor palette re-tints them automatically. */
export const PROP_ART = {
  bowl: '<svg viewBox="0 0 60 60"><ellipse cx="30" cy="34" rx="20" ry="6" fill="var(--wood-lip)"/><path d="M10 34a20 12 0 0 0 40 0z" fill="var(--wood)"/><ellipse cx="30" cy="33" rx="14" ry="4" fill="var(--amber)"/></svg>',
  tub: '<svg viewBox="0 0 60 60"><rect x="10" y="26" width="40" height="20" rx="9" fill="#B9C6CC"/><rect x="14" y="29" width="32" height="9" rx="4" fill="var(--mint)"/><rect x="14" y="46" width="5" height="6" fill="#8A979D"/><rect x="41" y="46" width="5" height="6" fill="#8A979D"/></svg>',
  lamp: '<svg viewBox="0 0 60 60"><circle cx="30" cy="24" r="17" fill="var(--amber)" opacity=".22"/><path d="M18 26h24l-6-13H24z" fill="var(--amber)"/><rect x="28" y="26" width="4" height="20" fill="#8A7A5A"/><ellipse cx="30" cy="47" rx="11" ry="4" fill="#6E6046"/></svg>',
  yarn: '<svg viewBox="0 0 60 60"><circle cx="30" cy="33" r="15" fill="var(--pink)"/><path d="M18 27c8 6 16 8 24 4M17 36c9 5 19 5 26-2M22 44c6 3 13 2 18-2" stroke="rgba(0,0,0,.28)" stroke-width="2" fill="none"/></svg>',
  musicbox: '<svg viewBox="0 0 60 60"><rect x="12" y="30" width="36" height="17" rx="2" fill="#7A4C2B"/><path d="M12 30l6-8h30l-6 8z" fill="#98603A"/><circle cx="42" cy="20" r="3" fill="var(--bone-dim)"/><path d="M42 20v-7h6" stroke="var(--bone-dim)" stroke-width="2" fill="none"/></svg>',
  candle: '<svg viewBox="0 0 60 60"><path d="M30 8c4 6 6 9 6 12a6 6 0 0 1-12 0c0-3 2-6 6-12z" fill="var(--amber)"/><rect x="24" y="24" width="12" height="22" fill="#2B2430"/><ellipse cx="30" cy="46" rx="11" ry="4" fill="#514659"/></svg>',
  fern: '<svg viewBox="0 0 60 60"><path d="M30 40c-2-12-10-18-18-20 4 12 8 18 18 20zM30 40c2-12 10-18 18-20-4 12-8 18-18 20z" fill="#3E7A4A"/><path d="M18 40h24l-3 12H21z" fill="#8A5A3B"/></svg>',
  mirror: '<svg viewBox="0 0 60 60"><ellipse cx="30" cy="28" rx="16" ry="21" fill="#B9C6CC"/><ellipse cx="30" cy="28" rx="12" ry="17" fill="#D8E3E7"/><path d="M24 12l6 14-5 8 8 12" stroke="#8A979D" stroke-width="1.6" fill="none"/><rect x="26" y="48" width="8" height="6" fill="var(--wood)"/></svg>',
  skull: '<svg viewBox="0 0 60 60"><path d="M30 12c11 0 17 8 17 16 0 6-3 9-3 13 0 3-5 5-14 5s-14-2-14-5c0-4-3-7-3-13 0-8 6-16 17-16z" fill="#E8E0CE"/><ellipse cx="23" cy="30" rx="5" ry="6" fill="#2B2028"/><ellipse cx="37" cy="30" rx="5" ry="6" fill="#2B2028"/><path d="M30 36l-3 6h6z" fill="#2B2028"/></svg>',
  coffinbed: '<svg viewBox="0 0 60 60"><path d="M22 22h16l7 12-7 14H22l-7-14z" fill="#4B3350"/><path d="M25 26h10l5 8-5 10H25l-5-10z" fill="var(--pink)" opacity=".55"/></svg>',
  bell: '<svg viewBox="0 0 60 60"><rect x="14" y="44" width="32" height="6" rx="2" fill="var(--wood)"/><path d="M18 44V30a12 12 0 0 1 24 0v14z" fill="#CFE0E5" opacity=".55" stroke="#A9BEC4" stroke-width="1.5"/><circle cx="30" cy="38" r="5" fill="var(--blood)" opacity=".8"/></svg>',
  globe: '<svg viewBox="0 0 60 60"><rect x="18" y="43" width="24" height="7" rx="2" fill="#5A3A46"/><circle cx="30" cy="29" r="16" fill="#CFE0E5" opacity=".5" stroke="#A9BEC4" stroke-width="1.5"/><circle cx="24" cy="24" r="1.6" fill="#fff"/><circle cx="34" cy="30" r="1.6" fill="#fff"/><circle cx="29" cy="36" r="1.6" fill="#fff"/><circle cx="36" cy="21" r="1.4" fill="#fff"/></svg>',
  trophy: '<svg viewBox="0 0 60 60"><path d="M18 46l12 6 12-6-4-14H22z" fill="var(--wood)"/><ellipse cx="30" cy="26" rx="10" ry="9" fill="#C9B79A"/><path d="M22 20l-6-10M38 20l6-10M20 16l-8-6M40 16l8-6" stroke="#8A7A5A" stroke-width="2" fill="none" stroke-linecap="round"/><circle cx="26" cy="25" r="1.6" fill="#2B2028"/><circle cx="34" cy="25" r="1.6" fill="#2B2028"/></svg>',
  board: '<svg viewBox="0 0 60 60"><rect x="10" y="14" width="40" height="30" rx="2" fill="#241833"/><path d="M14 40a16 16 0 0 1 32 0" stroke="var(--amber)" stroke-width="1.4" fill="none"/><circle cx="18" cy="24" r="1.4" fill="var(--amber)"/><circle cx="24" cy="19" r="1.4" fill="var(--amber)"/><circle cx="30" cy="17" r="1.4" fill="var(--amber)"/><circle cx="36" cy="19" r="1.4" fill="var(--amber)"/><circle cx="42" cy="24" r="1.4" fill="var(--amber)"/><path d="M22 34l8-6 8 6-4 8h-8z" fill="var(--blood)" opacity=".7"/><circle cx="30" cy="33" r="2.4" fill="#F2E9DC"/></svg>',
  box: '<svg viewBox="0 0 60 60"><rect x="14" y="26" width="32" height="22" rx="2" fill="var(--wood)"/><rect x="21" y="20" width="18" height="7" rx="1" fill="var(--wood-lip)"/><rect x="24" y="16" width="3" height="10" fill="#F2E9DC"/><rect x="29" y="14" width="3" height="12" fill="#F2E9DC"/><rect x="34" y="17" width="3" height="9" fill="#F2E9DC"/><rect x="20" y="48" width="20" height="3" fill="#3A2A20"/></svg>',
  plant: '<svg viewBox="0 0 60 60"><path d="M30 40c-1-10-6-16-13-19 2 3 4 9 7 13-3 1-6 0-9-2 3 6 9 9 15 8z" fill="#3E7A4A"/><path d="M30 40c1-11 7-17 15-19-3 4-5 10-8 14 3 0 6-1 8-3-4 6-9 9-15 8z" fill="#345F3B"/><ellipse cx="27" cy="30" rx="2" ry="3" fill="var(--blood)" opacity=".6"/><rect x="21" y="40" width="18" height="10" rx="2" fill="var(--wood)"/><path d="M22 50q8 4 16 0" stroke="#2B2028" stroke-width="1" fill="none" opacity=".4"/></svg>'
};

export const PROPS = {
  bowl: { name: 'Snack Bowl', at: 0, aura: { food: 0.62 }, desc: 'Neighbors get hungry more slowly.',
    lines: ['{p} has been at the bowl again. The bowl is empty again.', '{p} says it did not touch the bowl. The bowl disagrees.', '{p} guarded the bowl all night. From nobody.'],
    ambient: ['The bowl was full this morning. It is not now.', 'Something has been licked clean. Twice.'] },
  tub: { name: 'Tin Bathtub', at: 0, aura: { clean: 0.58 }, desc: 'Neighbors stay clean longer.',
    lines: ['{p} got in the tub voluntarily. Everyone is unsettled.', '{p} bathed and has been insufferable since.', '{p} refused the tub, then used it at 3am when nobody was looking.'],
    ambient: ['The water in the tub has changed color. Nobody will say why.', 'There are wet prints leading away from the tub and none leading back.'] },
  lamp: { name: 'Dim Lamp', at: 0, aura: { fuss: 0.8 }, desc: 'A little company. Nocturnal pets resent it.',
    lines: ['{p} sat under the lamp for hours doing nothing.', '{p} has claimed the lamp. There is no sharing arrangement.', '{p} says the light is fine. {p} moved it two inches anyway.'],
    ambient: ['The lamp flickered at the same time three nights running.', 'The bulb is warm and nobody has touched it.'] },
  yarn: { name: 'Ball of Yarn', at: 0, aura: { fuss: 0.75 }, desc: 'Something to destroy. Keeps boredom down.',
    lines: ['{p} unraveled the whole thing and blamed the room.', '{p} has been wrestling the yarn since Tuesday. The yarn is winning.', '{p} tied something up with the yarn. It will not say what.'],
    ambient: ['The yarn is in a different room. Nobody carried it there.', 'There is a string running under the shelf. It leads somewhere.'] },
  musicbox: { name: 'Music Box', at: 6, aura: { fuss: 0.62 }, desc: 'Keeps everyone entertained. Mostly.',
    lines: ['{p} wound the music box and sat through the whole thing.', '{p} plays it on repeat. The others have asked it to stop.', '{p} says the tune has words. It sang them once. Once.'],
    ambient: ['The music box played for eleven seconds at 4am.', 'The lid was closed. It is open now.'] },
  candle: { name: 'Black Candle', at: 6, aura: {}, desc: 'No practical use. They love it.',
    lines: ['{p} has been staring into the candle for two hours.', '{p} lit the candle. Nobody gave it matches.', '{p} says the flame leans toward whoever is lying.'],
    ambient: ['The candle is shorter than it was and has never been lit.', 'Wax has run in a straight line toward the door.'] },
  fern: { name: 'Suspicious Fern', at: 12, aura: { clean: 1.22 }, desc: 'Lovely. Also, things get buried in it.',
    lines: ['{p} buried something in the fern. The fern is thriving.', '{p} has been talking to the fern. The fern has been listening.', '{p} says the fern moved. The fern did move.'],
    ambient: ['The soil has been disturbed again.', 'The fern has grown noticeably since last week. Nobody waters it.'] },
  mirror: { name: 'Cracked Mirror', at: 12, aura: { fuss: 1.18 }, desc: 'Beautiful. Makes everyone slightly worse.',
    lines: ['{p} spent an hour at the mirror and came back different.', '{p} says its reflection blinked first.', '{p} has stopped using the mirror. It will not explain.'],
    ambient: ['The crack is longer today.', 'Something moved in the mirror while the shelf was empty.'] },
  skull: { name: 'Uncle', at: 20, aura: {}, desc: 'A small skull. He came with the house.',
    lines: ['{p} has been telling Uncle about your day.', '{p} moved Uncle so he faces the door. Uncle prefers it.', '{p} says Uncle agrees with it. Uncle has no comment.'],
    ambient: ['Uncle is facing a different way.', 'Uncle was on the top shelf this morning.'] },
  coffinbed: { name: 'Coffin Bed', at: 20, aura: { food: 0.85, fuss: 0.82, clean: 0.85 }, desc: 'Very comfortable. Slows everything down a little.',
    lines: ['{p} slept fourteen hours and woke up rude.', '{p} will not get out of the bed. It has been days.', '{p} has started charging others to nap in it.'],
    ambient: ['The bed was made this morning. Nobody makes the bed.', 'There is a dent in the pillow and everyone is accounted for.'] },
  bell: { name: 'Bell Jar', at: 32, aura: { clean: 0.68 }, desc: 'Keeps the dust off. Keeps other things in.',
    lines: ['{p} got under the bell jar and would not come out.', '{p} put something under the jar. It is best left there.', '{p} taps the glass whenever it walks past.'],
    ambient: ['The jar has fogged from the inside.', 'Whatever is under the jar has moved to the other side.'] },
  globe: { name: 'Snow Globe', at: 32, aura: {}, desc: 'Purely decorative. They are obsessed with it.',
    lines: ['{p} shook the globe forty times in a row.', '{p} says there is somebody in the globe. There is a small figure in the globe.', '{p} watched the snow settle and then did it again.'],
    ambient: ['The snow in the globe is still falling. It has been hours.', 'The little figure is facing outward now.'] },
  trophy: { name: 'Taxidermy Trophy', at: 40, aura: {}, desc: 'A little menace for the shelf. Nobody asks where it came from.',
    lines: ['{p} has been talking shop with the trophy. Career advice, probably.', '{p} salutes the trophy every morning. The trophy does not salute back.', '{p} asked what happened to the rest of it. Nobody answered.'],
    ambient: ['The trophy is facing a different direction than it was yesterday.', 'Something about the trophy is looking fresher than taxidermy should.'] },
  board: { name: 'Spirit Board', at: 40, aura: {}, desc: 'No practical use. They ask it things anyway.',
    lines: ['{p} asked the board a yes-or-no question. It answered in cursive.', '{p} spent an hour on the board and came back oddly formal.', '{p} says the board is "just for fun." The board disagrees.'],
    ambient: ['The planchette has moved two inches since last night.', 'Someone has been asking questions. The board has been answering.'] },
  box: { name: 'Complaint Box', at: 50, aura: { fuss: 0.66 }, desc: 'Give them somewhere to file it. They complain less everywhere else.',
    lines: ['{p} filed something in the box. The box is nearly full.', '{p} checks the box daily for a response. There is no response.', '{p} has started filing complaints about the box itself.'],
    ambient: ['The box is heavier than it should be for how few papers are in it.', 'A slip of paper worked its way out overnight. Nobody wrote it down again.'] },
  plant: { name: 'Weeping Fig', at: 50, aura: { clean: 0.7 }, desc: 'Thrives on grime nobody can identify. Neighbors stay tidier near it.',
    lines: ['{p} has been crying near the fig. The fig started it.', '{p} waters the fig with something that is not water.', '{p} insists the fig "understands" it. Concerning, either way.'],
    ambient: ['The soil is damp in a way the plant should not need.', 'The fig has grown noticeably overnight. Nobody waters it that well.'] }
};
