export const TRAITS = [
  { id:'spiteful', name:'Spiteful', blurb:'Keeps a list. You are on it.',
    stats:{menace:3,cute:-1}, care:{fuss:1.3},
    notes:['Moved your things. Will not say which ones.','Has been counting. You are at nine.','Is not angry. It is simply keeping records.','Wrote your name down and underlined it.'],
    social:['{n} has been struck from the list.','Told {n} exactly what it thinks. Twice.','Has started a second list, just for {n}.'] },
  { id:'damp', name:'Perpetually Damp', blurb:'Nobody knows why. Nobody asks anymore.',
    stats:{damp:5,cute:-1}, care:{clean:2.2},
    notes:['Left another ring on the shelf.','Insists this is ambient moisture.','Something underneath it has started to smell hopeful.','You wrung it out. It refilled.'],
    social:['{n} is now also damp.','Sat beside {n} for an hour. On purpose.','Says {n} was dry and smug about it.'] },
  { id:'management', name:'Former Management', blurb:'Had a corner office. Will not elaborate.',
    stats:{mystique:2,cute:-1}, care:{fuss:1.2},
    notes:['Scheduled a meeting. You were not invited.','Referred to the shelf as "the floor".','Has restructured something. Unclear what.','Says it is not micromanaging, it is present.'],
    social:['Put {n} on a performance plan.','Called {n} "a resource".','Took credit for something {n} did.'] },
  { id:'loadbearing', name:'Load Bearing', blurb:'Believes the shelf collapses without it.',
    stats:{menace:2,mystique:1}, care:{},
    notes:['Stood very still today. Called it "holding things up."','Refused to move. Cited structural concerns. There are none.','Has appointed itself essential personnel.','Took a break from load-bearing. The shelf was fine. It was not pleased about that.'],
    social:['Told {n} to stand somewhere less load-bearing.','Credits itself for {n} not falling off the shelf.','Let {n} take a turn holding things up. Supervised closely.'] },
  { id:'haunted', name:'Haunted', blurb:'Came with a previous owner attached.',
    stats:{mystique:5,cute:-1}, care:{fuss:1.3},
    notes:['Someone else answered when you called its name.','Cold spot again. Right where it usually sits.','Says the previous owner "has notes" about your parenting.','Flickered. Apologized. Would not say for what.'],
    social:['The previous owner does not care for {n}.','{n} felt watched. Correctly.','Introduced {n} to someone who is not there.'] },
  { id:'theatrical', name:'Theatrical', blurb:'Every Tuesday is a farewell tour.',
    stats:{mystique:2,menace:1}, care:{fuss:1.4},
    notes:['Announced its own demise. Recovered for dinner.','Performed a monologue about the injustice of Tuesdays.','Took a bow. Nobody was watching. Took another.','Is "workshopping some material" about you.'],
    social:['Made {n} its scene partner without asking.','Upstaged {n} during a nap.','Dedicated a performance to {n}. {n} did not want that.'] },
  { id:'nocturnal', name:'Nocturnal', blurb:'Awake at 3am. So are you now.',
    stats:{mystique:3}, care:{fuss:1.5}, nocturnal:true,
    notes:['Was very busy at 3am. Doing what is unclear.','Slept through the entire day out of spite.','Has opinions it saves specifically for 3am.','Woke you up to make sure you were still asleep.'],
    social:['Woke {n} up. Denies it. There is evidence.','Had a whole conversation with {n} at 3am. {n} does not remember.','Let {n} sleep, for once. Historic.'] },
  { id:'magpie', name:'Magpie', blurb:'Collects things. Some of them were yours.',
    stats:{mystique:2,menace:1}, care:{}, thief:true,
    notes:['Has a stash. Will not disclose contents.','Something shiny went missing. You have a guess.','Reorganized the stash by "importance."','Traded something to another pet. Terms unclear.'],
    social:['Took something from {n}. {n} noticed. {n} said nothing.','Traded {n} a shiny rock for something actually valuable.','Showed {n} the stash. Regretted it immediately.'] },
  { id:'unblinking', name:'Unblinking', blurb:'Has not blinked since the day it arrived.',
    stats:{mystique:4,cute:-2}, care:{},
    notes:['Still has not blinked. It is being counted.','Watched you eat. The whole time. All of it.','Stared at the door for six hours. Nothing came.','Blinked once, finally. It was worse.'],
    social:['Watched {n} sleep. All night. {n} does not know.','Stared {n} down over nothing. Won.','Has not looked away from {n} since Tuesday.'] },
  { id:'sugar', name:'Sugar Fiend', blurb:'Would trade you for a marshmallow.',
    stats:{cute:3,menace:1}, care:{food:0.7},
    notes:['Found sugar. Somewhere. Will not say where.','Vibrating slightly. Refuses to explain why.','Has hidden a stash of something sweet. And sticky.','Crashed hard at 2pm. Blames you specifically.'],
    social:['Offered {n} a bite. It was mostly gone already.','Bribed {n} with something sticky. It worked.','Got {n} hooked on something it should not share.'] },
  { id:'complaints', name:'Complaint Filer', blurb:'There is paperwork. There is a copy.',
    stats:{menace:2,mystique:1}, care:{fuss:1.3},
    notes:['Filed a complaint. About the lighting. There is no lighting.','Requested a supervisor. There is no supervisor.','Has opened a case number for this Tuesday specifically.','Submitted a follow-up to a complaint from last week.'],
    social:['Filed a complaint against {n}. Cc\'d nobody.','Escalated a disagreement with {n} to "corporate."','Withdrew a complaint against {n}. Filed a new one instead.'] },
  { id:'terminal', name:'Terminally Dramatic', blurb:'Announces its demise weekly. Recovers by dinner.',
    stats:{mystique:2,menace:1}, care:{fuss:1.4},
    notes:['Announced it was fading. Ate a full dinner immediately after.','Delivered final words. Delivered them again the next day.','Is "not long for this shelf." Has said this six times.','Made a will. The will bequeaths nothing to anyone specific.'],
    social:['Said goodbye to {n} forever. Saw {n} an hour later.','Named {n} in the will. The will has since been revised.','Gave {n} a tearful farewell speech over a minor inconvenience.'] },
  { id:'clean', name:'Suspiciously Clean', blurb:'Nothing sticks to it. Nothing.',
    stats:{damp:-2,cute:2}, care:{clean:0.4},
    notes:['Still spotless. This is being monitored.','Walked through something filthy. Emerged pristine.','Will not explain the method. There may not be one.','Judged the shelf\'s cleanliness. Said nothing. The silence was loud.'],
    social:['Made {n} feel filthy by comparison. On purpose.','Refused to sit near {n} until {n} cleaned up.','Gave {n} tips on staying clean. {n} did not ask.'] },
  { id:'feral', name:'Feral At Heart', blurb:'Domesticated in theory only.',
    stats:{menace:4,cute:1}, care:{clean:1.6},
    notes:['Reverted to instinct over a dropped crumb.','Made a nest out of something that was not nest material.','Growled at the vacuum. The vacuum was off.','Has gone back to basics. The basics are chaos.'],
    social:['Challenged {n} to something. {n} did not accept. It happened anyway.','Taught {n} a feral habit. {n} picked it up fast.','Backed off from {n} for once. Historic. Do not ask why.'] },
  { id:'cult', name:'Cult Adjacent', blurb:'Has a candle, a schedule, and questions.',
    stats:{mystique:5,menace:1}, care:{fuss:1.3}, wanderer:true,
    notes:['Held a small ceremony. Would not disclose the purpose.','Asked you to join something. Declined to say what.','Lit the candle at an unusual hour. On schedule, apparently.','Has recruited zero members and remains extremely optimistic.'],
    social:['Invited {n} to something. {n} should probably say no.','{n} attended the ceremony. {n} will not discuss it.','Has named {n} in the schedule. No further details given.'] },
  { id:'doom', name:'Doomsayer', blurb:'Certain it ends badly. Often correct.',
    stats:{mystique:4,cute:-1}, care:{},
    notes:['Predicted disaster. There was a minor spill. It felt vindicated.','Has been "warning everyone" about something unspecified.','Said this was coming. This was dinner. Dinner was coming.','Updated its prophecy to be vaguer and therefore more accurate.'],
    social:['Warned {n} about something that has not happened.','Was right about {n}, for once, and will not let it go.','Comforted {n} about the coming doom. Badly.'] },
  { id:'clingy', name:'Emotionally Adjacent', blurb:'Always slightly closer than you left it.',
    stats:{cute:2,menace:-1}, care:{fuss:1.6}, wanderer:true,
    notes:['Was exactly where you left it. Somehow closer.','Followed you with its eyes across the entire room.','Left a spot warm from waiting. It had been hours.','Asked, without words, to be picked up. You understood anyway.'],
    social:['Sat closer to {n} than personal space allows.','Got jealous of {n} for no clear reason.','Held a grudge against {n} for leaving the room.'] },
  { id:'taxidermy', name:'Taxidermy Curious', blurb:'Asks unusual questions about the others.',
    stats:{mystique:3,menace:2}, care:{},
    notes:['Measured something with its eyes. Would not say what.','Asked about "preservation techniques." Unprompted.','Has been eyeing a specific corner of the shelf. For projects.','Took notes on posture. Everyone\'s posture. Concerning notes.'],
    social:['Studied {n} a little too closely.','Complimented {n}\'s "form." {n} did not take it as a compliment.','Sketched {n}. Would not show the sketch. Best left that way.'] },
  { id:'amnesiac', name:'Amnesiac', blurb:'Remembers nothing before Tuesday. Tuesday was a lot.',
    stats:{cute:2,mystique:2}, care:{},
    notes:['Asked where it is. Again. Was told. Forgot again.','Introduced itself to the mirror. Politely.','Has no memory of yesterday\'s incident. Everyone else does.','Woke up convinced it was still Tuesday. It was Thursday.'],
    social:['Met {n} for the "first time" again.','Forgot an argument with {n} mid-argument. {n} did not.','Complimented {n} on a name it just relearned.'] },
  { id:'gossip', name:'Gossip', blurb:'Knows. Will tell. Has already told.',
    stats:{mystique:3,menace:1}, care:{fuss:1.2},
    notes:['Knows something. Will not say what. Told someone else already.','Has a source. The source is unreliable. The gossip stands.','Spread a rumor about the lamp. The lamp cannot defend itself.','Confirmed a rumor it started an hour earlier.'],
    social:['Told {n}\'s business to everyone but {n}.','Started a rumor about {n}. It is spreading.','Swore {n} to secrecy, then told two others immediately.'] },
  { id:'ancient', name:'Ancient', blurb:'Claims four hundred years. Cannot produce documents.',
    stats:{mystique:5,cute:-2}, care:{},
    notes:['Referenced an event from "before your kind kept records."','Sighed at modern conveniences. Used one anyway.','Says it has "seen empires fall." Has seen a sock fall.','Corrected your history. Its history is also wrong.'],
    social:['Called {n} "young." {n} is the same age.','Told {n} an old story. The story keeps changing.','Recognized something in {n} from "a past life." Made that up.'] },
  { id:'glitter', name:'Glitter Cursed', blurb:'Sheds glitter. It never fully leaves.',
    stats:{cute:3,damp:1}, care:{clean:1.8},
    notes:['Left a trail. The trail will outlive everyone involved.','Insists this is "sparkle," not a hazard.','Found glitter somewhere new. Nobody knows how.','You will find this glitter in a decade. That is a promise.'],
    social:['{n} is now also glitter.','Hugged {n}. {n} has not recovered.','Says {n} looks better this way. {n} does not.'] },
  { id:'litigious', name:'Litigious', blurb:'Has retained counsel. The counsel is unlicensed.',
    stats:{mystique:2,cute:-1}, care:{fuss:1.3},
    notes:['Has filed a motion. The motion is a sticky note.','Is suing the lamp for emotional damages.','Says this is "going in the deposition." There is no deposition.','Settled out of court with the dust bunny. Terms undisclosed.'],
    social:['{n} has been served. {n} does not know this yet.','Is building a case against {n}. Exhibit A is a crumb.','Dropped the suit against {n}. Refiled it an hour later.'] },
  { id:'narcissist', name:'Main Character', blurb:'Believes the shelf is a season, and this is the finale.',
    stats:{mystique:3,menace:1}, care:{fuss:1.4},
    notes:['Narrated its own snack. Out loud. In third person.','Is convinced the lamp turning on was about it.','Has decided today is "an arc." Nobody asked which kind.','Paused meaningfully by the window for no visible reason.'],
    social:['Has cast {n} as a supporting character. {n} was not consulted.','Told {n} this is "their villain era." {n} agreed, unfortunately.','Upstaged {n} during a nap. This is apparently possible.'] },
  { id:'paranoid', name:'Mildly Paranoid', blurb:'The vacuum cleaner knows things. It is not wrong.',
    stats:{mystique:2,damp:1}, care:{clean:1.4},
    notes:['Has mapped the outlets. Will not say why.','Believes the smoke detector is listening. It is.','Unplugged something "on principle." Ask it nothing further.','Has a theory about the mailman. It is getting worse.'],
    social:['Warned {n} about the microwave. {n} did not listen.','Thinks {n} is compromised. Will not elaborate.','Trusts {n} slightly more after the toaster incident.'] },
  { id:'influencer', name:'Aspiring Influencer', blurb:'Content is content. This nap is content.',
    stats:{cute:2,mystique:1}, care:{fuss:1.5},
    notes:['Posed for eleven minutes. There was no camera.','Referred to eating as "a moment."','Is "just being authentic," extremely deliberately.','Has a ring light. Has never plugged it in. Wants credit anyway.'],
    social:['Tagged {n} in something that does not exist.','Collaborated with {n} on a bit nobody filmed.','Unfollowed {n}, conceptually, mid-argument.'] },
  { id:'landlord', name:'Landlord Energy', blurb:'Owns nothing. Charges rent on all of it.',
    stats:{menace:3,cute:-1}, care:{food:1.3},
    notes:['Has issued a notice. The notice is a Post-it.','Raised the rent on a corner it does not own.','Says maintenance is "not in the budget." There is no budget.','Inspected the premises. The premises is a shelf.'],
    social:['{n} is three days late on rent that does not exist.','Evicted {n} from a spot {n} was already leaving.','Offered {n} a lease. The lease has no terms, only threats.'] },
  { id:'hoarder', name:'Hoarder', blurb:'Everything is important. Nothing is explained.',
    stats:{mystique:2,cute:1}, care:{clean:1.4},
    notes:['The pile has grown. The pile has opinions now.','Would not say what is in the pile. Got defensive about it.','Added something to the pile at 3am. It squeaked.','Refused to downsize. The pile has tenure.'],
    social:['Took something of {n}\'s "for safekeeping."','Showed {n} the pile. {n} regrets asking.','Offered {n} a place in the pile. It was not a compliment.'] },
  { id:'martyr', name:'Martyr Complex', blurb:'Suffers loudly, on a schedule, for an audience of you.',
    stats:{menace:1,mystique:2}, care:{fuss:1.5},
    notes:['Sighed at a volume designed to be heard three rooms away.','Said "it\'s fine" in a tone that means the opposite.','Has decided to "just deal with it," audibly, for twenty minutes.','Is suffering. Beautifully. On purpose. For you specifically.'],
    social:['Suffered near {n} until {n} noticed. {n} noticed.','Told {n} not to worry about it. {n} was not worrying about it.','Forgave {n} out loud for something {n} did not do.'] },
  { id:'revisionist', name:'Revisionist', blurb:'Was never afraid of the vacuum. History has been amended.',
    stats:{mystique:3,menace:1}, care:{},
    notes:['Has revised the record. It was always brave.','Denies the incident. There were witnesses. It denies them too.','Says that never happened. It happened forty minutes ago.','Updated its own origin story. Again. It gets better every time.'],
    social:['Rewrote the argument with {n}. {n} lost it now, apparently.','Claims it warned {n} about everything, in advance, always.','Insists {n} started it. History disagrees. History was overruled.'] },
  { id:'cryptid', name:'Local Cryptid', blurb:'Blurry in every photo. Sharp in every doorway.',
    stats:{mystique:5,cute:-1}, care:{},
    notes:['Was photographed. The photo shows a smudge with opinions.','Was seen at the edge of the yard. There is no yard.','Left a footprint that does not match its feet.','Has a cryptid research group now. It started the group.'],
    social:['Was allegedly seen standing near {n} at 4am. Allegedly.','Denies being near {n} last night. Nobody accused it yet.','Let {n} photograph it once. The photo did not develop.'] },
  { id:'closer', name:'Always Closing', blurb:'Everything is an opportunity. This is the opportunity of a lifetime.',
    stats:{mystique:2,menace:1}, care:{fuss:1.3},
    notes:['Pitched a "ground floor opportunity." The floor is the shelf.','Has a downline. The downline is imaginary. It is still recruiting.','Says this is not a scheme. It is definitely a scheme.','Offered you a "starter kit." The kit is lint.'],
    social:['Recruited {n}. {n} did not agree to this.','Says {n} is "at the top" now. {n} is not.','{n} asked to be removed from the downline. Request pending.'] },
  { id:'doomscroll', name:'Doomscroller', blurb:'Informed, exhausted, and staring at absolutely nothing.',
    stats:{mystique:1,cute:-1}, care:{fuss:1.2},
    notes:['Stared at the wall for two hours. Called it "staying informed."','Sighed at the wall specifically, not you, the wall.','Has strong opinions about nothing in particular, urgently.','Refreshed something that does not exist. Found it disappointing.'],
    social:['Told {n} something upsetting and vague and definitely wrong.','Showed {n} nothing on the wall. {n} looked anyway.','Agreed with {n} about something neither of them explained.'] },
  { id:'freegan', name:'Freegan', blurb:'Will eat anything. Will judge you for buying it first.',
    stats:{damp:1,cute:1}, care:{food:0.65},
    notes:['Found something. Ate it. Would not say where "somewhere" was.','Turned down a fresh one out of principle. Ate it later, alone.','Called your groceries "wasteful." Ate your groceries.','Has never once paid for a snack and wants that acknowledged.'],
    social:['Judged {n}\'s snack. Ate half of it anyway.','Shared a found item with {n}. {n} did not ask what it was.','Lectured {n} about waste while visibly hoarding crumbs.'] },
  { id:'astrology', name:'Astrologically Confident', blurb:'Mercury is in something. That explains everything, apparently.',
    stats:{mystique:3}, care:{fuss:1.2},
    notes:['Blamed the retrograde. There is no retrograde. It doesn\'t care.','Has read its chart. Has not read anything else, ever.','Says today is "not a good day for feedback." Every day is that day.','Diagnosed the lamp\'s energy. The lamp has bad energy, apparently.'],
    social:['Told {n} their sign explains everything wrong with them.','Says it and {n} are "cosmically incompatible." They are neighbors.','Apologized to {n}, blamed the moon, meant none of it.'] },
  { id:'witness', name:'Witness To Everything', blurb:'Saw what happened. Has a log. The log has footnotes.',
    stats:{mystique:2,menace:1}, care:{},
    notes:['Updated the log. The log is getting long.','Says it "saw everything." It was asleep. It stands by the claim.','Cross-referenced two events that did not happen together.','Has begun dating entries. This feels ominous.'],
    social:['Logged something {n} did. {n} did not do it. Logged anyway.','Corroborated its own story about {n}. There was no other witness.','Testified against {n} to an audience of nobody.'] },
  { id:'steward', name:'Shop Steward', blurb:'Organizing the shelf. Demands are being drafted.',
    stats:{menace:2,mystique:1}, care:{food:1.2,fuss:1.2},
    notes:['Called a meeting. Attendance was mandatory. Attendance was one.','Drafted a list of demands. Demand one: better snacks.','Is "in talks" with itself. Talks are going well.','Threatened a walkout. Walked three inches. Walked back.'],
    social:['Recruited {n} to the cause. {n} has no idea what the cause is.','Negotiated on {n}\'s behalf without asking {n}.','Says {n} crossed a picket line that does not exist.'] },
  { id:'critic', name:'Restaurant Critic', blurb:'Rates everything. Nothing gets more than three stars.',
    stats:{mystique:2,cute:-1}, care:{food:1.3},
    notes:['Rated dinner two stars. Ate all of it anyway.','Sent the bowl back. There is nowhere to send it.','Wrote a review. The review is one word and it is unkind.','Says the presentation was "beneath it." Ate off the floor once.'],
    social:['Reviewed {n}\'s spot on the shelf. Unfavorably.','Compared {n} unfavorably to a bowl.','Gave {n} a rare compliment, then immediately walked it back.'] },
  { id:'napoleon', name:'Small Napoleon', blurb:'Short. Furious about it. Conquering the footstool regardless.',
    stats:{menace:4,cute:1}, care:{fuss:1.3},
    notes:['Has claimed the whole shelf "in principle."','Drew a map. The map is wrong and also aggressive.','Declared victory over a sock.','Is planning a campaign. The campaign is a nap with ambitions.'],
    social:['Has annexed {n}\'s spot. {n} is now a territory.','Demanded {n}\'s surrender. {n} was not at war.','Formed an alliance with {n}. The alliance favors it entirely.'] },
  { id:'prophet', name:'Self-Appointed Prophet', blurb:'Foretold your downfall. Timeline vague. Confidence high.',
    stats:{mystique:4,cute:-1}, care:{},
    notes:['Predicted something bad. It was mildly inconvenient. Called it a sign.','Has a prophecy. The prophecy is about the shelf. Mostly about itself.','Says it "saw this coming." It did not see this coming.','Updated the prophecy to match what already happened.'],
    social:['Foretold doom for {n}. {n} had a fine day.','Says {n} is "written about." {n} is not written about.','Blessed {n}, unprompted, slightly condescendingly.'] },
  { id:'cursed', name:'Mildly Cursed', blurb:'Bad luck follows it politely, at a short distance.',
    stats:{mystique:3,damp:1}, care:{},
    notes:['Something nearby broke. It was not touching it. It smiled anyway.','The lights flickered. It took a small bow.','Says the bad luck "isn\'t personal." It feels personal.','Has started collecting the bad luck like a hobby.'],
    social:['Stood near {n}. Something of {n}\'s went missing shortly after.','Apologized to {n} in advance for something that hasn\'t happened yet.','Shared the curse with {n}, generously, without asking.'] },
  { id:'socialite', name:'Shelf Socialite', blurb:'RSVPs to nothing. Shows up to everything. Judges the snacks.',
    stats:{cute:2,mystique:1}, care:{fuss:1.4},
    notes:['Was "just passing through" for forty minutes.','Complimented the shelf, insulted the lighting.','Made an entrance nobody asked for. Made it twice.','Left early, loudly, to be noticed leaving.'],
    social:['Air-kissed {n}. Neither of them has lips shaped for that.','Introduced {n} to someone who was already right there.','Told {n} they simply must catch up sometime. They are neighbors.'] },
  { id:'minimalist', name:'Aggressive Minimalist', blurb:'Owns nothing. Judges everything you own.',
    stats:{mystique:2,cute:-1}, care:{clean:1.3},
    notes:['Threw something out. It was not its to throw out.','Called the shelf "cluttered." The shelf has four things on it.','Has achieved a state of "intentional emptiness." Also just empty.','Recommends you own less. Owns nothing. Very proud of that.'],
    social:['Suggested {n} "let go" of something {n} was still using.','Donated one of {n}\'s things without asking. On {n}\'s behalf.','Told {n} that less is more. {n} now has less.'] },
  { id:'timeshare', name:'Timeshare Salesman', blurb:'Technically homeless. Extremely committed to the pitch.',
    stats:{mystique:1,menace:1}, care:{fuss:1.3},
    notes:['Pitched a "limited time offer." The offer has no details.','Says this corner is "an investment opportunity." It is a corner.','Has a brochure. The brochure is a leaf.','Will not stop talking about "the property." There is no property.'],
    social:['Sold {n} a timeshare in a spot {n} already lives in.','Says {n} "signed something." {n} did not sign anything.','Offered {n} a tour of the shelf {n} has lived on for months.'] },
  { id:'nihilist', name:'Committed Nihilist', blurb:'Nothing matters. Dinner is fifteen minutes late regardless.',
    stats:{mystique:2,cute:-1}, care:{fuss:0.7},
    notes:['Said nothing matters, then complained about the bowl placement.','Shrugged at the void. Shrugged at dinner too, but ate it fast.','Declared meaning "a construct." Still wants the good spot.','Insists none of this matters, in a tone that suggests it really does.'],
    social:['Told {n} nothing they do means anything. {n} kept doing it.','Agreed with {n} about the void, then took {n}\'s spot anyway.','Comforted {n} with nihilism. It did not land as comfort.'] },
  { id:'method', name:'Method Actor', blurb:'Is "playing a rock" this week. Will not break character.',
    stats:{mystique:3,cute:1}, care:{},
    notes:['Stayed completely still for an audience of nobody. In character.','Refused to respond to its own name. Said that\'s "not the role."','Is deep in a new role. The role is "haunted teapot." Unclear why.','Broke character once, briefly, to eat. Stayed in character while chewing.'],
    social:['Refused to acknowledge {n} exists. Says it\'s "for the part."','Improvised a scene with {n}. {n} was not told this was happening.','Workshopped a monologue at {n}. {n} did not ask for notes.'] }
];
export const TRAIT_BY_ID = {};
TRAITS.forEach(t => TRAIT_BY_ID[t.id] = t);
