/* ================= TRAITS =================
   Shape: { id, name, blurb, stats, care, notes[], social[] }

   `notes`  render as a shelf note with the pet's own name as the byline, so every
            line must read as a specific observation about THAT pet.
   `social` render the same way but describe a specific neighbor, substituted for
            {n} by engine/loop.js — so {n} must be the object of the sentence, never
            a generic stand-in for "someone".
   `blurb`  is spliced into the pet's bio between HABITS and CLOSERS, so it has to
            work as a standalone sentence in the middle of a paragraph.

   Four traits carry load-bearing boolean flags read by engine/tick.js (isAsleep) and
   engine/loop.js (autonomy): nocturnal, thief, wanderer. Do not remove them. */
export const TRAITS = [
  { id:'spiteful', name:'Spiteful', blurb:'Keeps a list. You are on it.',
    stats:{menace:3,cute:-1}, care:{fuss:1.3},
    notes:['Moved your things. Two inches. All of them.','Has been counting. You are at nine.','Is not angry. It is simply keeping records.','Wrote your name down and underlined it.','Forgave you out loud. Did not cross anything off.'],
    social:['{n} has been struck from the list.','Told {n} exactly what it thinks. Twice.','Has started a second list, just for {n}.','Remembers what {n} did. {n} does not.'] },
  { id:'damp', name:'Perpetually Damp', blurb:'Nobody knows why. Nobody asks anymore.',
    stats:{damp:5,cute:-1}, care:{clean:2.2},
    notes:['Left another ring on the shelf. The rings are forming a pattern.','Insists this is ambient moisture.','You dried the shelf under it. It was wet again by lunch.','You wrung it out. It refilled.'],
    social:['{n} is now also damp.','Sat beside {n} for an hour. On purpose.','Says {n} was dry and smug about it.'] },
  { id:'management', name:'Former Management', blurb:'Had a corner office. Will not elaborate.',
    stats:{mystique:2,cute:-1}, care:{fuss:1.2},
    notes:['Scheduled a meeting. You were not invited.','Referred to the shelf as "the floor".','Has restructured something. Nobody can find what.','Says it is not micromanaging, it is present.'],
    social:['Put {n} on a performance plan.','Called {n} "a resource".','Took credit for something {n} did.','Told {n} its door is always open. {n} does not have a door.'] },
  { id:'loadbearing', name:'Load Bearing', blurb:'Believes the shelf collapses without it.',
    stats:{menace:2,mystique:1}, care:{},
    notes:['Stood very still today. Called it "holding things up."','Refused to move. Cited structural concerns. There are none.','Has appointed itself essential personnel.','Took a break from load-bearing. The shelf was fine. It has not recovered from that.'],
    social:['Told {n} to stand somewhere less load-bearing.','Credits itself for {n} not falling off the shelf.','Let {n} take a turn holding things up. Supervised the whole time.'] },
  { id:'haunted', name:'Haunted', blurb:'Came with a previous owner attached.',
    stats:{mystique:5,cute:-1}, care:{fuss:1.3},
    notes:['Someone else answered when you called its name.','Cold spot again. Right where it usually sits.','Says the previous owner "has notes" about your parenting.','Flickered. Apologized. Flickered again.'],
    social:['The previous owner does not care for {n}.','{n} felt watched. Correctly.','Introduced {n} to someone who is not there.'] },
  { id:'theatrical', name:'Theatrical', blurb:'Cannot simply leave a room. There has to be a door, and a pause.',
    stats:{mystique:2,menace:1}, care:{fuss:1.4},
    notes:['Left the room. Came back. Left again, properly this time.','Held a pause so long that two of the others went to check on it.','Took the long way in for the third time today.','Took a bow. Nobody was watching. Took another.'],
    social:['Made {n} its scene partner without asking.','Waited for {n} to finish, then said the same thing better.','Timed its exit to land the second {n} spoke.','Dedicated a performance to {n}. {n} did not want that.'] },
  { id:'nocturnal', name:'Nocturnal', blurb:'Awake at 3am. So are you now.',
    stats:{mystique:3}, care:{fuss:1.5}, nocturnal:true,
    notes:['Was extremely busy at 3am. The shelf was rearranged by four.','Slept through the entire day out of spite.','Has opinions it saves specifically for 3am.','Woke you up to check that you were still asleep.',"Has been awake since dusk, holding a grudge in the dark like a torch.","Counts you breathing at 3am. Says it is for the records."],
    social:['Woke {n} up. Denies it. There is evidence.','Had a whole conversation with {n} at 3am. {n} does not remember it.','Let {n} sleep, for once. Historic.'] },
  { id:'magpie', name:'Magpie', blurb:'Collects things. Some of them were yours.',
    stats:{mystique:2,menace:1}, care:{}, thief:true,
    notes:['Has a stash under the shelf. The stash is bigger than it is.','Something shiny went missing. You have a guess.','Reorganized the stash by "importance."','Returned one thing. Kept the rest. Wants credit for the one.',"Took the shine off something. The shine is in the stash. The something is not.","Has your key. Has known where your key was for three days."],
    social:['Took something from {n}. {n} noticed. {n} said nothing.','Traded {n} a shiny rock for something actually valuable.','Showed {n} the stash. Regretted it immediately.'] },
  { id:'unblinking', name:'Unblinking', blurb:'Has not blinked since the day it arrived.',
    stats:{mystique:4,cute:-2}, care:{},
    notes:['Still has not blinked. Somebody in this house is keeping count.','Watched you eat. The whole time. All of it.','Stared at the door for six hours. Nothing came.','Blinked once, finally. It was worse.',"Its eyes were dusted this morning. It did not close them for the dusting.","Won a staring contest with the mirror. The mirror has a crack now."],
    social:['Watched {n} sleep. All night. {n} does not know.','Stared {n} down over nothing. Won.','Has not looked away from {n} since Tuesday.'] },
  { id:'sugar', name:'Sugar Fiend', blurb:'Would trade you for a marshmallow.',
    stats:{cute:3,menace:1}, care:{food:0.7},
    notes:['Found sugar. It is four inches tall and the sugar was on a counter.','Vibrating slightly. Refuses to explain why.','Got into something sweet at 4am and has not stopped talking since.','Crashed hard at 2pm. Blames you specifically.',"Licked the underside of the shelf. There was once a sweet there. There was once.","Hid a sultana for later. Later was two minutes."],
    social:['Offered {n} a bite. It was mostly gone already.','Bribed {n} with something sticky. It worked.','Got {n} hooked on something it should not have shared.'] },
  { id:'complaints', name:'Complaint Filer', blurb:'There is paperwork. There is a copy.',
    stats:{menace:2,mystique:1}, care:{fuss:1.3},
    notes:['Filed a complaint. About the lighting. There is no lighting.','Requested a supervisor. There is no supervisor.','Has opened a case number for this Tuesday specifically.','Its complaint from last week has a complaint attached to it now.',"Filed a complaint about the dust. Filed it in triplicate. Filed the triplicate in the dust.","Its complaints have a table of contents now."],
    social:["Filed a complaint against {n}. Cc'd {n}.",'Escalated a disagreement with {n} to "corporate."','Withdrew a complaint against {n}. Filed a better one an hour later.'] },
  { id:'terminal', name:'Terminally Dramatic', blurb:'Announces its demise weekly. Recovers by dinner.',
    stats:{mystique:2,menace:1}, care:{fuss:1.4},
    notes:['Announced it was fading. Ate a full dinner immediately after.','Delivered its final words. Delivered them again the next day.','Is "not long for this shelf." Has said this six times.','Made a will. It is one page and most of it is grievances.',"Requested a priest. Requested a smaller one when the first did not fit.","Has chosen its final resting place. It is the good spot. It is not dying."],
    social:['Said goodbye to {n} forever. Saw {n} an hour later.','Named {n} in the will. The will has since been revised.','Gave {n} a tearful farewell over a slightly cold dinner.'] },
  { id:'clean', name:'Suspiciously Clean', blurb:'Nothing sticks to it. Nothing.',
    stats:{damp:-2,cute:2}, care:{clean:0.4},
    notes:['Still spotless. This is being monitored.','Walked through something filthy. Emerged pristine.','Nothing sticks to it. Not dust, not damp, not the fern.',"Inspected the shelf. Said nothing. Kept saying nothing.","Was damp for four seconds this morning. It has not spoken of it since.","Polished the plank under itself. Only under itself."],
    social:['Made {n} feel filthy by comparison. On purpose.','Refused to sit near {n} until {n} cleaned up.','Gave {n} tips on staying clean. {n} did not ask.'] },
  { id:'feral', name:'Feral At Heart', blurb:'Domesticated in theory only.',
    stats:{menace:4,cute:1}, care:{clean:1.6},
    notes:['Reverted to instinct over a dropped crumb.','Made a nest. Two of the materials were yours.','Growled at the vacuum. The vacuum was off.','Caught something. It is under the shelf and it is smaller than it is.',"Ate a moth. Regretted nothing. Reported the moth as a trespasser.","Has marked the slot. The mark is drying."],
    social:['Challenged {n} to something. {n} did not accept. It happened anyway.','Taught {n} to hiss. {n} was a natural.','Backed off from {n}. First time. Nobody is discussing it.'] },
  { id:'cult', name:'Cult Adjacent', blurb:'Has a candle, a schedule, and questions.',
    stats:{mystique:5,menace:1}, care:{fuss:1.3}, wanderer:true,
    notes:['Held a small ceremony. Would not disclose the purpose.','Asked you to join something. Declined to say what.','Lit the candle at an unusual hour. On schedule, apparently.','Has recruited zero members and remains extremely optimistic.',"Held the ceremony an hour early. The candle had a prior engagement.","Has a robe now. It is a sock. It has a hood."],
    social:['Invited {n} to something. {n} should probably say no.','{n} attended the ceremony. {n} has been quiet and slightly damp since.','Has written {n} into the schedule. No further details given.'] },
  { id:'doom', name:'Doomsayer', blurb:'Certain it ends badly. Often correct.',
    stats:{mystique:4,cute:-1}, care:{},
    notes:['Predicted disaster. There was a minor spill. It felt vindicated.','Has been warning everyone. Everyone is one lamp and a fern.','Said this was coming. This was dinner. Dinner was coming.','Made its warning vaguer. It has been more accurate since.',"Predicted the end of the shelf for Thursday. It was Thursday. It was fine. It says wait.","Said the bracket would give. Tapped the bracket to help it along."],
    social:['Warned {n} about something that has not happened.','Was right about {n}, once, and will not let it go.','Comforted {n} about the coming doom. Badly.'] },
  { id:'clingy', name:'Emotionally Adjacent', blurb:'Always slightly closer than you left it.',
    stats:{cute:2,menace:-1}, care:{fuss:1.6}, wanderer:true,
    notes:['Was exactly where you left it. Somehow closer.','Followed you with its eyes across the entire room.','Was waiting in the doorway. It could not have known which door.','Asked, without words, to be picked up. You understood anyway.',"Has moved one inch closer every hour. There is one inch left.","Held on to your sleeve. You do not own that sleeve anymore."],
    social:['Sat closer to {n} than personal space allows.','Got jealous of {n} for no reason it can name.','Held a grudge against {n} for leaving the room.'] },
  { id:'taxidermy', name:'Taxidermy Curious', blurb:'Asks unusual questions about the others.',
    stats:{mystique:3,menace:2}, care:{},
    notes:['Measured something with its eyes. It was the gap under the shelf.','Asked about "preservation techniques." Unprompted.','Has been eyeing one specific corner of the shelf. For projects.',"Took notes on everyone's posture. The notes include measurements.","Asked whether the previous owner was \"kept\". Followed up.","Has a small jar ready. The jar is labelled. The label is a name."],
    social:['Studied {n} a little too closely.',"Complimented {n}'s \"form.\" {n} did not take it as a compliment.",'Sketched {n}. Would not show the sketch. Best left that way.'] },
  { id:'amnesiac', name:'Amnesiac', blurb:'Remembers nothing before Tuesday. Tuesday was a lot.',
    stats:{cute:2,mystique:2}, care:{},
    notes:['Asked where it is. Again. Was told. Forgot again.','Introduced itself to the mirror. Politely.',"Has no memory of yesterday's incident. Everyone else does.",'Woke up certain it was still Tuesday. It was Thursday.',"Forgot it was angry with you. Got angry with you again from scratch, for a new reason.","Left itself a note. The note says READ THE NOTE."],
    social:['Met {n} for the "first time" again.','Forgot an argument with {n} halfway through it. {n} did not.','Complimented {n} on a name it had just relearned.'] },
  { id:'gossip', name:'Gossip', blurb:'Knows. Will tell. Has already told.',
    stats:{mystique:3,menace:1}, care:{fuss:1.2},
    notes:['Knows something. Told the lamp first, to hear how it sounded.','Has a source. The source is unreliable. The gossip stands.','Spread a rumor about the lamp. The lamp cannot defend itself.','Confirmed a rumor it started an hour earlier.',"Told the fern a secret. The fern has told the soil.","Has a rumour about Uncle. Uncle is a skull. The rumour is holding up."],
    social:["Told {n}'s business to everyone but {n}.",'Started a rumor about {n}. It is spreading.','Swore {n} to secrecy, then told two others immediately.'] },
  { id:'ancient', name:'Ancient', blurb:'Claims four hundred years. Cannot produce documents.',
    stats:{mystique:5,cute:-2}, care:{},
    notes:['Referenced an event from "before your kind kept records."','Sighed at modern conveniences. Used one anyway.','Says it has "seen empires fall." Has seen a sock fall.','Corrected your history. Its history is also wrong.'],
    social:['Called {n} "young." {n} is the same age.','Told {n} an old story. The story keeps changing.','Recognized something in {n} from "a past life." Made that up.'] },
  { id:'glitter', name:'Glitter Cursed', blurb:'Sheds glitter. It never fully leaves.',
    stats:{cute:3,damp:1}, care:{clean:1.8},
    notes:['Left a trail. The trail will outlive everyone involved.','Insists this is "sparkle," not a hazard.','There is glitter inside the sealed jar. The jar has not been opened.','You will find this glitter in a decade. That is a promise.'],
    social:['{n} is now also glitter.','Hugged {n}. {n} has not recovered.','Says {n} looks better this way. {n} does not.'] },
  { id:'litigious', name:'Litigious', blurb:'Has retained counsel. The counsel is unlicensed.',
    stats:{mystique:2,cute:-1}, care:{fuss:1.3},
    notes:['Has filed a motion. The motion is a sticky note.','Is suing the lamp for emotional damages.','Says this is "going in the deposition." There is no deposition.','Settled out of court with the dust bunny. Terms undisclosed.'],
    social:['{n} has been served. {n} does not know this yet.','Is building a case against {n}. Exhibit A is a crumb.','Dropped the suit against {n}. Refiled it an hour later.'] },
  { id:'narcissist', name:'Main Character', blurb:'Believes the shelf is a season, and this is the finale.',
    stats:{mystique:3,menace:1}, care:{fuss:1.4},
    notes:['Narrated its own snack. Out loud. In third person.','Is convinced the lamp coming on was about it.','Has decided today is "an arc." Nobody asked which kind.','Paused meaningfully by the window for no visible reason.'],
    social:['Has cast {n} as a supporting character. {n} was not consulted.','Told {n} this is "their villain era." {n} agreed, unfortunately.','Upstaged {n} during a nap. This is apparently possible.'] },
  { id:'paranoid', name:'Mildly Paranoid', blurb:'The vacuum cleaner knows things. It is not wrong.',
    stats:{mystique:2,damp:1}, care:{clean:1.4},
    notes:['Has mapped the outlets. The map is drawn on the shelf, in dust.','Believes the smoke detector is listening. It is.','Unplugged something "on principle." Ask it nothing further.','Has a theory about the postman. The theory is getting worse.'],
    social:['Warned {n} about the microwave. {n} did not listen.','Thinks {n} is compromised. Has moved one slot further away.','Trusts {n} slightly more since the toaster incident.'] },
  { id:'influencer', name:'Aspiring Influencer', blurb:'Content is content. This nap is content.',
    stats:{cute:2,mystique:1}, care:{fuss:1.5},
    notes:['Posed for eleven minutes. There was no camera.','Referred to eating as "a moment."','Is "just being authentic," extremely deliberately.','Has a ring light. Has never plugged it in. Wants credit anyway.'],
    social:['Tagged {n} in something that does not exist.','Collaborated with {n} on a bit nobody filmed.','Unfollowed {n}, conceptually, mid-argument.'] },
  { id:'landlord', name:'Landlord Energy', blurb:'Owns nothing. Charges rent on all of it.',
    stats:{menace:3,cute:-1}, care:{food:1.3},
    notes:['Has issued a notice. The notice is a Post-it.','Raised the rent on a corner it does not own.','Says maintenance is "not in the budget." There is no budget.','Inspected the premises. The premises is a shelf.'],
    social:['{n} is three days late on rent that does not exist.','Evicted {n} from a spot {n} was already leaving.','Offered {n} a lease. The lease has no terms, only threats.'] },
  { id:'hoarder', name:'Hoarder', blurb:'Everything is important. Nothing is explained.',
    stats:{mystique:2,cute:1}, care:{clean:1.4},
    notes:['The pile has grown. The pile has opinions now.','Was asked what is in the pile. Has not spoken since.','Added something to the pile at 3am. It squeaked.','Refused to downsize. The pile has tenure.'],
    social:["Took something of {n}'s \"for safekeeping.\"",'Showed {n} the pile. {n} regrets asking.','Offered {n} a place in the pile. It was not a compliment.'] },
  { id:'martyr', name:'Martyr Complex', blurb:'Suffers loudly, on a schedule, for an audience of you.',
    stats:{menace:1,mystique:2}, care:{fuss:1.5},
    notes:['Sighed at a volume calibrated for the next room.','Said "it\'s fine" in a tone that means the opposite.','Has decided to "just deal with it," audibly, for twenty minutes.','Is suffering. Beautifully. Where you can see it.'],
    social:['Suffered near {n} until {n} noticed. {n} noticed.','Told {n} not to worry about it. {n} was not worrying about it.','Forgave {n} out loud for something {n} did not do.'] },
  { id:'revisionist', name:'Revisionist', blurb:'Was never afraid of the vacuum. History has been amended.',
    stats:{mystique:3,menace:1}, care:{},
    notes:['Has revised the record. It was always brave.','Denies the incident. There were witnesses. It denies them too.','Says that never happened. It happened forty minutes ago.','Updated its own origin story. It gets better every time.'],
    social:['Rewrote the argument with {n}. {n} lost it now, apparently.','Claims it warned {n} about everything, in advance, always.','Insists {n} started it. History disagrees. History was overruled.'] },
  { id:'cryptid', name:'Local Cryptid', blurb:'Blurry in every photo. Sharp in every doorway.',
    stats:{mystique:5,cute:-1}, care:{},
    notes:['Was photographed. The photo shows a smudge with opinions.','Was seen at the edge of the yard. There is no yard.','Left a footprint that does not match its feet.','Has a research group now. It started the group.'],
    social:['Was allegedly seen standing over {n} at 4am. Allegedly.','Denies being near {n} last night. Nobody had accused it yet.','Let {n} photograph it once. The photo did not develop.'] },
  { id:'closer', name:'Always Closing', blurb:'Everything is an opportunity. This is the opportunity of a lifetime.',
    stats:{mystique:2,menace:1}, care:{fuss:1.3},
    notes:['Pitched a "ground floor opportunity." The floor is the shelf.','Has a downline. The downline is imaginary. It is still recruiting.','Says this is not a scheme. It is definitely a scheme.','Offered you a "starter kit." The kit is lint.'],
    social:['Recruited {n}. {n} did not agree to this.','Says {n} is "at the top" now. {n} is not.','{n} asked to leave the downline. The request is pending.'] },
  { id:'doomscroll', name:'Doomscroller', blurb:'Informed, exhausted, and staring at absolutely nothing.',
    stats:{mystique:1,cute:-1}, care:{fuss:1.2},
    notes:['Stared at the wall for two hours. Called it "staying informed."','Sighed at the wall. Not at you. At the wall.','Is furious about something that has not happened and may not be real.','Refreshed something that does not exist. Found it disappointing.'],
    social:['Told {n} something upsetting, vague and definitely wrong.','Showed {n} nothing on the wall. {n} looked anyway.','Agreed with {n} about something neither of them can explain.'] },
  { id:'freegan', name:'Freegan', blurb:'Will eat anything. Will judge you for buying it first.',
    stats:{damp:1,cute:1}, care:{food:0.65},
    notes:['Found something. Ate it. "Somewhere" is all you are getting.','Turned down a fresh one on principle. Ate it later, alone.','Called your groceries "wasteful." Ate your groceries.','Has never once paid for a snack and wants that acknowledged.'],
    social:["Judged {n}'s snack. Ate half of it anyway.",'Shared a found item with {n}. {n} did not ask what it was.','Lectured {n} about waste while visibly hoarding crumbs.'] },
  { id:'astrology', name:'Astrologically Confident', blurb:'Mercury is in something. That explains everything, apparently.',
    stats:{mystique:3}, care:{fuss:1.2},
    notes:["Blamed the retrograde. There is no retrograde. It does not care.",'Has read its chart. Has not read anything else, ever.','Says today is "not a good day for feedback." Every day is that day.',"Diagnosed the lamp's energy. The lamp has bad energy, apparently."],
    social:['Told {n} its sign explains everything wrong with it.','Says it and {n} are "cosmically incompatible." They are neighbors.','Apologized to {n}, blamed the moon, meant none of it.'] },
  { id:'witness', name:'Witness To Everything', blurb:'Saw what happened. Has a log. The log has footnotes.',
    stats:{mystique:2,menace:1}, care:{},
    notes:['Updated the log. The log is getting long.','Says it "saw everything." It was asleep. It stands by the claim.','Cross-referenced two incidents and concluded they were one incident. They were not.','Has begun dating the entries. This feels ominous.'],
    social:['Logged something {n} did. {n} did not do it. Logged it anyway.','Corroborated its own story about {n}. There was no other witness.','Testified against {n} to an audience of nobody.'] },
  { id:'steward', name:'Shop Steward', blurb:'Organizing the shelf. Demands are being drafted.',
    stats:{menace:2,mystique:1}, care:{food:1.2,fuss:1.2},
    notes:['Called a meeting. Attendance was mandatory. Attendance was one.','Drafted a list of demands. Demand one: better snacks.','Is "in talks" with itself. Talks are going well.','Threatened a walkout. Walked three inches. Walked back.'],
    social:['Recruited {n} to the cause. {n} has no idea what the cause is.',"Negotiated on {n}'s behalf without asking {n}.",'Says {n} crossed a picket line that does not exist.'] },
  { id:'critic', name:'Restaurant Critic', blurb:'Rates everything. Nothing gets more than three stars.',
    stats:{mystique:2,cute:-1}, care:{food:1.3},
    notes:['Rated dinner two stars. Ate all of it anyway.','Sent the bowl back. There is nowhere to send it.','Wrote a review. The review is one word and it is unkind.','Says the presentation was "beneath it." Ate off the floor last week.'],
    social:["Reviewed {n}'s spot on the shelf. Unfavorably.",'Compared {n} unfavorably to a bowl.','Paid {n} a compliment, then walked it back within the hour.'] },
  { id:'napoleon', name:'Small Napoleon', blurb:'Short. Furious about it. Conquering the footstool regardless.',
    stats:{menace:4,cute:1}, care:{fuss:1.3},
    notes:['Has claimed the whole shelf "in principle."','Drew a map. The map is wrong and also aggressive.','Declared victory over a sock.','Is planning a campaign. The campaign is a nap with ambitions.'],
    social:["Has annexed {n}'s spot. {n} is now a territory.",'Demanded {n} surrender. {n} was not at war.','Formed an alliance with {n}. The alliance favors it entirely.'] },
  { id:'prophet', name:'Self-Appointed Prophet', blurb:'Uses a different voice for the prophecies. It is not a good voice.',
    stats:{mystique:4,cute:-1}, care:{},
    notes:['Used the voice at breakfast. It is too early for the voice.','Prophesied something specific about Thursday. It was Thursday.','Announced a sign. The sign was a dropped crumb. It was still an announcement.','Delivered a prophecy in the voice, then asked, normally, whether that landed.'],
    social:['Foretold doom for {n}. {n} had a lovely day.','Says {n} is "written about." {n} is not written about.','Used the voice on {n}. {n} left.'] },
  { id:'cursed', name:'Mildly Cursed', blurb:'Bad luck follows it politely, at a short distance.',
    stats:{mystique:3,damp:1}, care:{},
    notes:['Something nearby broke. It was not touching it. It smiled anyway.','The lights flickered. It took a small bow.','Says the bad luck "isn\'t personal." It feels personal.','Has begun keeping the bad luck in one place. The place is your side of the shelf.'],
    social:["Stood near {n}. Something of {n}'s went missing shortly after.",'Apologized to {n} in advance for something that has not happened yet.','Shared the curse with {n}. Generously. Without asking.'] },
  { id:'socialite', name:'Shelf Socialite', blurb:'RSVPs to nothing. Shows up to everything. Judges the snacks.',
    stats:{cute:2,mystique:1}, care:{fuss:1.4},
    notes:['Was "just passing through" for forty minutes.','Complimented the shelf, insulted the lighting.','Made an entrance nobody asked for. Made it twice.','Left early, loudly, to be noticed leaving.'],
    social:['Air-kissed {n}. Neither of them has lips shaped for that.','Introduced {n} to someone who was already right there.','Told {n} they simply must catch up sometime. They are neighbors.'] },
  { id:'minimalist', name:'Aggressive Minimalist', blurb:'Owns nothing. Judges everything you own.',
    stats:{mystique:2,cute:-1}, care:{clean:1.3},
    notes:['Threw something out. It was not its to throw out.','Called the shelf "cluttered." The shelf has four things on it.','Has achieved a state of intentional emptiness. Also just empty.','Recommends you own less. Owns nothing. Very proud of that.'],
    social:['Suggested {n} "let go" of something {n} was still using.',"Donated one of {n}'s things. On {n}'s behalf. Without telling {n}.",'Told {n} that less is more. {n} now has less.'] },
  { id:'timeshare', name:'Timeshare Salesman', blurb:'Technically homeless. Extremely committed to the pitch.',
    stats:{mystique:1,menace:1}, care:{fuss:1.3},
    notes:['The offer expires tonight. It has expired every night for a month.','Says this corner is "an investment opportunity." It is a corner.','Has a brochure. The brochure is a leaf.','Referred to the corner as "the property" nine times before lunch.'],
    social:['Sold {n} a timeshare in the spot {n} already lives in.','Says {n} "signed something." {n} did not sign anything.','Offered {n} a tour of the shelf {n} has lived on for months.'] },
  { id:'nihilist', name:'Committed Nihilist', blurb:'Nothing matters. Dinner is fifteen minutes late regardless.',
    stats:{mystique:2,cute:-1}, care:{fuss:0.7},
    notes:['Said nothing matters, then complained about the bowl placement.','Shrugged at the void. Shrugged at dinner too, but ate it fast.','Declared meaning "a construct." Still wants the good spot.','Insists none of this matters, in a tone that suggests it really does.'],
    social:['Told {n} nothing it does means anything. {n} kept doing it.','Agreed with {n} about the void, then took {n}\'s spot.','Comforted {n} with nihilism. It did not land as comfort.'] },
  { id:'method', name:'Method Actor', blurb:'Is "playing a rock" this week. Will not break character.',
    stats:{mystique:3,cute:1}, care:{},
    notes:['Stayed completely still for an audience of nobody. In character.','Refused to answer to its own name. Says that is "not the role."','Is deep in a new role. The role is "haunted teapot." It has the posture.','Broke character once, briefly, to eat. Stayed in character while chewing.'],
    social:['Refuses to acknowledge {n} exists. Says it is "for the part."','Improvised a scene with {n}. {n} was not told this was happening.','Workshopped a monologue at {n}. {n} did not ask for notes.'] },

  /* ---- gothic-domestic expansion ---- */
  { id:'undertaker', name:'Undertaker Adjacent', blurb:'Offers its condolences early. Says it saves time later.',
    stats:{mystique:3,menace:1,cute:-1}, care:{fuss:1.2},
    notes:['Offered its condolences. Nothing has happened yet.','Asked whether you had "made arrangements." You are perfectly healthy.','Has been measuring the shelf. Lengthwise. In sections.','Says it does not want to alarm anyone. It has said this four times today.','Wrote a date down, folded the paper, and put it somewhere.'],
    social:['Told {n} it would handle everything "when the time comes."','Has quietly reserved a spot for {n}. {n} is fine. {n} is right there.','Asked {n} about next of kin. {n} does not have kin.','Offered {n} a discount. {n} did not ask what for.'] },
  { id:'mourner', name:'Professional Mourner', blurb:'Grieves loudly, on schedule, for people it never met.',
    stats:{damp:2,mystique:2,cute:1}, care:{fuss:1.3},
    notes:['Wept for forty minutes about a stranger. Recovered instantly at dinner.','Has scheduled its grief for four o\'clock. It is extremely punctual.','Practised its wailing quietly. For range.','Grieved a spider, then ate beside the spider. The spider was fine.','Says nobody grieves properly anymore. Demonstrated properly. At length.'],
    social:['Grieved for {n} at length. {n} is not dead. {n} was in the room.','Told {n} its crying was "technically fine." A professional note.','Offered to handle the grieving on {n}\'s behalf. For a fee.','Wept through {n}\'s entire nap, at volume, four inches away.'] },
  { id:'understudy', name:'The Understudy', blurb:'Has learned everyone else\'s part. Is not in a hurry.',
    stats:{mystique:3,menace:2,cute:-1}, care:{},
    notes:['Knows everyone\'s lines. Has never been asked to say any of them.','Stood in somebody else\'s spot for an hour and got the posture exactly right.','Asked, politely, what happens if somebody is unavailable.','Has a costume. Nobody has seen the costume.','Is not waiting for anything in particular. It is simply ready.'],
    social:['Has learned {n}\'s part. All of it. Including the walk.','Asked {n} how it was feeling. Wrote the answer down.','Did an impression of {n}. It was accurate to the point of rudeness.','Told {n} to take all the time it needs. {n} was not going anywhere.'] },
  { id:'executor', name:'Estate Executor', blurb:'Is dividing up your things. You are still using them.',
    stats:{menace:2,mystique:2}, care:{fuss:1.2},
    notes:['Has assigned your mug to somebody. You were not consulted.','Read out a list of your belongings. Used the past tense throughout.','Says the paperwork is "mostly in order." There is no paperwork.','Asked which of your things you are most attached to. Wrote it down.','Opened a probate. You are not eligible for probate. It proceeded anyway.'],
    social:['Left {n} the good corner, in writing, effective at an unspecified date.','Told {n} it is "in the will." There is no will. There is a list.','Contested something on {n}\'s behalf. {n} had not raised anything.','Removed {n} from the list. The list is four inches long.'] },
  { id:'heirloom', name:'Family Heirloom', blurb:'Belonged to your grandmother. Has opinions about your grandmother.',
    stats:{mystique:4,cute:1}, care:{clean:0.8},
    notes:['Says your grandmother did it differently. It never met your grandmother.','Recognized the good china. Sighed.','Mentioned an argument from 1974. Nobody in this room was born.','Says it has "been in the family." It has never said it liked the family.','Was in a drawer for thirty years and has not let that go.'],
    social:['Told {n} about your grandmother. Told {n} the unflattering version.','Says {n} would not have lasted a week in the old house.','Called {n} "new." {n} has been here two years.','Compared {n} unfavorably to something that has been in a box since 1981.'] },
  { id:'bones', name:'Bone Collector', blurb:'Collects bones. Small ones. There is a system.',
    stats:{menace:3,mystique:2,cute:-1}, care:{clean:1.3},
    notes:['Added something to the collection. The collection is under the shelf now.','Sorted the collection by size. Is now sorting it by something else.','Found a tooth. Was delighted. Nobody else was.','Says the collection is nearly complete. Nobody has asked what complete means.','Is missing one. Has been missing one for a while now.'],
    social:['Looked at {n} for a long time, then looked at the collection.','Asked {n} how many teeth {n} has. {n} did not answer.','Offered {n} a piece of the collection as a gift. {n} declined.','Says {n} would "round it out nicely." Would not elaborate.'] },
  { id:'swarm', name:'Not One Thing', blurb:'Is several small things in a convincing arrangement.',
    stats:{mystique:4,cute:2,menace:1}, care:{food:1.3},
    notes:['Came apart briefly in the night and reassembled slightly wrong.','Ate for four. There is one of it. Allegedly.','Was counted twice by two different people. Both counts were correct.','Part of it went to the kitchen. The rest of it stayed here.','Says it is one thing. Says it in more than one voice.'],
    social:['Sat beside {n}. Some of it sat on the other side of {n} as well.','Whispered to {n} from two directions at once.','Lent {n} a piece of itself. Wants it back by Thursday.','Agreed with {n} unanimously. It was the only one voting.'] },
  { id:'fullname', name:'Uses Your Full Name', blurb:'Knows your middle name. Deploys it.',
    stats:{menace:3,mystique:1}, care:{fuss:1.2},
    notes:['Used your full name. You have not heard your full name since school.','Learned your middle name somewhere. You have never said it in this house.','Says your name the way your mother says it. Exactly that way.','Wrote your name out in full and put the date beside it.','Has not used your name at all today.'],
    social:['Called {n} by a name {n} has not used in years.','Said {n}\'s full name out loud. {n} sat up immediately.','Knows something {n} is called that {n} has never mentioned.','Has started referring to {n} by a number. The number is not one to six.'] },
  { id:'auditor', name:'The Auditor', blurb:'Has your receipts. All of them. Yes, that one.',
    stats:{menace:2,mystique:2,cute:-1}, care:{fuss:1.2},
    notes:['Went through the receipts. Found something. Has not said what.','Asked about a purchase from March. You do not remember March.','Says the numbers do not reconcile. There are no numbers.','Has flagged something. The flag is a torn piece of napkin.','Said this would only take a moment. It has been a week.'],
    social:['Requested documentation from {n}. {n} is a small animal.','Found a discrepancy in {n}\'s snacks and opened a file.','Told {n} it is "nothing to worry about," which is how these start.','Cleared {n} of everything and scheduled a follow-up anyway.'] },
  { id:'insomniac', name:'Has Not Slept', blurb:'Not once. Not since it arrived. Says it is fine.',
    stats:{mystique:3,menace:1,cute:-1}, care:{fuss:1.4},
    notes:['Has not slept. It would like that on the record.','Was awake when you went to bed and awake when you got up. Same position.','Says it does not need sleep. Its face disagrees.','Watched the entire night happen and has notes about it.','Fell asleep for four seconds and is furious about the lost time.'],
    social:['Watched {n} sleep and has thoughts about how easy {n} makes it look.','Told {n} what happened at 4am. {n} did not want to know.','Has been awake for every one of {n}\'s naps. Counted them.','Asked {n} how it does it. {n} could not explain. That made it worse.'] },
  { id:'reflection', name:'Reflection Issues', blurb:'Its reflection runs half a second late. Consistently.',
    stats:{mystique:5,cute:-1}, care:{},
    notes:['Waved at the mirror. The mirror waved back a moment later.','Sat down. Its reflection stayed standing for a beat.','Has stopped going near the mirror. The mirror has not stopped.','Says the delay is getting longer. It has been measuring.','Smiled at itself. Waited. Was smiled at.'],
    social:['Stood between {n} and the mirror. Only one of them arrived on time.','Asked {n} to check something in the glass. {n} will not do it again.','Its reflection looked at {n} before it did.','Told {n} the mirror is fine. Said it while facing away from the mirror.'] },
  { id:'etiquette', name:'Etiquette', blurb:'There is a correct fork. There is a correct mourning period. You have both wrong.',
    stats:{cute:1,menace:2,mystique:1}, care:{clean:0.75,fuss:1.2},
    notes:['Corrected your posture. You were alone.','Says the mourning period for the fern was observed incorrectly.','Refused to eat until the bowl was placed properly. It was two inches out.','Wrote a thank-you note for something you have not done yet.','Says it is not judging, it is noticing. There is a difference, apparently.'],
    social:['Told {n} which fork. There is one fork.','Corrected {n} mid-sentence. Twice. Politely both times.','Says {n} was raised in a barn. {n} was raised in a box.','Hand-delivered {n} a note about {n}\'s conduct, then waited.'] },
  { id:'hummer', name:'Hums', blurb:'A tune you nearly recognize. It will not stop until you do.',
    stats:{mystique:3,cute:1}, care:{},
    notes:['Hummed the same eleven notes all afternoon.','Stopped humming the moment you looked up. Started again when you looked away.','You almost had the tune. It changed key.','Hummed something your mother used to hum. You have not mentioned your mother.','The humming stopped for an hour. That was much worse.'],
    social:['Hummed at {n} until {n} left the shelf.','Taught {n} the tune. {n} cannot get rid of it now.','Hummed {n}\'s least favorite eleven notes. On purpose. Repeatedly.','Stopped humming when {n} sat down, then started again the moment {n} relaxed.'] },
  { id:'lifecoach', name:'Life Coach', blurb:'Believes in you. Aggressively. With a timeline.',
    stats:{cute:2,menace:2}, care:{fuss:1.4},
    notes:['Believes in you. Has said so four times. It is starting to feel like a deadline.','Asked where you see yourself in five years and waited for a real answer.','Says today is day one. It said that yesterday.','Has set a goal for you. You were not present when it was set.','Told you it is proud of you in a tone that implied a follow-up meeting.'],
    social:['Told {n} it could be so much more. {n} was asleep.','Set {n} a stretch goal. {n} is a small animal on a shelf.','Says {n} is not living up to its potential. {n}\'s potential is naps.','Gave {n} a deadline. {n} does not experience time that way.'] },
  { id:'sleepwalker', name:'Sleepwalker', blurb:'Wakes up somewhere else. Every time.',
    stats:{mystique:4,cute:1}, care:{clean:1.2}, wanderer:true,
    notes:['Went to sleep in one spot and woke up in another. Has no theory.','Was found standing up, facing the wall, entirely asleep.','Left the shelf in the night. Came back. Brought something.','Says it does not sleepwalk. There are prints. The prints are its size.','Woke up holding something that belongs in the kitchen.'],
    social:['Woke up beside {n}. Neither of them arranged that.','Was found asleep, standing over {n}. {n} has changed spots since.','Took something of {n}\'s in its sleep and returned it in its sleep.','Says {n} moved it in the night. {n} has an alibi. {n} was also asleep.'] },
  { id:'bitey', name:'Bites', blurb:'Bites. Denies biting. There are marks.',
    stats:{menace:4,cute:1}, care:{food:1.2},
    notes:['Bit something. There are marks in three places and all of them are small.','Bit you. Looked surprised. It was not surprised.','Has been told not to bite. Has been told this eleven times.','Did not bite anything today and expects to be rewarded for it.','Bit the shelf. The shelf had done nothing. That is not a defense, apparently.'],
    social:['Bit {n}. Says {n} started it. {n} was asleep.','Did not bite {n} today. {n} has noticed the change and is nervous.','Bit {n} on the ear, gently. It considers that affection.','Has been keeping count of every time it has not bitten {n}.'] },
  { id:'fungal', name:'Fungal', blurb:'Spreading. Politely. With a permission it never asked for.',
    stats:{damp:4,mystique:2,cute:-1}, care:{clean:1.9},
    notes:['Something is growing on its left side. It calls that side "the expansion."','Has colonized a corner of the shelf and refers to it as an annex.','Says it is not spreading. It was measured yesterday and again today.','Left a small ring of something. The ring is a perfect circle.','Was wiped down entirely. It was back by evening, in the same pattern.'],
    social:['Sat next to {n}. Something has started on {n}\'s left side.','Offered {n} a spore. Framed it as a housewarming gift.','Says {n} would benefit from "a little growth." {n} understood the threat.','Shook hands with {n}. There had been no need to shake hands.'] },
  { id:'porcelain', name:'Porcelain', blurb:'Fragile. Aware of it. Has learned exactly what that is worth.',
    stats:{cute:3,menace:2,mystique:1}, care:{clean:0.7,fuss:1.3},
    notes:['Reminded you it is fragile. It was being asked to move two inches.','Has a new crack. It appeared during an argument it was already winning.','Says it could break at any moment. It has been saying this for a year.','Leaned dangerously close to the edge until you got up.','Chipped itself on purpose and left the chip where you would find it.'],
    social:['Told {n} to be careful. {n} was across the shelf.','Held a chip up so {n} could see it. Did not say how it got there.','Says {n} nearly broke it. {n} has not moved all day.','Let {n} apologize for a full minute before mentioning it was already cracked.'] },
  { id:'physician', name:'Attending Physician', blurb:'Unlicensed. Extremely confident. Has a diagnosis for you.',
    stats:{menace:2,mystique:2}, care:{food:1.2,fuss:1.2},
    notes:['Has diagnosed you. Will share the diagnosis when it is ready.','Took your pulse while you were asleep and wrote a number down.','Says the lamp has a condition. The lamp is a lamp.','Prescribed rest, fluids, and "less of whatever you have been doing."','Said it does not want to worry you, then used a word you have never heard.'],
    social:['Diagnosed {n} from across the shelf, from memory, in under a second.','Told {n} the results were "not what we hoped." There were no tests.','Gave {n} a clean bill of health, then booked a second opinion with itself.','Says {n} should have come in sooner. {n} lives four inches away.'] }
];
export const TRAIT_BY_ID = {};
TRAITS.forEach(t => TRAIT_BY_ID[t.id] = t);
